{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-analytics",
    "version": "1.7.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.7.25"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-1.7.25.aar",
          "url": "nautilus-analytics-1.7.25.aar",
          "size": 154811,
          "sha512": "3ccd635bcaafc9792f143f8f1bc604131c827606932a9221e06c7db0833c89cf4d50d52d6265d56e40babecea34f936b0b5ce8e9f9d539d7d27f145ea7463b10",
          "sha256": "fd922b45b60be4dce7a4fd5fbbdacef31759bd19c30600ce81c7f14b180c80a1",
          "sha1": "c0ec6a8bb9bf6bbac46ef7b9aa178194ea1bf227",
          "md5": "eeea8973a8ee7d9f58365f68f8408aa7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.7.25"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-1.7.25.aar",
          "url": "nautilus-analytics-1.7.25.aar",
          "size": 154811,
          "sha512": "3ccd635bcaafc9792f143f8f1bc604131c827606932a9221e06c7db0833c89cf4d50d52d6265d56e40babecea34f936b0b5ce8e9f9d539d7d27f145ea7463b10",
          "sha256": "fd922b45b60be4dce7a4fd5fbbdacef31759bd19c30600ce81c7f14b180c80a1",
          "sha1": "c0ec6a8bb9bf6bbac46ef7b9aa178194ea1bf227",
          "md5": "eeea8973a8ee7d9f58365f68f8408aa7"
        }
      ]
    }
  ]
}
