{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-campaign",
    "version": "1.15.7-hotfix1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.15.7-hotfix1"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-format",
          "version": {
            "requires": "1.15.7-hotfix1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-campaign-1.15.7-hotfix1.aar",
          "url": "nautilus-campaign-1.15.7-hotfix1.aar",
          "size": 138282,
          "sha512": "b39366df94207e32b1b36c611975601407f6af512bd7080d7b191fd0a4cef4dfc259c3386e6f4d990ed3a156c653e3da4de2d52427a1c049be21e2cd855ed195",
          "sha256": "47888b622ea72401843aa73d75aca42bf966babc905243a46314a1d370c4ecb6",
          "sha1": "bd0bffb7acca709518a19a4ccf933740552f5a21",
          "md5": "35bec7d3a0cbe8de6b205b1cc7110f6c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.15.7-hotfix1"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-format",
          "version": {
            "requires": "1.15.7-hotfix1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-campaign-1.15.7-hotfix1.aar",
          "url": "nautilus-campaign-1.15.7-hotfix1.aar",
          "size": 138282,
          "sha512": "b39366df94207e32b1b36c611975601407f6af512bd7080d7b191fd0a4cef4dfc259c3386e6f4d990ed3a156c653e3da4de2d52427a1c049be21e2cd855ed195",
          "sha256": "47888b622ea72401843aa73d75aca42bf966babc905243a46314a1d370c4ecb6",
          "sha1": "bd0bffb7acca709518a19a4ccf933740552f5a21",
          "md5": "35bec7d3a0cbe8de6b205b1cc7110f6c"
        }
      ]
    }
  ]
}
