{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-network",
    "version": "1.9.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.9.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.9.4.aar",
          "url": "nautilus-util-network-1.9.4.aar",
          "size": 23241,
          "sha512": "56623c248c83504a6734baf741cf4f31bcb7099efb2bc7661b183ebdcb4c642296ebc304e8eda9fe3fa2518164a3ca0cef5756448d3b1d2141a16a4cdc5eb89a",
          "sha256": "59eccecf9f7a1aa0fd9f86be22331df537c1d6b3436627b6b5e7399d506d1659",
          "sha1": "904dd0d9bbb25fd02e93214d37bd48f873399674",
          "md5": "00ef932556e4c9e215e7e136f64b87b9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.9.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.9.4.aar",
          "url": "nautilus-util-network-1.9.4.aar",
          "size": 23241,
          "sha512": "56623c248c83504a6734baf741cf4f31bcb7099efb2bc7661b183ebdcb4c642296ebc304e8eda9fe3fa2518164a3ca0cef5756448d3b1d2141a16a4cdc5eb89a",
          "sha256": "59eccecf9f7a1aa0fd9f86be22331df537c1d6b3436627b6b5e7399d506d1659",
          "sha1": "904dd0d9bbb25fd02e93214d37bd48f873399674",
          "md5": "00ef932556e4c9e215e7e136f64b87b9"
        }
      ]
    }
  ]
}
