{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-content",
    "version": "1.7.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-imaging",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-config",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-view",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-livedata",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-format",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-analytics",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-content-1.7.6.aar",
          "url": "nautilus-content-1.7.6.aar",
          "size": 799069,
          "sha512": "d63a1e006e6210fcde65e516eb8166e711c45c8e5f5d14b780de1578e648ce5b36419796f3fdfc695de0042d753ffa709987a2b3d301221186aacf93d7826cc0",
          "sha256": "38668f80c918282c2304e6648658b0f09d755e772b83da94ad247bf04086709a",
          "sha1": "8263a9ba4ff0fb957edbcc89cc1746a596f71402",
          "md5": "443b1d07ce0e8719c75d593914b549ca"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-imaging",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-config",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-view",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-livedata",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-format",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-analytics",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.3"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.4.3"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-content-1.7.6.aar",
          "url": "nautilus-content-1.7.6.aar",
          "size": 799069,
          "sha512": "d63a1e006e6210fcde65e516eb8166e711c45c8e5f5d14b780de1578e648ce5b36419796f3fdfc695de0042d753ffa709987a2b3d301221186aacf93d7826cc0",
          "sha256": "38668f80c918282c2304e6648658b0f09d755e772b83da94ad247bf04086709a",
          "sha1": "8263a9ba4ff0fb957edbcc89cc1746a596f71402",
          "md5": "443b1d07ce0e8719c75d593914b549ca"
        }
      ]
    }
  ]
}
