{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-json",
    "version": "1.7.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-json-1.7.4.aar",
          "url": "nautilus-util-json-1.7.4.aar",
          "size": 11145,
          "sha512": "06cbbe83e4346a54f2fc1a379be6dce2d3392c39ac6b856f271fafd002636e35e26377dd3e7b75dc54e4f7638298cf5aae04ba4183e0afbfa10904cc04cadfa5",
          "sha256": "9c00809ff5b4d9bcd48fd11c67ee489063d88fca026e1d08b0ec9ebbb83f15da",
          "sha1": "55e006683b8edd82af71ba3edc2620cec2af3d00",
          "md5": "99744bb9ffb8811f6ce52338f5ea7784"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-json-1.7.4.aar",
          "url": "nautilus-util-json-1.7.4.aar",
          "size": 11145,
          "sha512": "06cbbe83e4346a54f2fc1a379be6dce2d3392c39ac6b856f271fafd002636e35e26377dd3e7b75dc54e4f7638298cf5aae04ba4183e0afbfa10904cc04cadfa5",
          "sha256": "9c00809ff5b4d9bcd48fd11c67ee489063d88fca026e1d08b0ec9ebbb83f15da",
          "sha1": "55e006683b8edd82af71ba3edc2620cec2af3d00",
          "md5": "99744bb9ffb8811f6ce52338f5ea7784"
        }
      ]
    }
  ]
}
