{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-analytics",
    "version": "1.17.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.17.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-1.17.4.aar",
          "url": "nautilus-analytics-1.17.4.aar",
          "size": 165849,
          "sha512": "3a33cc7c055b91fe01e6bd4d747b74dd0a51416c3e36aebede3f915079406335d3dc1a95d2a4293145e115c5842084ce219e26ac183c25dbfee30d799af268f2",
          "sha256": "1347473eaf1c4bbccb1abdc4c0c46310d9687ca18dfd8984f7cf775e16c761f2",
          "sha1": "c801f8c729763c94aa746e16a8af1137dd7e41fb",
          "md5": "ebe115f3f07699e74941a2c8324e966e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.17.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-1.17.4.aar",
          "url": "nautilus-analytics-1.17.4.aar",
          "size": 165849,
          "sha512": "3a33cc7c055b91fe01e6bd4d747b74dd0a51416c3e36aebede3f915079406335d3dc1a95d2a4293145e115c5842084ce219e26ac183c25dbfee30d799af268f2",
          "sha256": "1347473eaf1c4bbccb1abdc4c0c46310d9687ca18dfd8984f7cf775e16c761f2",
          "sha1": "c801f8c729763c94aa746e16a8af1137dd7e41fb",
          "md5": "ebe115f3f07699e74941a2c8324e966e"
        }
      ]
    }
  ]
}
