{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-json",
    "version": "1.19.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-json-1.19.6.aar",
          "url": "nautilus-util-json-1.19.6.aar",
          "size": 11396,
          "sha512": "d3a7e8ebf50f474d0627741e87f1488871e3f217ee938c68bf783a4e69a572b536f882b21abbbebb5e9370270c29432a43e1ac4ed22f805569392284617fc003",
          "sha256": "050885e19fc6c5436b4748ae3a1eeeaab89aeb3c2ffe74657d29b4475fc4bbc9",
          "sha1": "f47d5e8ada47ba6d76c6ff69f35d7a3244ea6fe7",
          "md5": "9ea3a45f83b5233e11e17100b38eaa6e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-json-1.19.6.aar",
          "url": "nautilus-util-json-1.19.6.aar",
          "size": 11396,
          "sha512": "d3a7e8ebf50f474d0627741e87f1488871e3f217ee938c68bf783a4e69a572b536f882b21abbbebb5e9370270c29432a43e1ac4ed22f805569392284617fc003",
          "sha256": "050885e19fc6c5436b4748ae3a1eeeaab89aeb3c2ffe74657d29b4475fc4bbc9",
          "sha1": "f47d5e8ada47ba6d76c6ff69f35d7a3244ea6fe7",
          "md5": "9ea3a45f83b5233e11e17100b38eaa6e"
        }
      ]
    }
  ]
}
