{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-format",
    "version": "1.9.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.9.4.aar",
          "url": "nautilus-util-format-1.9.4.aar",
          "size": 8940,
          "sha512": "fcf451daaa8e9452749b866cca6b99149492dafcf08b4acde4704953caaa02172d921441b90e63ebcd5a1ed166e0a2b910172cd9931b8396febab0fb2e1e4566",
          "sha256": "8cd69f6bf7ed1c692c2e4379c432c625b891d9cf04c4a7a879c1468619eadbe1",
          "sha1": "983a01462b830194e2e04e797759a00604e092d7",
          "md5": "69685fab9b0654deb57ed001feeae604"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.9.4.aar",
          "url": "nautilus-util-format-1.9.4.aar",
          "size": 8940,
          "sha512": "fcf451daaa8e9452749b866cca6b99149492dafcf08b4acde4704953caaa02172d921441b90e63ebcd5a1ed166e0a2b910172cd9931b8396febab0fb2e1e4566",
          "sha256": "8cd69f6bf7ed1c692c2e4379c432c625b891d9cf04c4a7a879c1468619eadbe1",
          "sha1": "983a01462b830194e2e04e797759a00604e092d7",
          "md5": "69685fab9b0654deb57ed001feeae604"
        }
      ]
    }
  ]
}
