{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-core",
    "version": "1.7.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.7.17"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-cryptography",
          "version": {
            "requires": "1.7.17"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-core-1.7.17.aar",
          "url": "nautilus-core-1.7.17.aar",
          "size": 116073,
          "sha512": "8d8ec34037c7f5acce8d191e9263e136ee59c78aec5f349808ef220a5fb53ce23ea4e4e81c98d94d31f053f897d3dcc3c8aa2f7d032fb4c195e31e1e66a39365",
          "sha256": "e0a63a9075e5b4c5075903e52d83224c10e12e90e19a134ade6cc349f6f32808",
          "sha1": "4147c260cac55db99af6db324f98141636b0e225",
          "md5": "0b8820888edc3e37de854a30359d5c0b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.7.17"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-cryptography",
          "version": {
            "requires": "1.7.17"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-core-1.7.17.aar",
          "url": "nautilus-core-1.7.17.aar",
          "size": 116073,
          "sha512": "8d8ec34037c7f5acce8d191e9263e136ee59c78aec5f349808ef220a5fb53ce23ea4e4e81c98d94d31f053f897d3dcc3c8aa2f7d032fb4c195e31e1e66a39365",
          "sha256": "e0a63a9075e5b4c5075903e52d83224c10e12e90e19a134ade6cc349f6f32808",
          "sha1": "4147c260cac55db99af6db324f98141636b0e225",
          "md5": "0b8820888edc3e37de854a30359d5c0b"
        }
      ]
    }
  ]
}
