{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-tools-cryptography",
    "version": "1.10.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-cryptography-1.10.2.aar",
          "url": "nautilus-tools-cryptography-1.10.2.aar",
          "size": 26306,
          "sha512": "64869a040965e680b9a20bc56f859b057b5876c255d577e9e344d8a63f2a13047ddc0ec2f9e0393e7756f597781fd49b3eef530b3d673e70efa14ed9966f6e86",
          "sha256": "ebff3fc3adc4c4eef826891500acc3a9a36dda2dac4bb11ce774f227f3753ae5",
          "sha1": "0547dd41554ef7fd9d5e00fd738dfba0a7b0afb3",
          "md5": "dad013eaca4173b9c846cc1d92123e77"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-cryptography-1.10.2.aar",
          "url": "nautilus-tools-cryptography-1.10.2.aar",
          "size": 26306,
          "sha512": "64869a040965e680b9a20bc56f859b057b5876c255d577e9e344d8a63f2a13047ddc0ec2f9e0393e7756f597781fd49b3eef530b3d673e70efa14ed9966f6e86",
          "sha256": "ebff3fc3adc4c4eef826891500acc3a9a36dda2dac4bb11ce774f227f3753ae5",
          "sha1": "0547dd41554ef7fd9d5e00fd738dfba0a7b0afb3",
          "md5": "dad013eaca4173b9c846cc1d92123e77"
        }
      ]
    }
  ]
}
