{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-tools-logging",
    "version": "1.19.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-logging-1.19.4.aar",
          "url": "nautilus-tools-logging-1.19.4.aar",
          "size": 19669,
          "sha512": "20e0b6f73a390b965e1e46f85bc02a6d2f044f0f25ece2ba6194a97dc39ef70b045f676f93902d7d5127855491a1e66766e54c210d0f544dd37cfeb0f5090a1b",
          "sha256": "89d7d259564d7b4c50ef6ed5fdeeb187b1ca9f556f2a26abcdb9505d0e355c4b",
          "sha1": "4a9bf7afae112d06fe287659206eb1a29f68ea8c",
          "md5": "432da77bdd23b11110f87285f3affa5e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-logging-1.19.4.aar",
          "url": "nautilus-tools-logging-1.19.4.aar",
          "size": 19669,
          "sha512": "20e0b6f73a390b965e1e46f85bc02a6d2f044f0f25ece2ba6194a97dc39ef70b045f676f93902d7d5127855491a1e66766e54c210d0f544dd37cfeb0f5090a1b",
          "sha256": "89d7d259564d7b4c50ef6ed5fdeeb187b1ca9f556f2a26abcdb9505d0e355c4b",
          "sha1": "4a9bf7afae112d06fe287659206eb1a29f68ea8c",
          "md5": "432da77bdd23b11110f87285f3affa5e"
        }
      ]
    }
  ]
}
