{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-check-in",
    "version": "1.15.7-hotfix1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.15.7-hotfix1"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-format",
          "version": {
            "requires": "1.15.7-hotfix1"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-analytics",
          "version": {
            "requires": "1.15.7-hotfix1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-check-in-1.15.7-hotfix1.aar",
          "url": "nautilus-check-in-1.15.7-hotfix1.aar",
          "size": 46456,
          "sha512": "09bcb73d33ecdf3b6604ef08eb7dd05c004fae129324cbe1ed4c7552e096b59faca25072791dfc2bc4755e1ebdfa9d2ffa4eeeee11fde948ae1ce510b9b5b7d0",
          "sha256": "5f8679690a1f5ec35df75d99fa9b95db52a29cd671b5e01ac9a60b192d9eb1c6",
          "sha1": "d91d049ec26b96be02363ace2e06703f5bcb106e",
          "md5": "3487bc7e2c1a8ad21ec81d381551f9cd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.15.7-hotfix1"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-format",
          "version": {
            "requires": "1.15.7-hotfix1"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-analytics",
          "version": {
            "requires": "1.15.7-hotfix1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-check-in-1.15.7-hotfix1.aar",
          "url": "nautilus-check-in-1.15.7-hotfix1.aar",
          "size": 46456,
          "sha512": "09bcb73d33ecdf3b6604ef08eb7dd05c004fae129324cbe1ed4c7552e096b59faca25072791dfc2bc4755e1ebdfa9d2ffa4eeeee11fde948ae1ce510b9b5b7d0",
          "sha256": "5f8679690a1f5ec35df75d99fa9b95db52a29cd671b5e01ac9a60b192d9eb1c6",
          "sha1": "d91d049ec26b96be02363ace2e06703f5bcb106e",
          "md5": "3487bc7e2c1a8ad21ec81d381551f9cd"
        }
      ]
    }
  ]
}
