{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-network",
    "version": "1.12.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.12.11"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.12.11.aar",
          "url": "nautilus-util-network-1.12.11.aar",
          "size": 23242,
          "sha512": "9ddd7c2f4d4fc03ffa05db8fbdc1df946dab6ee6a4195bc5ee621719cbd5bd0d2bd5e7c2962a7e3b42f12f008e3f127e28509f4a1c6854356d08a33a7498d4cb",
          "sha256": "5ff3fecac617bccb573c3e5db6d51112d08e2182a42032e5411c30b59db56965",
          "sha1": "4399bd4d6a6b983dc17e25a56358c9ab6e0c153c",
          "md5": "112b70e59ecd9bcf2322ac3169147d8c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.12.11"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.12.11.aar",
          "url": "nautilus-util-network-1.12.11.aar",
          "size": 23242,
          "sha512": "9ddd7c2f4d4fc03ffa05db8fbdc1df946dab6ee6a4195bc5ee621719cbd5bd0d2bd5e7c2962a7e3b42f12f008e3f127e28509f4a1c6854356d08a33a7498d4cb",
          "sha256": "5ff3fecac617bccb573c3e5db6d51112d08e2182a42032e5411c30b59db56965",
          "sha1": "4399bd4d6a6b983dc17e25a56358c9ab6e0c153c",
          "md5": "112b70e59ecd9bcf2322ac3169147d8c"
        }
      ]
    }
  ]
}
