{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-format",
    "version": "1.7.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.7.5.aar",
          "url": "nautilus-util-format-1.7.5.aar",
          "size": 8802,
          "sha512": "0c6abb85f7aa1a71b391e8242e7b2f7ffcb63f1fa0c2edecfa878ce047c4c6d439d2a679300ede082c46a9be75fa75590f400ef9891163d8db3b6604093de416",
          "sha256": "3f164d21568a4dee7e1860f0d6c5b86e7ba4ba0f7636743ee5df649415b8da3d",
          "sha1": "55012ba9581b4d695789b6c5647721e8ec4cf69b",
          "md5": "b317826cadbe0f5a91be08c9e0515372"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.7.5.aar",
          "url": "nautilus-util-format-1.7.5.aar",
          "size": 8802,
          "sha512": "0c6abb85f7aa1a71b391e8242e7b2f7ffcb63f1fa0c2edecfa878ce047c4c6d439d2a679300ede082c46a9be75fa75590f400ef9891163d8db3b6604093de416",
          "sha256": "3f164d21568a4dee7e1860f0d6c5b86e7ba4ba0f7636743ee5df649415b8da3d",
          "sha1": "55012ba9581b4d695789b6c5647721e8ec4cf69b",
          "md5": "b317826cadbe0f5a91be08c9e0515372"
        }
      ]
    }
  ]
}
