{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-format",
    "version": "1.7.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.7.5.aar",
          "url": "nautilus-util-format-1.7.5.aar",
          "size": 8803,
          "sha512": "9102c594f97fdd6aa35d737af2b249237170ad50c0bde81c2e22deaa732b5ffd7d10e3efcb62ddbd5612c3fe518479c61e743b4fcdf527e2bcd27a89e5024d5c",
          "sha256": "51b1d71babcb0752f617a6a0479f2a1d95a33688fb218b69f41e1c73d2bfe3c0",
          "sha1": "47cb737e9324e02593a1a8df439f189dfe9f760b",
          "md5": "3d8ef6be2f7e224f8756861a97e9f001"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.7.5.aar",
          "url": "nautilus-util-format-1.7.5.aar",
          "size": 8803,
          "sha512": "9102c594f97fdd6aa35d737af2b249237170ad50c0bde81c2e22deaa732b5ffd7d10e3efcb62ddbd5612c3fe518479c61e743b4fcdf527e2bcd27a89e5024d5c",
          "sha256": "51b1d71babcb0752f617a6a0479f2a1d95a33688fb218b69f41e1c73d2bfe3c0",
          "sha1": "47cb737e9324e02593a1a8df439f189dfe9f760b",
          "md5": "3d8ef6be2f7e224f8756861a97e9f001"
        }
      ]
    }
  ]
}
