{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-code-image-providers",
    "version": "1.7.27-hotfix1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.7.27-hotfix1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-code-image-providers-1.7.27-hotfix1.aar",
          "url": "nautilus-code-image-providers-1.7.27-hotfix1.aar",
          "size": 12554,
          "sha512": "972313f78bd6dd18af06fd2753f8298ff5548a19940801a5b306538b7ef9e93b9032c26bd79890e00d9be1c20aebeb73c6d081e22f685048f58ee3e2b46d327b",
          "sha256": "6892676a07115f4b3c6ace5a01c68bf0af960452b21c5f859eff6fb5c52821fc",
          "sha1": "66baac55ea4602fb87d8b9f211f056228d69843d",
          "md5": "aeabec2ce264b05d2b2f680994bf2d67"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.7.27-hotfix1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-code-image-providers-1.7.27-hotfix1.aar",
          "url": "nautilus-code-image-providers-1.7.27-hotfix1.aar",
          "size": 12554,
          "sha512": "972313f78bd6dd18af06fd2753f8298ff5548a19940801a5b306538b7ef9e93b9032c26bd79890e00d9be1c20aebeb73c6d081e22f685048f58ee3e2b46d327b",
          "sha256": "6892676a07115f4b3c6ace5a01c68bf0af960452b21c5f859eff6fb5c52821fc",
          "sha1": "66baac55ea4602fb87d8b9f211f056228d69843d",
          "md5": "aeabec2ce264b05d2b2f680994bf2d67"
        }
      ]
    }
  ]
}
