{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-format",
    "version": "1.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.7.1.aar",
          "url": "nautilus-util-format-1.7.1.aar",
          "size": 8803,
          "sha512": "dc757849ceecdebc09132f3f140e15117432bc32431821cb0518b865dde2bd91d96cdc6b575986a0291b5579298e93b9b6b63acc45b4d058b38281ee881945b4",
          "sha256": "85f7b69cf8b1141474d2998ee8e43b980f393644c1f924b0d8fa638d60c91718",
          "sha1": "43b879307dcdd22d02ff7f2ab53bc12c032d5a44",
          "md5": "b61a0ae0f8fa39a41351b23764f50145"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.7.1.aar",
          "url": "nautilus-util-format-1.7.1.aar",
          "size": 8803,
          "sha512": "dc757849ceecdebc09132f3f140e15117432bc32431821cb0518b865dde2bd91d96cdc6b575986a0291b5579298e93b9b6b63acc45b4d058b38281ee881945b4",
          "sha256": "85f7b69cf8b1141474d2998ee8e43b980f393644c1f924b0d8fa638d60c91718",
          "sha1": "43b879307dcdd22d02ff7f2ab53bc12c032d5a44",
          "md5": "b61a0ae0f8fa39a41351b23764f50145"
        }
      ]
    }
  ]
}
