{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-analytics",
    "version": "1.10.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-1.10.3.aar",
          "url": "nautilus-analytics-1.10.3.aar",
          "size": 173973,
          "sha512": "cfd8b9bd9e52a6c7662834147e1cbc860b2941b50ee1ab810bce4a11dd252ce8aa385d4c5cc4f50f5b03f816d60c36357c1f45a826db20ccf4ede1b9cfe10118",
          "sha256": "d6bd83073857f0e92c659236bfde22afd24e9d71d851f8245e46918c2f2eb990",
          "sha1": "873565a17088f760506322b36ca0bfdc054d2c60",
          "md5": "00aabf9bf8b7379d8f40cb57aacc9d09"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-1.10.3.aar",
          "url": "nautilus-analytics-1.10.3.aar",
          "size": 173973,
          "sha512": "cfd8b9bd9e52a6c7662834147e1cbc860b2941b50ee1ab810bce4a11dd252ce8aa385d4c5cc4f50f5b03f816d60c36357c1f45a826db20ccf4ede1b9cfe10118",
          "sha256": "d6bd83073857f0e92c659236bfde22afd24e9d71d851f8245e46918c2f2eb990",
          "sha1": "873565a17088f760506322b36ca0bfdc054d2c60",
          "md5": "00aabf9bf8b7379d8f40cb57aacc9d09"
        }
      ]
    }
  ]
}
