{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-analytics",
    "version": "1.12.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.12.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-1.12.2.aar",
          "url": "nautilus-analytics-1.12.2.aar",
          "size": 173972,
          "sha512": "7d13e9934d1906904b751e23fbda4846422a957b7b01447cd5534fc8dc62db7729a3a81d602a78173c665ffe230d3c32e5e18528448ca2b1b608da16944ead48",
          "sha256": "63b754e2752eac0ad95386aa02a19029ed0ccc9215280f309c0abb2f37c74602",
          "sha1": "a0baac21ed866b60772d80b2a455b7ed6c0900e9",
          "md5": "bf5ce7b1813c6fe85b538a6bd9103a5b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.12.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-1.12.2.aar",
          "url": "nautilus-analytics-1.12.2.aar",
          "size": 173972,
          "sha512": "7d13e9934d1906904b751e23fbda4846422a957b7b01447cd5534fc8dc62db7729a3a81d602a78173c665ffe230d3c32e5e18528448ca2b1b608da16944ead48",
          "sha256": "63b754e2752eac0ad95386aa02a19029ed0ccc9215280f309c0abb2f37c74602",
          "sha1": "a0baac21ed866b60772d80b2a455b7ed6c0900e9",
          "md5": "bf5ce7b1813c6fe85b538a6bd9103a5b"
        }
      ]
    }
  ]
}
