{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-network",
    "version": "1.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.13.0.aar",
          "url": "nautilus-util-network-1.13.0.aar",
          "size": 23244,
          "sha512": "327a9961f6e9bfcf550cc83d90c7b4a850fb476c238c576e4220dfebbbf1397536d22955721a77f3f0388611de1fd0dd0443420b90116b803695ed4d706e08fc",
          "sha256": "16ffffa125d6275bc3ab63a89fdcd1a67c2a92cd2a308e8ec1986c8f6c300697",
          "sha1": "9fa0110d9c2e2497c87a21a6a212f90e3fc4a719",
          "md5": "cc03a09326ad281d6250b819784fa676"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.13.0.aar",
          "url": "nautilus-util-network-1.13.0.aar",
          "size": 23244,
          "sha512": "327a9961f6e9bfcf550cc83d90c7b4a850fb476c238c576e4220dfebbbf1397536d22955721a77f3f0388611de1fd0dd0443420b90116b803695ed4d706e08fc",
          "sha256": "16ffffa125d6275bc3ab63a89fdcd1a67c2a92cd2a308e8ec1986c8f6c300697",
          "sha1": "9fa0110d9c2e2497c87a21a6a212f90e3fc4a719",
          "md5": "cc03a09326ad281d6250b819784fa676"
        }
      ]
    }
  ]
}
