{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-tools-logging",
    "version": "1.7.9-hotfix1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-logging-1.7.9-hotfix1.aar",
          "url": "nautilus-tools-logging-1.7.9-hotfix1.aar",
          "size": 16671,
          "sha512": "4e3c4d372e6790c12a6b9842db91f0142a2256616b5bb56272468118ad658410b22731686829ce593e392388945b753f11b668d6f66a573e5c410b36f6b9308e",
          "sha256": "a03c2b6dcf799d7c7ff5d03aa111c8e13ee4c7774839f626730fd12988632277",
          "sha1": "8d1a87749501fa01fbb6ec8960b7ad3de83e5090",
          "md5": "45a6c5f8ee47ab5fd7d8d9d5f9e95858"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-logging-1.7.9-hotfix1.aar",
          "url": "nautilus-tools-logging-1.7.9-hotfix1.aar",
          "size": 16671,
          "sha512": "4e3c4d372e6790c12a6b9842db91f0142a2256616b5bb56272468118ad658410b22731686829ce593e392388945b753f11b668d6f66a573e5c410b36f6b9308e",
          "sha256": "a03c2b6dcf799d7c7ff5d03aa111c8e13ee4c7774839f626730fd12988632277",
          "sha1": "8d1a87749501fa01fbb6ec8960b7ad3de83e5090",
          "md5": "45a6c5f8ee47ab5fd7d8d9d5f9e95858"
        }
      ]
    }
  ]
}
