{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-core",
    "version": "1.25.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.25.13"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-cryptography",
          "version": {
            "requires": "1.25.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-core-1.25.13.aar",
          "url": "nautilus-core-1.25.13.aar",
          "size": 85229,
          "sha512": "eff8ba2e693942c82d0c07310061ddeda781eb7706ddc2a7f18bd4d56ee458ed9c3991880d2b6ad1676b507e9e789c5ea1b83d95c38e700a0df593b7f09d7374",
          "sha256": "c8fa0ba4b2dfd2a002cdf5c2c03270da42cfe7000e74332da78ceb1c54ed4e5d",
          "sha1": "9bbae8088bc2cfd862ce2cd16fa70e0d9b8d39c5",
          "md5": "83b05d9bdaff2d4c8d71cb5ee5ad0a1a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.18.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.25.13"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-cryptography",
          "version": {
            "requires": "1.25.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-core-1.25.13.aar",
          "url": "nautilus-core-1.25.13.aar",
          "size": 85229,
          "sha512": "eff8ba2e693942c82d0c07310061ddeda781eb7706ddc2a7f18bd4d56ee458ed9c3991880d2b6ad1676b507e9e789c5ea1b83d95c38e700a0df593b7f09d7374",
          "sha256": "c8fa0ba4b2dfd2a002cdf5c2c03270da42cfe7000e74332da78ceb1c54ed4e5d",
          "sha1": "9bbae8088bc2cfd862ce2cd16fa70e0d9b8d39c5",
          "md5": "83b05d9bdaff2d4c8d71cb5ee5ad0a1a"
        }
      ]
    }
  ]
}
