{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-core",
    "version": "1.7.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.7.5"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-cryptography",
          "version": {
            "requires": "1.7.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-core-1.7.5.aar",
          "url": "nautilus-core-1.7.5.aar",
          "size": 90250,
          "sha512": "1d9a3765b01ebd19204f4a3784b5043e0f4fdab0c976603ebf1cb36cdf7b423985b5f860e41dbbe6a796042a27eb293727aee9816985dbdf069ab701d158b9f7",
          "sha256": "c18f1a7e2fa21874acb5d7e5a209335d48958a683dee6be0fe9b4e91b1bd1eb9",
          "sha1": "5cafd14a1485e34d8912dfacf1710abe56dfadad",
          "md5": "d257a50cd874304e52b640e5bb86fb95"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.7.5"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-cryptography",
          "version": {
            "requires": "1.7.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-core-1.7.5.aar",
          "url": "nautilus-core-1.7.5.aar",
          "size": 90250,
          "sha512": "1d9a3765b01ebd19204f4a3784b5043e0f4fdab0c976603ebf1cb36cdf7b423985b5f860e41dbbe6a796042a27eb293727aee9816985dbdf069ab701d158b9f7",
          "sha256": "c18f1a7e2fa21874acb5d7e5a209335d48958a683dee6be0fe9b4e91b1bd1eb9",
          "sha1": "5cafd14a1485e34d8912dfacf1710abe56dfadad",
          "md5": "d257a50cd874304e52b640e5bb86fb95"
        }
      ]
    }
  ]
}
