{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-analytics",
    "version": "1.5.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.5.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-1.5.8.aar",
          "url": "nautilus-analytics-1.5.8.aar",
          "size": 145140,
          "sha512": "2951ce2461eafc855a5f8329bab764ac30ed7862f7021380bf6e73ca8c2d1539c7e595aa70b29225deabf340a0153d1d3acee79729f01928609a5319bd035739",
          "sha256": "aaa9c5bd931fd40bfecbc7fafbeed534df76ebe49317b900fc839e8e7d07a3d3",
          "sha1": "2da951dc311eb228b84e78a2d534f114bb4d2130",
          "md5": "90a9d72b4d3203f5b3e64f19c962c001"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.5.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-1.5.8.aar",
          "url": "nautilus-analytics-1.5.8.aar",
          "size": 145140,
          "sha512": "2951ce2461eafc855a5f8329bab764ac30ed7862f7021380bf6e73ca8c2d1539c7e595aa70b29225deabf340a0153d1d3acee79729f01928609a5319bd035739",
          "sha256": "aaa9c5bd931fd40bfecbc7fafbeed534df76ebe49317b900fc839e8e7d07a3d3",
          "sha1": "2da951dc311eb228b84e78a2d534f114bb4d2130",
          "md5": "90a9d72b4d3203f5b3e64f19c962c001"
        }
      ]
    }
  ]
}
