{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-user-info",
    "version": "1.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-imaging",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-geo",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-datetime",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-config",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-view",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-livedata",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-user-info-1.6.1.aar",
          "url": "nautilus-user-info-1.6.1.aar",
          "size": 141000,
          "sha512": "16916f08f394df8bc79b0cf4a70d7daa39ddda20c856f19594e8dd419f68b681839fed46b18b91ed6abc3f82f6c7f0e9856cb77ecc0d44f26f582b3e4b8912a9",
          "sha256": "46fd7a75715154fcae2dd5bfeb56800b2e9ee351211af194a789fe8d77bf8d84",
          "sha1": "f3316c56a1f48b047b4b22fb4953c94f45d9eaa9",
          "md5": "f295ac2a6f65fb239e83f2abdd7b99cd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-imaging",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-geo",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-datetime",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-config",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-view",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-livedata",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.3"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.4.3"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-user-info-1.6.1.aar",
          "url": "nautilus-user-info-1.6.1.aar",
          "size": 141000,
          "sha512": "16916f08f394df8bc79b0cf4a70d7daa39ddda20c856f19594e8dd419f68b681839fed46b18b91ed6abc3f82f6c7f0e9856cb77ecc0d44f26f582b3e4b8912a9",
          "sha256": "46fd7a75715154fcae2dd5bfeb56800b2e9ee351211af194a789fe8d77bf8d84",
          "sha1": "f3316c56a1f48b047b4b22fb4953c94f45d9eaa9",
          "md5": "f295ac2a6f65fb239e83f2abdd7b99cd"
        }
      ]
    }
  ]
}
