{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-maintenance",
    "version": "1.13.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-network",
          "version": {
            "requires": "1.13.3"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.13.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-maintenance-1.13.3.aar",
          "url": "nautilus-maintenance-1.13.3.aar",
          "size": 41035,
          "sha512": "1b5e88ee6f0344c92595c1efcfceed0d7973b8578c734d737fe5726a098cce413cbb637b78e6ad4d437d5bec5266292b28a078b9732fa9480ac023f240622704",
          "sha256": "318357e718b57d2a6c7faf9db97898fda274f8b632864817de6cb947e4d8bc50",
          "sha1": "c1ac7f681d4059a0e2016beb5ba9825577202bd9",
          "md5": "8aa23ebb3143ac561affb4e86ceadd44"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-network",
          "version": {
            "requires": "1.13.3"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.13.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-maintenance-1.13.3.aar",
          "url": "nautilus-maintenance-1.13.3.aar",
          "size": 41035,
          "sha512": "1b5e88ee6f0344c92595c1efcfceed0d7973b8578c734d737fe5726a098cce413cbb637b78e6ad4d437d5bec5266292b28a078b9732fa9480ac023f240622704",
          "sha256": "318357e718b57d2a6c7faf9db97898fda274f8b632864817de6cb947e4d8bc50",
          "sha1": "c1ac7f681d4059a0e2016beb5ba9825577202bd9",
          "md5": "8aa23ebb3143ac561affb4e86ceadd44"
        }
      ]
    }
  ]
}
