{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-network",
    "version": "1.14.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.14.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.14.6.aar",
          "url": "nautilus-util-network-1.14.6.aar",
          "size": 23247,
          "sha512": "6967f04888e1e85034b3ab63a522c82b48e5e5971272389505e08b232cedcd5b3f6393776acf9a0943521a145d4ca65f5c672f81e398f86805661c6feeb14ef5",
          "sha256": "7a15167a920c6ff1b02da7a771bdec8f35fd4f08bb5e925a56f15985065b4519",
          "sha1": "359201a3381defed5f6dd6cb932a8335ddc09c95",
          "md5": "52c20fef4ecda3d1aa56cc358ea8a1a6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.14.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.14.6.aar",
          "url": "nautilus-util-network-1.14.6.aar",
          "size": 23247,
          "sha512": "6967f04888e1e85034b3ab63a522c82b48e5e5971272389505e08b232cedcd5b3f6393776acf9a0943521a145d4ca65f5c672f81e398f86805661c6feeb14ef5",
          "sha256": "7a15167a920c6ff1b02da7a771bdec8f35fd4f08bb5e925a56f15985065b4519",
          "sha1": "359201a3381defed5f6dd6cb932a8335ddc09c95",
          "md5": "52c20fef4ecda3d1aa56cc358ea8a1a6"
        }
      ]
    }
  ]
}
