{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-config",
    "version": "1.15.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.15.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-config-1.15.6.aar",
          "url": "nautilus-config-1.15.6.aar",
          "size": 151021,
          "sha512": "81853380a49e5526e547f314997927ff00c4e687cf300f38d9360aac331eb2d303e93e6cf77b6458336d55285f660728929ad828aaab780d16f5f7a8b67a31be",
          "sha256": "19e7b8f81c5f8a0a1ba6f63f581775e44f0e6e065d9acc94a487cd4d662b7c1f",
          "sha1": "9ece0471bbd11be435ed8d6f10a5383011ffbac4",
          "md5": "5c2e2716dde65e1ccdfade50dea5baa6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.15.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-config-1.15.6.aar",
          "url": "nautilus-config-1.15.6.aar",
          "size": 151021,
          "sha512": "81853380a49e5526e547f314997927ff00c4e687cf300f38d9360aac331eb2d303e93e6cf77b6458336d55285f660728929ad828aaab780d16f5f7a8b67a31be",
          "sha256": "19e7b8f81c5f8a0a1ba6f63f581775e44f0e6e065d9acc94a487cd4d662b7c1f",
          "sha1": "9ece0471bbd11be435ed8d6f10a5383011ffbac4",
          "md5": "5c2e2716dde65e1ccdfade50dea5baa6"
        }
      ]
    }
  ]
}
