{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-core",
    "version": "1.12.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.12.13"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-cryptography",
          "version": {
            "requires": "1.12.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-core-1.12.13.aar",
          "url": "nautilus-core-1.12.13.aar",
          "size": 108597,
          "sha512": "eb08fadf6ee881088a308e6f0ea1974c3945995687de98322290688fde0ba184f52998de9aed8160a456ef3ffd42fcfc9532b82ac84df9e709e9cbcdb8d87fb6",
          "sha256": "8e733ee6ca64b4f176dcad35be71f3eb9d50e77e9d0f8e464f2b211b409bc3cb",
          "sha1": "01ae103ef50f44717ad55bbe794c7e488db1d8d8",
          "md5": "ae08156dd90097dce44031d552e97bb6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.12.13"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-cryptography",
          "version": {
            "requires": "1.12.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-core-1.12.13.aar",
          "url": "nautilus-core-1.12.13.aar",
          "size": 108597,
          "sha512": "eb08fadf6ee881088a308e6f0ea1974c3945995687de98322290688fde0ba184f52998de9aed8160a456ef3ffd42fcfc9532b82ac84df9e709e9cbcdb8d87fb6",
          "sha256": "8e733ee6ca64b4f176dcad35be71f3eb9d50e77e9d0f8e464f2b211b409bc3cb",
          "sha1": "01ae103ef50f44717ad55bbe794c7e488db1d8d8",
          "md5": "ae08156dd90097dce44031d552e97bb6"
        }
      ]
    }
  ]
}
