{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-wovn",
    "version": "1.23.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-wovn-1.23.5.jar",
          "url": "nautilus-util-wovn-1.23.5.jar",
          "size": 4985,
          "sha512": "9e6fa773bc2ba782444cf3efbcb0e5811b26d03eefaf24043d6bf2d13f435358e26d83b192f00bf320cd92cd457123c01be027cca62d20c6add6999cd1f65be2",
          "sha256": "b5bd42a9c2dd93ba767dc7b8e4cc4d13d7cfc0757e2f22485878209d9f8849b8",
          "sha1": "dc6d23defd4149fc24ef4a520dfd07e86cd85a9f",
          "md5": "ef37584573e583558bd1d2ee04478620"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-wovn-1.23.5.jar",
          "url": "nautilus-util-wovn-1.23.5.jar",
          "size": 4985,
          "sha512": "9e6fa773bc2ba782444cf3efbcb0e5811b26d03eefaf24043d6bf2d13f435358e26d83b192f00bf320cd92cd457123c01be027cca62d20c6add6999cd1f65be2",
          "sha256": "b5bd42a9c2dd93ba767dc7b8e4cc4d13d7cfc0757e2f22485878209d9f8849b8",
          "sha1": "dc6d23defd4149fc24ef4a520dfd07e86cd85a9f",
          "md5": "ef37584573e583558bd1d2ee04478620"
        }
      ]
    }
  ]
}
