{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-code-reader",
    "version": "1.25.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.25.1"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-view",
          "version": {
            "requires": "1.25.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "9.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-code-reader-1.25.1.aar",
          "url": "nautilus-code-reader-1.25.1.aar",
          "size": 25869,
          "sha512": "cc8d412af294ff3460ea459faa5ba7aeb9adc74e1b638bb202cc8042f1751cc52ea6883f68b73f66bc7fea346601b8bcb513291dd5d18fd8ec3b87fa146ca36e",
          "sha256": "df5a0fddd5be4461d8ee8e27e96bcb4faf5ecc9e0242fcc97e05f1da6853d002",
          "sha1": "f4e1f70ab3a4e2653933cff9c6ee03b1d4a3ba8f",
          "md5": "cb77f40dbe83a7c2d9c3b9a0277f3925"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.9"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "17.3.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.25.1"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-view",
          "version": {
            "requires": "1.25.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "9.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-code-reader-1.25.1.aar",
          "url": "nautilus-code-reader-1.25.1.aar",
          "size": 25869,
          "sha512": "cc8d412af294ff3460ea459faa5ba7aeb9adc74e1b638bb202cc8042f1751cc52ea6883f68b73f66bc7fea346601b8bcb513291dd5d18fd8ec3b87fa146ca36e",
          "sha256": "df5a0fddd5be4461d8ee8e27e96bcb4faf5ecc9e0242fcc97e05f1da6853d002",
          "sha1": "f4e1f70ab3a4e2653933cff9c6ee03b1d4a3ba8f",
          "md5": "cb77f40dbe83a7c2d9c3b9a0277f3925"
        }
      ]
    }
  ]
}
