{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-json",
    "version": "1.7.28",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-json-1.7.28.aar",
          "url": "nautilus-util-json-1.7.28.aar",
          "size": 11142,
          "sha512": "e12179f835cd8e7762b06c9c6da2f7f29814031d4c79218f80e95b8e483c001d4d6fca2af45f230134f60477d5935fc2d2c9dad17c9049e28ba13311604e6ee4",
          "sha256": "ed5449dc72ad504d014b1bfe7bfaf7dd5230899ff8ddd3652d864b23883cf5bb",
          "sha1": "c000ae31409018cf15230d4059ba5162be6866c8",
          "md5": "5b9950b17a6659811e278ada08525c49"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-json-1.7.28.aar",
          "url": "nautilus-util-json-1.7.28.aar",
          "size": 11142,
          "sha512": "e12179f835cd8e7762b06c9c6da2f7f29814031d4c79218f80e95b8e483c001d4d6fca2af45f230134f60477d5935fc2d2c9dad17c9049e28ba13311604e6ee4",
          "sha256": "ed5449dc72ad504d014b1bfe7bfaf7dd5230899ff8ddd3652d864b23883cf5bb",
          "sha1": "c000ae31409018cf15230d4059ba5162be6866c8",
          "md5": "5b9950b17a6659811e278ada08525c49"
        }
      ]
    }
  ]
}
