{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-network",
    "version": "1.15.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.15.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.15.6.aar",
          "url": "nautilus-util-network-1.15.6.aar",
          "size": 23273,
          "sha512": "f51a3df08b6776dd68254948e73ac5b7bec6026a807f564825338d3745031b2dd2a45e4569c72f11bec50244fa647415d436d39b7628a30472ce2a08bbac71bd",
          "sha256": "95ef9bceb58dd91d10581fdbe3718ad25fdca0f2ddc9e0b0882a0e69f6fe35cf",
          "sha1": "531014561a986b04a4b1d7c35dee1202fcb3171f",
          "md5": "72f0b22872040ebe34fc8101d7cfc639"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.15.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.15.6.aar",
          "url": "nautilus-util-network-1.15.6.aar",
          "size": 23273,
          "sha512": "f51a3df08b6776dd68254948e73ac5b7bec6026a807f564825338d3745031b2dd2a45e4569c72f11bec50244fa647415d436d39b7628a30472ce2a08bbac71bd",
          "sha256": "95ef9bceb58dd91d10581fdbe3718ad25fdca0f2ddc9e0b0882a0e69f6fe35cf",
          "sha1": "531014561a986b04a4b1d7c35dee1202fcb3171f",
          "md5": "72f0b22872040ebe34fc8101d7cfc639"
        }
      ]
    }
  ]
}
