{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-format",
    "version": "1.7.0-hotfix",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.7.0-hotfix.aar",
          "url": "nautilus-util-format-1.7.0-hotfix.aar",
          "size": 8812,
          "sha512": "6762222922ed83f7b71cfeb62ffb4c8e10f15cad5b6a610f8cd3ee25159f0c84cbc203178cb51634da9a5a6765e6a1794070c7f2896080b6971bce6e0f02c2a8",
          "sha256": "8ccaf7bffd1956cac628d8f07203393a3c84830b8e980c836c3250fb840b9afb",
          "sha1": "93ad1738fa99d61a5275f14177c55d29691ddfd9",
          "md5": "679974a3efc7a109d1b4e8d450907618"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.7.0-hotfix.aar",
          "url": "nautilus-util-format-1.7.0-hotfix.aar",
          "size": 8812,
          "sha512": "6762222922ed83f7b71cfeb62ffb4c8e10f15cad5b6a610f8cd3ee25159f0c84cbc203178cb51634da9a5a6765e6a1794070c7f2896080b6971bce6e0f02c2a8",
          "sha256": "8ccaf7bffd1956cac628d8f07203393a3c84830b8e980c836c3250fb840b9afb",
          "sha1": "93ad1738fa99d61a5275f14177c55d29691ddfd9",
          "md5": "679974a3efc7a109d1b4e8d450907618"
        }
      ]
    }
  ]
}
