{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-core",
    "version": "1.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-cryptography",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-core-1.7.1.aar",
          "url": "nautilus-core-1.7.1.aar",
          "size": 90254,
          "sha512": "ab7727d10afe1aab1d2124e4f32df473244a786807407a159a6c96d47653ac616ffd493cc73530571fb59c282b2fe968817096ad44f83dadf9ab6c56c29069b3",
          "sha256": "11259ae264b80d6f9c05f87e3be0b9299cad998c241f6a28fb6916a9ad21e68f",
          "sha1": "f17910ed5e87c4dac6680def82832fbcfbd31faf",
          "md5": "dcc25b4c0a28a60c110efbe594ac3918"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-cryptography",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-core-1.7.1.aar",
          "url": "nautilus-core-1.7.1.aar",
          "size": 90254,
          "sha512": "ab7727d10afe1aab1d2124e4f32df473244a786807407a159a6c96d47653ac616ffd493cc73530571fb59c282b2fe968817096ad44f83dadf9ab6c56c29069b3",
          "sha256": "11259ae264b80d6f9c05f87e3be0b9299cad998c241f6a28fb6916a9ad21e68f",
          "sha1": "f17910ed5e87c4dac6680def82832fbcfbd31faf",
          "md5": "dcc25b4c0a28a60c110efbe594ac3918"
        }
      ]
    }
  ]
}
