{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-code-image-providers",
    "version": "1.8.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.8.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-code-image-providers-1.8.4.aar",
          "url": "nautilus-code-image-providers-1.8.4.aar",
          "size": 12775,
          "sha512": "d5ae42f12b4b8766fb089ba0178a5217b81fede3c978cea74ba8c454a15253b92d008554a06f31232a5833571212320cf764c1590adb273e3e3ce11e234b69b8",
          "sha256": "ba8e5856ea96625baeed67b96c369151d1b6031932633d9332c785033eabc04e",
          "sha1": "d79274e2e123377409c48ce6831cebb18b07f92f",
          "md5": "eea77b980b16a4f13020217b22869598"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.8.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-code-image-providers-1.8.4.aar",
          "url": "nautilus-code-image-providers-1.8.4.aar",
          "size": 12775,
          "sha512": "d5ae42f12b4b8766fb089ba0178a5217b81fede3c978cea74ba8c454a15253b92d008554a06f31232a5833571212320cf764c1590adb273e3e3ce11e234b69b8",
          "sha256": "ba8e5856ea96625baeed67b96c369151d1b6031932633d9332c785033eabc04e",
          "sha1": "d79274e2e123377409c48ce6831cebb18b07f92f",
          "md5": "eea77b980b16a4f13020217b22869598"
        }
      ]
    }
  ]
}
