{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-wovn",
    "version": "1.19.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-wovn-1.19.17.jar",
          "url": "nautilus-util-wovn-1.19.17.jar",
          "size": 4985,
          "sha512": "399f786593f6326a12d9bb371c1b4d1da663a9e12749626f958bae18fc4037fa4b2afa7fe73b64e665b2c6a3945adead019950e516fcf008e157e996df46e104",
          "sha256": "4fc3609afeeda99396c7ff65ced0df6077bc37cf2647282e28ce80eef39c6a3a",
          "sha1": "6693bdfd44a6e678a54e7aee4aa9f91dafbc208f",
          "md5": "16863ce8eb86a60afa6372720849d494"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-wovn-1.19.17.jar",
          "url": "nautilus-util-wovn-1.19.17.jar",
          "size": 4985,
          "sha512": "399f786593f6326a12d9bb371c1b4d1da663a9e12749626f958bae18fc4037fa4b2afa7fe73b64e665b2c6a3945adead019950e516fcf008e157e996df46e104",
          "sha256": "4fc3609afeeda99396c7ff65ced0df6077bc37cf2647282e28ce80eef39c6a3a",
          "sha1": "6693bdfd44a6e678a54e7aee4aa9f91dafbc208f",
          "md5": "16863ce8eb86a60afa6372720849d494"
        }
      ]
    }
  ]
}
