{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-network",
    "version": "1.12.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.12.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.12.13.aar",
          "url": "nautilus-util-network-1.12.13.aar",
          "size": 23244,
          "sha512": "a618e8ea9031c1c68b965cb8d2beea4728556515e937a1cc77eeb0f63b546d6dc65a16acf6b5f0184f4028355c83f9ac9b8efa3fb62e9cd32cf15378dc3270bc",
          "sha256": "527de4103ac689b68109ee5912b2baaf9e6d04a0f6d7c01ed3baab4a8070a611",
          "sha1": "953d2cea364d166f4f2cb683df32d6318ecb9e87",
          "md5": "4c2c2ff57b8429b4a89cfe57b7b81499"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.12.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.12.13.aar",
          "url": "nautilus-util-network-1.12.13.aar",
          "size": 23244,
          "sha512": "a618e8ea9031c1c68b965cb8d2beea4728556515e937a1cc77eeb0f63b546d6dc65a16acf6b5f0184f4028355c83f9ac9b8efa3fb62e9cd32cf15378dc3270bc",
          "sha256": "527de4103ac689b68109ee5912b2baaf9e6d04a0f6d7c01ed3baab4a8070a611",
          "sha1": "953d2cea364d166f4f2cb683df32d6318ecb9e87",
          "md5": "4c2c2ff57b8429b4a89cfe57b7b81499"
        }
      ]
    }
  ]
}
