{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-imaging",
    "version": "1.15.5-feu1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-network",
          "version": {
            "requires": "1.15.5-feu1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-imaging-1.15.5-feu1.aar",
          "url": "nautilus-util-imaging-1.15.5-feu1.aar",
          "size": 11286,
          "sha512": "0487b1c9c40b556140a690ef07980c58649bca24088bfc613661ec9cce93354ec6fd96b4a3b19f5942aa93e692344b85358b5baa1bd7f56401e2dac8f771b3b9",
          "sha256": "704c41d47639e0f01ec3996a90e6195b65db07c0fb4442df0aaba10829af54ed",
          "sha1": "87d98b37ee5d80ba4653138ed0ba1c9207ec91dd",
          "md5": "2a35f07cf3cd28451eb7d957d76a2275"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-network",
          "version": {
            "requires": "1.15.5-feu1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-imaging-1.15.5-feu1.aar",
          "url": "nautilus-util-imaging-1.15.5-feu1.aar",
          "size": 11286,
          "sha512": "0487b1c9c40b556140a690ef07980c58649bca24088bfc613661ec9cce93354ec6fd96b4a3b19f5942aa93e692344b85358b5baa1bd7f56401e2dac8f771b3b9",
          "sha256": "704c41d47639e0f01ec3996a90e6195b65db07c0fb4442df0aaba10829af54ed",
          "sha1": "87d98b37ee5d80ba4653138ed0ba1c9207ec91dd",
          "md5": "2a35f07cf3cd28451eb7d957d76a2275"
        }
      ]
    }
  ]
}
