{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-format",
    "version": "1.15.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.15.7.aar",
          "url": "nautilus-util-format-1.15.7.aar",
          "size": 8979,
          "sha512": "d6ec189dae13b14766d8ed4167b643492ee9a2389d0bcb9838203824807226eef8220dd0088ec4d79041ed477e42d7291d0d93d1ba62374fa95584713712ba86",
          "sha256": "dfccb1afdbf45c375195d4dab2bdad3c7e045bb2a8055ee00b0b5c13a1ade1fc",
          "sha1": "cb4d6e2c1419258f787c3e442ee8786200b42429",
          "md5": "b1a44a219c1a69dd0d26367fed66aaaa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.15.7.aar",
          "url": "nautilus-util-format-1.15.7.aar",
          "size": 8979,
          "sha512": "d6ec189dae13b14766d8ed4167b643492ee9a2389d0bcb9838203824807226eef8220dd0088ec4d79041ed477e42d7291d0d93d1ba62374fa95584713712ba86",
          "sha256": "dfccb1afdbf45c375195d4dab2bdad3c7e045bb2a8055ee00b0b5c13a1ade1fc",
          "sha1": "cb4d6e2c1419258f787c3e442ee8786200b42429",
          "md5": "b1a44a219c1a69dd0d26367fed66aaaa"
        }
      ]
    }
  ]
}
