{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-tools-logging",
    "version": "1.7.2-hotfix",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-logging-1.7.2-hotfix.aar",
          "url": "nautilus-tools-logging-1.7.2-hotfix.aar",
          "size": 16668,
          "sha512": "3068641a5f161824d78cf29b61d912ed5f0dc986d2bfb8c0fad08251c0671e0fd0ef346e84c734094910f8956240e4319fba36ab932eff98776c051b89220fea",
          "sha256": "d80ddf461f7b9dd084a47136a32ad2c743f8c23ff5c807e76936f5df4bfae748",
          "sha1": "465ba6e1f3eb1657ca02e90a5232f809a75884f1",
          "md5": "c8a3e23474f34a88f35f63e5e7838f18"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-logging-1.7.2-hotfix.aar",
          "url": "nautilus-tools-logging-1.7.2-hotfix.aar",
          "size": 16668,
          "sha512": "3068641a5f161824d78cf29b61d912ed5f0dc986d2bfb8c0fad08251c0671e0fd0ef346e84c734094910f8956240e4319fba36ab932eff98776c051b89220fea",
          "sha256": "d80ddf461f7b9dd084a47136a32ad2c743f8c23ff5c807e76936f5df4bfae748",
          "sha1": "465ba6e1f3eb1657ca02e90a5232f809a75884f1",
          "md5": "c8a3e23474f34a88f35f63e5e7838f18"
        }
      ]
    }
  ]
}
