{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-analytics",
    "version": "1.25.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.25.14"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-1.25.14.aar",
          "url": "nautilus-analytics-1.25.14.aar",
          "size": 169860,
          "sha512": "973a2cba2ff7372979eb6922f290d655b0b93c915c57f8595a10bfe9bd0f0e53de166b83d77c5e93fddbadfc7e50b6731fa63438a4f9a97db0ff8366b1ac6aff",
          "sha256": "cb693f6ae7bedfd6a7ae7516444ad90ddbbf818eeeac57882a9f06194f9728b7",
          "sha1": "2db4f10f5ffa3cd5690f059cc618f9377e60cd85",
          "md5": "cfdb8ff87446dc091896b5619ff0c0c4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.3.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.3.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.15.2"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.15.2"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.25.14"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-1.25.14.aar",
          "url": "nautilus-analytics-1.25.14.aar",
          "size": 169860,
          "sha512": "973a2cba2ff7372979eb6922f290d655b0b93c915c57f8595a10bfe9bd0f0e53de166b83d77c5e93fddbadfc7e50b6731fa63438a4f9a97db0ff8366b1ac6aff",
          "sha256": "cb693f6ae7bedfd6a7ae7516444ad90ddbbf818eeeac57882a9f06194f9728b7",
          "sha1": "2db4f10f5ffa3cd5690f059cc618f9377e60cd85",
          "md5": "cfdb8ff87446dc091896b5619ff0c0c4"
        }
      ]
    }
  ]
}
