{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-analytics-amplitude-plugin",
    "version": "1.19.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.amplitude",
          "module": "analytics-android",
          "version": {
            "requires": "1.21.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-amplitude-plugin-1.19.16.aar",
          "url": "nautilus-analytics-amplitude-plugin-1.19.16.aar",
          "size": 12107,
          "sha512": "d513cc6ee6f8a44e364cecb5c8df30f7c249715138623c64210f911781f8184370c9a5d476c4f3f8c2fa88c7f6a4594bc3bb9d933429d097fc7327751192a920",
          "sha256": "d1e474d79822924a5663e14761d5b8c3c62c8b972e626b960f534e932f064fbc",
          "sha1": "7d4eabbac5048dad9bf7cd10c1d1403c7ad63b4d",
          "md5": "824e2fbed6a5347e6dcf1afe03568228"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.amplitude",
          "module": "plugin-session-replay-android",
          "version": {
            "requires": "0.20.12"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-analytics",
          "version": {
            "requires": "1.19.16"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.19.16"
          }
        },
        {
          "group": "com.amplitude",
          "module": "analytics-android",
          "version": {
            "requires": "1.21.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-amplitude-plugin-1.19.16.aar",
          "url": "nautilus-analytics-amplitude-plugin-1.19.16.aar",
          "size": 12107,
          "sha512": "d513cc6ee6f8a44e364cecb5c8df30f7c249715138623c64210f911781f8184370c9a5d476c4f3f8c2fa88c7f6a4594bc3bb9d933429d097fc7327751192a920",
          "sha256": "d1e474d79822924a5663e14761d5b8c3c62c8b972e626b960f534e932f064fbc",
          "sha1": "7d4eabbac5048dad9bf7cd10c1d1403c7ad63b4d",
          "md5": "824e2fbed6a5347e6dcf1afe03568228"
        }
      ]
    }
  ]
}
