{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-code-image-providers",
    "version": "1.19.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.19.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-code-image-providers-1.19.3.aar",
          "url": "nautilus-code-image-providers-1.19.3.aar",
          "size": 12791,
          "sha512": "e7192995615400b90186d8891a3372833aecf66a27797463c81ffe1e2fc8eeea1f7b8ef0494ef82793727f0f8117abddf2d467832c326e7c7339b837390b3285",
          "sha256": "569ce3b8cdd9ee1b654d5e0bf16457055a922792362a6769deaa1a8f9b65d256",
          "sha1": "8547bdbe99541865819412050c43a74aedba084f",
          "md5": "71b36b064f4135dd3a3191f1f2f34b50"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.19.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-code-image-providers-1.19.3.aar",
          "url": "nautilus-code-image-providers-1.19.3.aar",
          "size": 12791,
          "sha512": "e7192995615400b90186d8891a3372833aecf66a27797463c81ffe1e2fc8eeea1f7b8ef0494ef82793727f0f8117abddf2d467832c326e7c7339b837390b3285",
          "sha256": "569ce3b8cdd9ee1b654d5e0bf16457055a922792362a6769deaa1a8f9b65d256",
          "sha1": "8547bdbe99541865819412050c43a74aedba084f",
          "md5": "71b36b064f4135dd3a3191f1f2f34b50"
        }
      ]
    }
  ]
}
