{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-tools-logging",
    "version": "1.7.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-logging-1.7.18.aar",
          "url": "nautilus-tools-logging-1.7.18.aar",
          "size": 16669,
          "sha512": "46e991dd8814ff0b53e38377bfb97f1075f0e9a8d993b09d76cd919fe8ce89ae55be3ab3915a1558b305eb5ade124eda4e837a65d1701cf10be9cf297f137e27",
          "sha256": "a6187f24c05ef9862943aab6d6db23deebf5fef333ab6759e3c2a04a4792f7d7",
          "sha1": "b1dcff3a924c51e940fe98666db285e8d0a2451d",
          "md5": "351803f258f93e72d35715f37a96d309"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-logging-1.7.18.aar",
          "url": "nautilus-tools-logging-1.7.18.aar",
          "size": 16669,
          "sha512": "46e991dd8814ff0b53e38377bfb97f1075f0e9a8d993b09d76cd919fe8ce89ae55be3ab3915a1558b305eb5ade124eda4e837a65d1701cf10be9cf297f137e27",
          "sha256": "a6187f24c05ef9862943aab6d6db23deebf5fef333ab6759e3c2a04a4792f7d7",
          "sha1": "b1dcff3a924c51e940fe98666db285e8d0a2451d",
          "md5": "351803f258f93e72d35715f37a96d309"
        }
      ]
    }
  ]
}
