{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-maintenance",
    "version": "1.11.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-network",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-maintenance-1.11.1.aar",
          "url": "nautilus-maintenance-1.11.1.aar",
          "size": 41036,
          "sha512": "e326c0f7d12098194c5cadb4b36d7d69ff92b19295c2b0a68b315f7ea31d7f73647390fad0b111c6cfca911947301d2950239a8901c034ada4e54c16ed04cddd",
          "sha256": "53d7eaa0982a54baa4f5136818af43b6cff34c23d883eaf16cdc7dcb692f8998",
          "sha1": "5376d60c49bd618e71a2c67f6b4558dc9f66c8e6",
          "md5": "4e5b02f3433e42081c92acd9a7d84166"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-network",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-maintenance-1.11.1.aar",
          "url": "nautilus-maintenance-1.11.1.aar",
          "size": 41036,
          "sha512": "e326c0f7d12098194c5cadb4b36d7d69ff92b19295c2b0a68b315f7ea31d7f73647390fad0b111c6cfca911947301d2950239a8901c034ada4e54c16ed04cddd",
          "sha256": "53d7eaa0982a54baa4f5136818af43b6cff34c23d883eaf16cdc7dcb692f8998",
          "sha1": "5376d60c49bd618e71a2c67f6b4558dc9f66c8e6",
          "md5": "4e5b02f3433e42081c92acd9a7d84166"
        }
      ]
    }
  ]
}
