{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-tools-livedata",
    "version": "1.13.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-livedata-1.13.1.aar",
          "url": "nautilus-tools-livedata-1.13.1.aar",
          "size": 10479,
          "sha512": "614f3e8578636489cd68cd5f3942c74518f83b2778ab26ca2b4d104f6fb378570ff107215f96ca1ca6a28122749be779547a4764a2715582455aacc6b07d7cb2",
          "sha256": "d2471e50585b8c98284c9a2b5013500676f0c124333eda85ffef6e47f23d12ff",
          "sha1": "4865d1b4f870db8222fe67f460341904d29d41a8",
          "md5": "3447a04ee647ef8679f69237c341b6b8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-livedata-1.13.1.aar",
          "url": "nautilus-tools-livedata-1.13.1.aar",
          "size": 10479,
          "sha512": "614f3e8578636489cd68cd5f3942c74518f83b2778ab26ca2b4d104f6fb378570ff107215f96ca1ca6a28122749be779547a4764a2715582455aacc6b07d7cb2",
          "sha256": "d2471e50585b8c98284c9a2b5013500676f0c124333eda85ffef6e47f23d12ff",
          "sha1": "4865d1b4f870db8222fe67f460341904d29d41a8",
          "md5": "3447a04ee647ef8679f69237c341b6b8"
        }
      ]
    }
  ]
}
