{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-imaging",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-network",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-imaging-1.10.0.aar",
          "url": "nautilus-util-imaging-1.10.0.aar",
          "size": 11260,
          "sha512": "05a6a07c6b4edd3c081661e7ab4bcc4faf1640f84e7a60fe21055e2ee9f90e31864771ad2341874d232d4afde39fdfddd3f07160132ba69b45e2785830fdec12",
          "sha256": "01c9442bfc9e140d90cd047ba8e5504cc94b85a3442eee4e8eb2a9d3fbfc634f",
          "sha1": "d7bac0dd4ae2c70b04770b0c421d8e524b52e096",
          "md5": "ef6b6380b581cf92dab777107bf9aff9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-network",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-imaging-1.10.0.aar",
          "url": "nautilus-util-imaging-1.10.0.aar",
          "size": 11260,
          "sha512": "05a6a07c6b4edd3c081661e7ab4bcc4faf1640f84e7a60fe21055e2ee9f90e31864771ad2341874d232d4afde39fdfddd3f07160132ba69b45e2785830fdec12",
          "sha256": "01c9442bfc9e140d90cd047ba8e5504cc94b85a3442eee4e8eb2a9d3fbfc634f",
          "sha1": "d7bac0dd4ae2c70b04770b0c421d8e524b52e096",
          "md5": "ef6b6380b581cf92dab777107bf9aff9"
        }
      ]
    }
  ]
}
