{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-network",
    "version": "1.6.9-hotfix1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.6.9-hotfix1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.6.9-hotfix1.aar",
          "url": "nautilus-util-network-1.6.9-hotfix1.aar",
          "size": 23658,
          "sha512": "c0ebf6fbf0042f8aad4ed3c8f6a88fcd59427bfb2be60dcb76fe46f91c18056199147687c16976f6e50bfc7272d87f9dea414b4dd579a0f793e237778f2550cd",
          "sha256": "63ed98b1982e64d6284709126ff3ea9a7814053a84c2bf5dfd7ec572fea568f3",
          "sha1": "f229db758c41bc818ea854f67a25d67fa1b290e0",
          "md5": "fe2b804838edb972f48058638e309f71"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.6.9-hotfix1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.6.9-hotfix1.aar",
          "url": "nautilus-util-network-1.6.9-hotfix1.aar",
          "size": 23658,
          "sha512": "c0ebf6fbf0042f8aad4ed3c8f6a88fcd59427bfb2be60dcb76fe46f91c18056199147687c16976f6e50bfc7272d87f9dea414b4dd579a0f793e237778f2550cd",
          "sha256": "63ed98b1982e64d6284709126ff3ea9a7814053a84c2bf5dfd7ec572fea568f3",
          "sha1": "f229db758c41bc818ea854f67a25d67fa1b290e0",
          "md5": "fe2b804838edb972f48058638e309f71"
        }
      ]
    }
  ]
}
