{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-core",
    "version": "1.16.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.16.6"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-cryptography",
          "version": {
            "requires": "1.16.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-core-1.16.6.aar",
          "url": "nautilus-core-1.16.6.aar",
          "size": 107545,
          "sha512": "5fdbb853325f661ca5e8ff68f73a50a10883c6ff19074984107b2b7ccc46141a470ff110ef63369b501e068753eb59abceccb00658d8fbfc83d545a94842aa0e",
          "sha256": "2403dfeef2177e69b4566084303f78f1f75de244302a85ec0d7ed9c5b166edd4",
          "sha1": "bce2636f7d7e1a542ff1045252587b99da021a84",
          "md5": "f05f0e40d6277114bfdc8fe80265a027"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.16.6"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-cryptography",
          "version": {
            "requires": "1.16.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-core-1.16.6.aar",
          "url": "nautilus-core-1.16.6.aar",
          "size": 107545,
          "sha512": "5fdbb853325f661ca5e8ff68f73a50a10883c6ff19074984107b2b7ccc46141a470ff110ef63369b501e068753eb59abceccb00658d8fbfc83d545a94842aa0e",
          "sha256": "2403dfeef2177e69b4566084303f78f1f75de244302a85ec0d7ed9c5b166edd4",
          "sha1": "bce2636f7d7e1a542ff1045252587b99da021a84",
          "md5": "f05f0e40d6277114bfdc8fe80265a027"
        }
      ]
    }
  ]
}
