{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-core",
    "version": "1.19.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.19.9"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-cryptography",
          "version": {
            "requires": "1.19.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-core-1.19.9.aar",
          "url": "nautilus-core-1.19.9.aar",
          "size": 107755,
          "sha512": "6af91d7a6adbcdf83572c2a9fd9bd87f820348b9c0c312a3d8f6590106dd73c859ebcecebaae6f15a92db946625b40ec25f84059e4742f5098851ea78f7dba1f",
          "sha256": "d9ffc744ac3286e84abe888435a856e2ca43348feb1345dd0aab82d70b58ee0a",
          "sha1": "2d64e7e14fa681bf9b440d4c157f6817d684050d",
          "md5": "a8e57f5e06557a5a68602dafcdfcae90"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.19.9"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-cryptography",
          "version": {
            "requires": "1.19.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-core-1.19.9.aar",
          "url": "nautilus-core-1.19.9.aar",
          "size": 107755,
          "sha512": "6af91d7a6adbcdf83572c2a9fd9bd87f820348b9c0c312a3d8f6590106dd73c859ebcecebaae6f15a92db946625b40ec25f84059e4742f5098851ea78f7dba1f",
          "sha256": "d9ffc744ac3286e84abe888435a856e2ca43348feb1345dd0aab82d70b58ee0a",
          "sha1": "2d64e7e14fa681bf9b440d4c157f6817d684050d",
          "md5": "a8e57f5e06557a5a68602dafcdfcae90"
        }
      ]
    }
  ]
}
