{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-datetime",
    "version": "1.6.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-datetime-1.6.11.aar",
          "url": "nautilus-util-datetime-1.6.11.aar",
          "size": 13912,
          "sha512": "4d2091c3301edb598bb07b8913c55869319b50550b8a5b0b39a1075b42c97c08e20e3d43ea50de0451d7e1c35c0a5c5a807bc38abc09401828e7c32544682c44",
          "sha256": "6e94d5ce3f720b3d16b1859ab640274869f96a7bc7ed0d9cc4b08547c473dd0f",
          "sha1": "afd17faa897220770bf1a89908545546cd6d086f",
          "md5": "1b9620049f93ed81308733e0a904e494"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.jakewharton.threetenabp",
          "module": "threetenabp",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-datetime-1.6.11.aar",
          "url": "nautilus-util-datetime-1.6.11.aar",
          "size": 13912,
          "sha512": "4d2091c3301edb598bb07b8913c55869319b50550b8a5b0b39a1075b42c97c08e20e3d43ea50de0451d7e1c35c0a5c5a807bc38abc09401828e7c32544682c44",
          "sha256": "6e94d5ce3f720b3d16b1859ab640274869f96a7bc7ed0d9cc4b08547c473dd0f",
          "sha1": "afd17faa897220770bf1a89908545546cd6d086f",
          "md5": "1b9620049f93ed81308733e0a904e494"
        }
      ]
    }
  ]
}
