{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-datetime",
    "version": "1.7.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-datetime-1.7.10.aar",
          "url": "nautilus-util-datetime-1.7.10.aar",
          "size": 15039,
          "sha512": "d5b048083c3c0a1e9128424d066a9fb1c9783b3d3cf33164cfa8e8a2f9576dd6bebf04cbe5f973514379be38931521ff43bd86818d1188058214d879ad1c037d",
          "sha256": "36954b1d538f704a2367ad520503581b5e3cf76b7ce74bdc0986602d3892d9a4",
          "sha1": "b6dd3cf9afead2595e4b4f0258021775f75236a2",
          "md5": "07255448d1892ac240e217abf5c7c9fa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.jakewharton.threetenabp",
          "module": "threetenabp",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-datetime-1.7.10.aar",
          "url": "nautilus-util-datetime-1.7.10.aar",
          "size": 15039,
          "sha512": "d5b048083c3c0a1e9128424d066a9fb1c9783b3d3cf33164cfa8e8a2f9576dd6bebf04cbe5f973514379be38931521ff43bd86818d1188058214d879ad1c037d",
          "sha256": "36954b1d538f704a2367ad520503581b5e3cf76b7ce74bdc0986602d3892d9a4",
          "sha1": "b6dd3cf9afead2595e4b4f0258021775f75236a2",
          "md5": "07255448d1892ac240e217abf5c7c9fa"
        }
      ]
    }
  ]
}
