{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-analytics",
    "version": "1.5.0-alpha3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.5.0-alpha3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-1.5.0-alpha3.aar",
          "url": "nautilus-analytics-1.5.0-alpha3.aar",
          "size": 141337,
          "sha512": "038edba5f0b81b859ac6729571241237aba2843d52561891489a645cf93e13391035c71ef9d633f584ed19de6bad74abaccecd678d3c453b5e76eb2a1a7fe9e6",
          "sha256": "c7c8a5098f9e533af721c391d0e99dabad3926787a98b93c6ec27e95d35dc81f",
          "sha1": "1aef122dab3ce569065aae61d0eed2cbef2f9822",
          "md5": "892dc37727edd35feba3f70c548aa2b6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.5.0-alpha3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-1.5.0-alpha3.aar",
          "url": "nautilus-analytics-1.5.0-alpha3.aar",
          "size": 141337,
          "sha512": "038edba5f0b81b859ac6729571241237aba2843d52561891489a645cf93e13391035c71ef9d633f584ed19de6bad74abaccecd678d3c453b5e76eb2a1a7fe9e6",
          "sha256": "c7c8a5098f9e533af721c391d0e99dabad3926787a98b93c6ec27e95d35dc81f",
          "sha1": "1aef122dab3ce569065aae61d0eed2cbef2f9822",
          "md5": "892dc37727edd35feba3f70c548aa2b6"
        }
      ]
    }
  ]
}
