{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-wovn",
    "version": "1.19.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-wovn-1.19.6.jar",
          "url": "nautilus-util-wovn-1.19.6.jar",
          "size": 4985,
          "sha512": "906fed23b307ac5384d7ea15bf73cb6fe1f7291c12a64b1542e19e0c3586e44453d261fba3044ac5d2bddf63e8e66067e7656441e220fa8860f3f150940cc152",
          "sha256": "1dc987a593752430dacbc74d998b6a09b4a5aab393f4375e8efe1267abeeb3d5",
          "sha1": "3f33c38b8cfbdc49897eee67aeb7d3534d64eee1",
          "md5": "48fc4c117a8215da6f660046e4265059"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-wovn-1.19.6.jar",
          "url": "nautilus-util-wovn-1.19.6.jar",
          "size": 4985,
          "sha512": "906fed23b307ac5384d7ea15bf73cb6fe1f7291c12a64b1542e19e0c3586e44453d261fba3044ac5d2bddf63e8e66067e7656441e220fa8860f3f150940cc152",
          "sha256": "1dc987a593752430dacbc74d998b6a09b4a5aab393f4375e8efe1267abeeb3d5",
          "sha1": "3f33c38b8cfbdc49897eee67aeb7d3534d64eee1",
          "md5": "48fc4c117a8215da6f660046e4265059"
        }
      ]
    }
  ]
}
