{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-config",
    "version": "1.16.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.16.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-config-1.16.2.aar",
          "url": "nautilus-config-1.16.2.aar",
          "size": 151025,
          "sha512": "880eb3841916e35564691c6a555d1c70931a9fde5b64007367c421eeefb76fbb4eac116c0f14b5abf76f4e2f3e06903b47f5da2f71fdd13e6d5f284f1ecb92cf",
          "sha256": "f5df6a31828eb0ac8f7e77772caf2577d79b50264a4501f05c488bcfb9886661",
          "sha1": "7e2f8c8dfac69eb5a236478d2b937b75ba1a35f0",
          "md5": "ff1d8f45a68e2893bfa929a1006b393e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.16.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-config-1.16.2.aar",
          "url": "nautilus-config-1.16.2.aar",
          "size": 151025,
          "sha512": "880eb3841916e35564691c6a555d1c70931a9fde5b64007367c421eeefb76fbb4eac116c0f14b5abf76f4e2f3e06903b47f5da2f71fdd13e6d5f284f1ecb92cf",
          "sha256": "f5df6a31828eb0ac8f7e77772caf2577d79b50264a4501f05c488bcfb9886661",
          "sha1": "7e2f8c8dfac69eb5a236478d2b937b75ba1a35f0",
          "md5": "ff1d8f45a68e2893bfa929a1006b393e"
        }
      ]
    }
  ]
}
