{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-datetime",
    "version": "1.6.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.6.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-datetime-1.6.12.aar",
          "url": "nautilus-util-datetime-1.6.12.aar",
          "size": 13913,
          "sha512": "85b55876f88a017068461a5ce2b8bea5e29ae2307adaafe12c76cbea0587e8014a55d31d89e09cd45ac49ff83068648db301223446957011f3c640df0ba0d11a",
          "sha256": "9cdee9139db54f757fadd580b0a97191208cdcb502a3f8768c2cd4a330e91db6",
          "sha1": "d1a7dea93d15a13d4becb6fa6534cd39e5a2389c",
          "md5": "50c9e2278f96e9fbd173485874873155"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.6.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.jakewharton.threetenabp",
          "module": "threetenabp",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-datetime-1.6.12.aar",
          "url": "nautilus-util-datetime-1.6.12.aar",
          "size": 13913,
          "sha512": "85b55876f88a017068461a5ce2b8bea5e29ae2307adaafe12c76cbea0587e8014a55d31d89e09cd45ac49ff83068648db301223446957011f3c640df0ba0d11a",
          "sha256": "9cdee9139db54f757fadd580b0a97191208cdcb502a3f8768c2cd4a330e91db6",
          "sha1": "d1a7dea93d15a13d4becb6fa6534cd39e5a2389c",
          "md5": "50c9e2278f96e9fbd173485874873155"
        }
      ]
    }
  ]
}
