{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-stamp-rally-ui",
    "version": "1.25.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-code-reader",
          "version": {
            "requires": "1.25.5"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-server-time",
          "version": {
            "requires": "1.25.5"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-stamp",
          "version": {
            "requires": "1.25.5"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-map",
          "version": {
            "requires": "1.25.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "9.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-stamp-rally-ui-1.25.5.aar",
          "url": "nautilus-stamp-rally-ui-1.25.5.aar",
          "size": 464837,
          "sha512": "5af9abff4317043f65aa5c6d6229340656d7a6923c35b1f62c906f1b70ef1f42576a714f3a6f3c4a352970bc79c11137e6249a4a451fc927ebaf76871d3283d4",
          "sha256": "dffee02d72b433490a0ed89e6c0c030265acbcde5ced0508f4831d80bbabbc92",
          "sha1": "4221c18b3f1a5b9f460386c90bc08c438a32de37",
          "md5": "d449717655ce02b397791ea452f39d1c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-imaging",
          "version": {
            "requires": "1.25.5"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-wovn",
          "version": {
            "requires": "1.25.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.18.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.9"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-maps",
          "version": {
            "requires": "20.0.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.03.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-code-reader",
          "version": {
            "requires": "1.25.5"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-server-time",
          "version": {
            "requires": "1.25.5"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-stamp",
          "version": {
            "requires": "1.25.5"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-map",
          "version": {
            "requires": "1.25.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "9.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-stamp-rally-ui-1.25.5.aar",
          "url": "nautilus-stamp-rally-ui-1.25.5.aar",
          "size": 464837,
          "sha512": "5af9abff4317043f65aa5c6d6229340656d7a6923c35b1f62c906f1b70ef1f42576a714f3a6f3c4a352970bc79c11137e6249a4a451fc927ebaf76871d3283d4",
          "sha256": "dffee02d72b433490a0ed89e6c0c030265acbcde5ced0508f4831d80bbabbc92",
          "sha1": "4221c18b3f1a5b9f460386c90bc08c438a32de37",
          "md5": "d449717655ce02b397791ea452f39d1c"
        }
      ]
    }
  ]
}
