{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-network",
    "version": "1.6.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.6.7.aar",
          "url": "nautilus-util-network-1.6.7.aar",
          "size": 23660,
          "sha512": "f4b3fe7999b3521886daf8debbcd1947de0638e89d0bf79d954721dcc2d0c07b7417e9150d5fbb28ee9d1be3063b283490157918bbd5d7f3e32e98bbab78f687",
          "sha256": "6351e539a85acdab553ea41144650473bd1627c972a1e5440dd72e440c278dee",
          "sha1": "6c6a103509a06b4e59f71e13bc698b6bd7d56527",
          "md5": "73a8f3516b698fe5c31355311e1058cf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.6.7.aar",
          "url": "nautilus-util-network-1.6.7.aar",
          "size": 23660,
          "sha512": "f4b3fe7999b3521886daf8debbcd1947de0638e89d0bf79d954721dcc2d0c07b7417e9150d5fbb28ee9d1be3063b283490157918bbd5d7f3e32e98bbab78f687",
          "sha256": "6351e539a85acdab553ea41144650473bd1627c972a1e5440dd72e440c278dee",
          "sha1": "6c6a103509a06b4e59f71e13bc698b6bd7d56527",
          "md5": "73a8f3516b698fe5c31355311e1058cf"
        }
      ]
    }
  ]
}
