{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-network",
    "version": "1.19.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.19.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.19.9.aar",
          "url": "nautilus-util-network-1.19.9.aar",
          "size": 23281,
          "sha512": "12ea135102700e95fd3829c181725c4612e0688f9a3901746efb3737b9c268cffc94754b67ace97ab9007025e919939b0ea393d618aeaa3ce8947e4f8d4aa88f",
          "sha256": "b4d4c0ea9dfcc2460dbd9e062fc4c5afc32f9673ebd01caa0e76e55b587ad990",
          "sha1": "db1d3f490467a998b9ee45995975039bdaba4db9",
          "md5": "27f9719d97df638d0ae4b6f0c8236a13"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.19.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.19.9.aar",
          "url": "nautilus-util-network-1.19.9.aar",
          "size": 23281,
          "sha512": "12ea135102700e95fd3829c181725c4612e0688f9a3901746efb3737b9c268cffc94754b67ace97ab9007025e919939b0ea393d618aeaa3ce8947e4f8d4aa88f",
          "sha256": "b4d4c0ea9dfcc2460dbd9e062fc4c5afc32f9673ebd01caa0e76e55b587ad990",
          "sha1": "db1d3f490467a998b9ee45995975039bdaba4db9",
          "md5": "27f9719d97df638d0ae4b6f0c8236a13"
        }
      ]
    }
  ]
}
