{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-format",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.4.0.aar",
          "url": "nautilus-util-format-1.4.0.aar",
          "size": 8822,
          "sha512": "afef6ab8084e8c280c5a51b888e589d75b3304b9093a8f8f278e19e8b394e4b461def06a62d4d082b8ec805f8e02bd980829cd3812210caec4ef1fa085fc8a13",
          "sha256": "42153cc0f34db886877f012e6def93be5bdd8a4ff50dd37b977c1bbc97837903",
          "sha1": "aa4a1a53577765dad99be9bb36306eeeef96357b",
          "md5": "b382370544c323456200b96b75ab3ffd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.4.0.aar",
          "url": "nautilus-util-format-1.4.0.aar",
          "size": 8822,
          "sha512": "afef6ab8084e8c280c5a51b888e589d75b3304b9093a8f8f278e19e8b394e4b461def06a62d4d082b8ec805f8e02bd980829cd3812210caec4ef1fa085fc8a13",
          "sha256": "42153cc0f34db886877f012e6def93be5bdd8a4ff50dd37b977c1bbc97837903",
          "sha1": "aa4a1a53577765dad99be9bb36306eeeef96357b",
          "md5": "b382370544c323456200b96b75ab3ffd"
        }
      ]
    }
  ]
}
