{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-network",
    "version": "1.23.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.23.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.23.2.aar",
          "url": "nautilus-util-network-1.23.2.aar",
          "size": 17159,
          "sha512": "4f686d64e37cd5ced55c745a4dacbba9f4790fcff4d079d19ef3a2e8f77838fe50d4ab3773409719ab4ce0666005c55b5024fdb7c6f367a30e003a40b1964ccf",
          "sha256": "2756eee4cf6fcbf54ebb1a497c7c5dee81b389fe48055da51867d287707218cf",
          "sha1": "1c117c58c25987246620582edf6d9e1c12f4ef8f",
          "md5": "96cd3e62d3b37908752e6c9ddc10dec0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.23.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.23.2.aar",
          "url": "nautilus-util-network-1.23.2.aar",
          "size": 17159,
          "sha512": "4f686d64e37cd5ced55c745a4dacbba9f4790fcff4d079d19ef3a2e8f77838fe50d4ab3773409719ab4ce0666005c55b5024fdb7c6f367a30e003a40b1964ccf",
          "sha256": "2756eee4cf6fcbf54ebb1a497c7c5dee81b389fe48055da51867d287707218cf",
          "sha1": "1c117c58c25987246620582edf6d9e1c12f4ef8f",
          "md5": "96cd3e62d3b37908752e6c9ddc10dec0"
        }
      ]
    }
  ]
}
