{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-tools-logging",
    "version": "1.19.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-logging-1.19.24.aar",
          "url": "nautilus-tools-logging-1.19.24.aar",
          "size": 19675,
          "sha512": "392b7743500c280caa48c23fbbec3fe6c7dedcae97cee43e48209c6e06e0af664adac0086439a1a4920f5ea04974afff22976aa441589aeb70a5464a9cdcd49a",
          "sha256": "4e22d735e68098e87d71bd7930da30d56176950986712b8b56301352c5eb0a47",
          "sha1": "60cc2a33553f06dac5a0c0ebe1783667f4872b8e",
          "md5": "e3fd79bc6a8c4d5c02415b8d7b50bfdc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-logging-1.19.24.aar",
          "url": "nautilus-tools-logging-1.19.24.aar",
          "size": 19675,
          "sha512": "392b7743500c280caa48c23fbbec3fe6c7dedcae97cee43e48209c6e06e0af664adac0086439a1a4920f5ea04974afff22976aa441589aeb70a5464a9cdcd49a",
          "sha256": "4e22d735e68098e87d71bd7930da30d56176950986712b8b56301352c5eb0a47",
          "sha1": "60cc2a33553f06dac5a0c0ebe1783667f4872b8e",
          "md5": "e3fd79bc6a8c4d5c02415b8d7b50bfdc"
        }
      ]
    }
  ]
}
