{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-tools-livedata",
    "version": "1.14.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-livedata-1.14.5.aar",
          "url": "nautilus-tools-livedata-1.14.5.aar",
          "size": 10484,
          "sha512": "277146ad3f846826d36242ac37c10d9e12ba4168926bd7ea142f4b2f0398e2f374d673980d39e274458636ed2b27cd6ac6e18e7eb656a0845bc5c192790c4078",
          "sha256": "7ee5b5ada7cfd73b8a0c4b06fdcd6ead5cec64c8097db167c2474b3247978500",
          "sha1": "e65838d58296afd6eb370e478ded855aa17d27c9",
          "md5": "c14ee3b43580b38bc2322d31793273b4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-livedata-1.14.5.aar",
          "url": "nautilus-tools-livedata-1.14.5.aar",
          "size": 10484,
          "sha512": "277146ad3f846826d36242ac37c10d9e12ba4168926bd7ea142f4b2f0398e2f374d673980d39e274458636ed2b27cd6ac6e18e7eb656a0845bc5c192790c4078",
          "sha256": "7ee5b5ada7cfd73b8a0c4b06fdcd6ead5cec64c8097db167c2474b3247978500",
          "sha1": "e65838d58296afd6eb370e478ded855aa17d27c9",
          "md5": "c14ee3b43580b38bc2322d31793273b4"
        }
      ]
    }
  ]
}
