{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-analytics",
    "version": "1.6.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-1.6.10.aar",
          "url": "nautilus-analytics-1.6.10.aar",
          "size": 145036,
          "sha512": "911a8e0bde5a201650040c15d2d185a76114b43afa61c7ca777b6a12ad9a122d9d870179a1959d0565500dbf90a1e6ad0560a75fcd6df60ce70aa200e51f653b",
          "sha256": "ac41ee6e94bc1ebd11a4980be72354d3ebcfc97125a6b0c9082dabe0c748bb99",
          "sha1": "ff1e079141540f72d2bcb5da196ed9ea68973d5b",
          "md5": "9607b9626c378ff7bb0a62b493a6960a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-1.6.10.aar",
          "url": "nautilus-analytics-1.6.10.aar",
          "size": 145036,
          "sha512": "911a8e0bde5a201650040c15d2d185a76114b43afa61c7ca777b6a12ad9a122d9d870179a1959d0565500dbf90a1e6ad0560a75fcd6df60ce70aa200e51f653b",
          "sha256": "ac41ee6e94bc1ebd11a4980be72354d3ebcfc97125a6b0c9082dabe0c748bb99",
          "sha1": "ff1e079141540f72d2bcb5da196ed9ea68973d5b",
          "md5": "9607b9626c378ff7bb0a62b493a6960a"
        }
      ]
    }
  ]
}
