{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-campaign",
    "version": "1.14.0-alpha1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.14.0-alpha1"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-format",
          "version": {
            "requires": "1.14.0-alpha1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-campaign-1.14.0-alpha1.aar",
          "url": "nautilus-campaign-1.14.0-alpha1.aar",
          "size": 138599,
          "sha512": "56496375aa3cba2a4dd11cf13d8b3a15b6d505be53f61decdd90bf14bb84609329bed0291dcebe684ce7ef204e7ac2718fb22b4f23f68ac541cb6db9d00494b4",
          "sha256": "0d12b9d1a24d97f21494a50ce1f4a0a49126effc3eedfae0ce65cdfea770723f",
          "sha1": "60f67d45519cf3fe8b0e974456a17598a33595eb",
          "md5": "0d545a12358dbe248ca7e55be25a7f5b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.14.0-alpha1"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-format",
          "version": {
            "requires": "1.14.0-alpha1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-campaign-1.14.0-alpha1.aar",
          "url": "nautilus-campaign-1.14.0-alpha1.aar",
          "size": 138599,
          "sha512": "56496375aa3cba2a4dd11cf13d8b3a15b6d505be53f61decdd90bf14bb84609329bed0291dcebe684ce7ef204e7ac2718fb22b4f23f68ac541cb6db9d00494b4",
          "sha256": "0d12b9d1a24d97f21494a50ce1f4a0a49126effc3eedfae0ce65cdfea770723f",
          "sha1": "60f67d45519cf3fe8b0e974456a17598a33595eb",
          "md5": "0d545a12358dbe248ca7e55be25a7f5b"
        }
      ]
    }
  ]
}
