{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-config",
    "version": "1.15.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.15.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-config-1.15.3.aar",
          "url": "nautilus-config-1.15.3.aar",
          "size": 151029,
          "sha512": "c0e5e12f64999534f82228113eb231397a91a3e368a9b612e32346f72f124cff0d04f9b14e4ecb81690242070c98f378ecba814b81176d0ea8fcb6d52ad27f8f",
          "sha256": "76fadd866ecdce7a68ec4e821deb33ff6ad534f64a064b7c58882a9834f01bd7",
          "sha1": "5a7b9708b384625c14c2db8bcf40bb91339e12f3",
          "md5": "6319258f641c4d2bd72d67127dd84412"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.15.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-config-1.15.3.aar",
          "url": "nautilus-config-1.15.3.aar",
          "size": 151029,
          "sha512": "c0e5e12f64999534f82228113eb231397a91a3e368a9b612e32346f72f124cff0d04f9b14e4ecb81690242070c98f378ecba814b81176d0ea8fcb6d52ad27f8f",
          "sha256": "76fadd866ecdce7a68ec4e821deb33ff6ad534f64a064b7c58882a9834f01bd7",
          "sha1": "5a7b9708b384625c14c2db8bcf40bb91339e12f3",
          "md5": "6319258f641c4d2bd72d67127dd84412"
        }
      ]
    }
  ]
}
