{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-json",
    "version": "1.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-json-1.5.0.aar",
          "url": "nautilus-util-json-1.5.0.aar",
          "size": 11154,
          "sha512": "3333972183ac89b36400906f8add62a9fc20a4e34e781422ddd2a4fb08663e4f8542db9751da11a5cc559b51ccfb29561b99bebe007e32893de349080514d163",
          "sha256": "e6c0aef6f5badde9d80ebde71ebf2065bb9874c69a57ef35e448891245613589",
          "sha1": "5f8a531ab92a6a8d0c81978d2560688ccfbae95f",
          "md5": "7bf7c492a4e753dca01f522b5075fa5a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-json-1.5.0.aar",
          "url": "nautilus-util-json-1.5.0.aar",
          "size": 11154,
          "sha512": "3333972183ac89b36400906f8add62a9fc20a4e34e781422ddd2a4fb08663e4f8542db9751da11a5cc559b51ccfb29561b99bebe007e32893de349080514d163",
          "sha256": "e6c0aef6f5badde9d80ebde71ebf2065bb9874c69a57ef35e448891245613589",
          "sha1": "5f8a531ab92a6a8d0c81978d2560688ccfbae95f",
          "md5": "7bf7c492a4e753dca01f522b5075fa5a"
        }
      ]
    }
  ]
}
