{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-analytics",
    "version": "1.16.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.16.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-1.16.4.aar",
          "url": "nautilus-analytics-1.16.4.aar",
          "size": 165074,
          "sha512": "c45e2a4f1197a214ab1a58907f8e372274a0e212bc884326eac1c7f78f61095944bb109344b44add8e1e81825488ac4c0bd3a1288ec7aa71f0b5106f3940abfb",
          "sha256": "459f8296a71e0c7d26288bd263583e27164587aa0c5a65ad3d803a46c979b247",
          "sha1": "33105ddb3834ede61b2cb55a1a4b6411a10a2935",
          "md5": "f550e41c2207f69c7936f868e5a7e87f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.16.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-1.16.4.aar",
          "url": "nautilus-analytics-1.16.4.aar",
          "size": 165074,
          "sha512": "c45e2a4f1197a214ab1a58907f8e372274a0e212bc884326eac1c7f78f61095944bb109344b44add8e1e81825488ac4c0bd3a1288ec7aa71f0b5106f3940abfb",
          "sha256": "459f8296a71e0c7d26288bd263583e27164587aa0c5a65ad3d803a46c979b247",
          "sha1": "33105ddb3834ede61b2cb55a1a4b6411a10a2935",
          "md5": "f550e41c2207f69c7936f868e5a7e87f"
        }
      ]
    }
  ]
}
