{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-tools-cryptography",
    "version": "1.20.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-cryptography-1.20.0.aar",
          "url": "nautilus-tools-cryptography-1.20.0.aar",
          "size": 26336,
          "sha512": "2d60bfd2f2b31e4713a00542d074aab39f33a17d859f2deb5c7d7ea5ee67668cfa1318a5094bb106c72eff4dfc60794dfde5c4a8039e0cba50bfce96a393c4c6",
          "sha256": "71e1ae5d983fe35e43a7496fbafe82870881d06bdbcea3719d07b1d8fd091fb3",
          "sha1": "925f6239c69e1e0532b2f09fb13f4189b643381b",
          "md5": "8828701bbb23c5ebf3a0725e33a69b27"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-cryptography-1.20.0.aar",
          "url": "nautilus-tools-cryptography-1.20.0.aar",
          "size": 26336,
          "sha512": "2d60bfd2f2b31e4713a00542d074aab39f33a17d859f2deb5c7d7ea5ee67668cfa1318a5094bb106c72eff4dfc60794dfde5c4a8039e0cba50bfce96a393c4c6",
          "sha256": "71e1ae5d983fe35e43a7496fbafe82870881d06bdbcea3719d07b1d8fd091fb3",
          "sha1": "925f6239c69e1e0532b2f09fb13f4189b643381b",
          "md5": "8828701bbb23c5ebf3a0725e33a69b27"
        }
      ]
    }
  ]
}
