{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-tools-cryptography",
    "version": "1.7.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-cryptography-1.7.5.aar",
          "url": "nautilus-tools-cryptography-1.7.5.aar",
          "size": 26019,
          "sha512": "8b9d697773579a2c4d93a97412ed75e9040a5092435913aa2812bb764d33e146e34706182d29926876d1f679009cbe9dc46432542ff5279b04441d5779f36a32",
          "sha256": "bbf0e0ef08bca896b9a8775ef51dea174082e26520182327cc606e9aba873495",
          "sha1": "09553d5f1f59186918c3bd388ec49682ec594fc2",
          "md5": "0ffff96b6e2de942c4d0ffc9e5f1d884"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-cryptography-1.7.5.aar",
          "url": "nautilus-tools-cryptography-1.7.5.aar",
          "size": 26019,
          "sha512": "8b9d697773579a2c4d93a97412ed75e9040a5092435913aa2812bb764d33e146e34706182d29926876d1f679009cbe9dc46432542ff5279b04441d5779f36a32",
          "sha256": "bbf0e0ef08bca896b9a8775ef51dea174082e26520182327cc606e9aba873495",
          "sha1": "09553d5f1f59186918c3bd388ec49682ec594fc2",
          "md5": "0ffff96b6e2de942c4d0ffc9e5f1d884"
        }
      ]
    }
  ]
}
