{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-analytics",
    "version": "1.14.0-alpha1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.14.0-alpha1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-1.14.0-alpha1.aar",
          "url": "nautilus-analytics-1.14.0-alpha1.aar",
          "size": 173978,
          "sha512": "3b812bcd2d547619a4a1ecdd1628e585ebc087436a493db1f6f61f6c28d75da10b159fe1a6e84cd2b8cece859d9868b37881cb0b7fcde35f24f26e2af792b425",
          "sha256": "70556077e184a4a6d83fa6f0fff148b9e914d0899f7e5c1c4fdaa6e67f4fbd70",
          "sha1": "ad9be1fbd06488daec96b0e8b947ca863df2d563",
          "md5": "de91abca76924bccd50044d49ef9ff8f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.14.0-alpha1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-1.14.0-alpha1.aar",
          "url": "nautilus-analytics-1.14.0-alpha1.aar",
          "size": 173978,
          "sha512": "3b812bcd2d547619a4a1ecdd1628e585ebc087436a493db1f6f61f6c28d75da10b159fe1a6e84cd2b8cece859d9868b37881cb0b7fcde35f24f26e2af792b425",
          "sha256": "70556077e184a4a6d83fa6f0fff148b9e914d0899f7e5c1c4fdaa6e67f4fbd70",
          "sha1": "ad9be1fbd06488daec96b0e8b947ca863df2d563",
          "md5": "de91abca76924bccd50044d49ef9ff8f"
        }
      ]
    }
  ]
}
