{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-analytics",
    "version": "1.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-1.5.2.aar",
          "url": "nautilus-analytics-1.5.2.aar",
          "size": 141337,
          "sha512": "5e6a091ac1a407eadbac271fbeee4b2d1a3f0203080e0a8359486737b64e32ed5b2934e706989f8878eb051eee1c4cd0202c994fd380f20ebcd61e8e08f49edc",
          "sha256": "d03f9ba3b60334752852f393a8e610988e2b92015bb9b01fb5030fdfaa24f768",
          "sha1": "9dd979d2e2e961b41582427d47dcc77ae2648770",
          "md5": "9d1df7df67062dd385859a91e696f8bb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-1.5.2.aar",
          "url": "nautilus-analytics-1.5.2.aar",
          "size": 141337,
          "sha512": "5e6a091ac1a407eadbac271fbeee4b2d1a3f0203080e0a8359486737b64e32ed5b2934e706989f8878eb051eee1c4cd0202c994fd380f20ebcd61e8e08f49edc",
          "sha256": "d03f9ba3b60334752852f393a8e610988e2b92015bb9b01fb5030fdfaa24f768",
          "sha1": "9dd979d2e2e961b41582427d47dcc77ae2648770",
          "md5": "9d1df7df67062dd385859a91e696f8bb"
        }
      ]
    }
  ]
}
