{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-core",
    "version": "1.25.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.25.12"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-cryptography",
          "version": {
            "requires": "1.25.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-core-1.25.12.aar",
          "url": "nautilus-core-1.25.12.aar",
          "size": 85224,
          "sha512": "ac5386bf2c7a36b6dfacc01a935e0fdbfbb594fbd6330e582c78e62dce11a27bd5892b639c3107959637d7de3d40e58b781eecb143473372fa3fa006075ea3fb",
          "sha256": "71c14c3edd58526cfe32fb0795c9593acbc3a6029bc0810c51e94b97d468be84",
          "sha1": "2cab33cfd8f64b0a6a86830305025900348b6c9b",
          "md5": "0b54098662764fa2c2c4cecf5a0a4d46"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.18.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.25.12"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-cryptography",
          "version": {
            "requires": "1.25.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-core-1.25.12.aar",
          "url": "nautilus-core-1.25.12.aar",
          "size": 85224,
          "sha512": "ac5386bf2c7a36b6dfacc01a935e0fdbfbb594fbd6330e582c78e62dce11a27bd5892b639c3107959637d7de3d40e58b781eecb143473372fa3fa006075ea3fb",
          "sha256": "71c14c3edd58526cfe32fb0795c9593acbc3a6029bc0810c51e94b97d468be84",
          "sha1": "2cab33cfd8f64b0a6a86830305025900348b6c9b",
          "md5": "0b54098662764fa2c2c4cecf5a0a4d46"
        }
      ]
    }
  ]
}
