{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-imaging",
    "version": "1.7.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-network",
          "version": {
            "requires": "1.7.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-imaging-1.7.13.aar",
          "url": "nautilus-util-imaging-1.7.13.aar",
          "size": 11061,
          "sha512": "65c901e89aa22fac10500880cb3184b6a3eadbd59f2e5a15c233c2b01d27c7a5620deb82e90b8da05ef8c01e4b5b07ea29cec498151fbecab4bf633fadc67689",
          "sha256": "5a452d57926f1a7786d0cf4c278d19ceb6175c2b907d2900ceaad8cfc122597f",
          "sha1": "11445bf0c0956bf28a97bd6835bbad55429c82b6",
          "md5": "68814d37f7df4bac57c3490dfef7a5e1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-network",
          "version": {
            "requires": "1.7.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-imaging-1.7.13.aar",
          "url": "nautilus-util-imaging-1.7.13.aar",
          "size": 11061,
          "sha512": "65c901e89aa22fac10500880cb3184b6a3eadbd59f2e5a15c233c2b01d27c7a5620deb82e90b8da05ef8c01e4b5b07ea29cec498151fbecab4bf633fadc67689",
          "sha256": "5a452d57926f1a7786d0cf4c278d19ceb6175c2b907d2900ceaad8cfc122597f",
          "sha1": "11445bf0c0956bf28a97bd6835bbad55429c82b6",
          "md5": "68814d37f7df4bac57c3490dfef7a5e1"
        }
      ]
    }
  ]
}
