{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-imaging",
    "version": "1.17.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-network",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-imaging-1.17.0.aar",
          "url": "nautilus-util-imaging-1.17.0.aar",
          "size": 11290,
          "sha512": "55c629b84365c36b80280c9985694b33dac7219738c2d25e47fdefb0947d0e80d2c67297fc11184f8c3ae8366ebc2a972c81a55001a2fddb6a61b13244342e5a",
          "sha256": "a7c5e70a9430b7f9a4e254ac3a3a8b1794cf3db2785c442a40790248fc5b1c73",
          "sha1": "0f8588b9ede98fcc5d713096068bfa6fa223b0c5",
          "md5": "7c307ce63edb80b4effa007a7a2663df"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-network",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-imaging-1.17.0.aar",
          "url": "nautilus-util-imaging-1.17.0.aar",
          "size": 11290,
          "sha512": "55c629b84365c36b80280c9985694b33dac7219738c2d25e47fdefb0947d0e80d2c67297fc11184f8c3ae8366ebc2a972c81a55001a2fddb6a61b13244342e5a",
          "sha256": "a7c5e70a9430b7f9a4e254ac3a3a8b1794cf3db2785c442a40790248fc5b1c73",
          "sha1": "0f8588b9ede98fcc5d713096068bfa6fa223b0c5",
          "md5": "7c307ce63edb80b4effa007a7a2663df"
        }
      ]
    }
  ]
}
