{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-json",
    "version": "1.12.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-json-1.12.5.aar",
          "url": "nautilus-util-json-1.12.5.aar",
          "size": 11359,
          "sha512": "42e2c5b71e892f0b68a0dcb4c26be5effc55dda2665121d4e05687b0248e7c3c51794da36b086c911f78cf5f11fbffc5104b427932a4bd0ba4754357f21a5e1f",
          "sha256": "9010e3bd1e845488daf5bd8534850da4838e25a3b1e1039841887651b2bdc4e6",
          "sha1": "72f78434aa1faff241664feb660e9568038a992b",
          "md5": "f928f34defe4520421ffde83dab117ad"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-json-1.12.5.aar",
          "url": "nautilus-util-json-1.12.5.aar",
          "size": 11359,
          "sha512": "42e2c5b71e892f0b68a0dcb4c26be5effc55dda2665121d4e05687b0248e7c3c51794da36b086c911f78cf5f11fbffc5104b427932a4bd0ba4754357f21a5e1f",
          "sha256": "9010e3bd1e845488daf5bd8534850da4838e25a3b1e1039841887651b2bdc4e6",
          "sha1": "72f78434aa1faff241664feb660e9568038a992b",
          "md5": "f928f34defe4520421ffde83dab117ad"
        }
      ]
    }
  ]
}
