{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-code-image-providers",
    "version": "1.7.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.7.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-code-image-providers-1.7.5.aar",
          "url": "nautilus-code-image-providers-1.7.5.aar",
          "size": 12998,
          "sha512": "2cd96b6595b3e077b8a92e55c1f8384a6f5379d9070df97ade8925ab8f8d52809dc934b3cfeb645057232571dab110e0f3fefc540cd457a0676fe07431cb8249",
          "sha256": "9d50918f2a133aef4fd51c212dbcccf02f3903b9a8cce9abe92ab706942ed749",
          "sha1": "3cf9982a95b2b777b12f00ec29d252425541c005",
          "md5": "ddf6305e4823c7b9dcd5b292941daf74"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.7.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-code-image-providers-1.7.5.aar",
          "url": "nautilus-code-image-providers-1.7.5.aar",
          "size": 12998,
          "sha512": "2cd96b6595b3e077b8a92e55c1f8384a6f5379d9070df97ade8925ab8f8d52809dc934b3cfeb645057232571dab110e0f3fefc540cd457a0676fe07431cb8249",
          "sha256": "9d50918f2a133aef4fd51c212dbcccf02f3903b9a8cce9abe92ab706942ed749",
          "sha1": "3cf9982a95b2b777b12f00ec29d252425541c005",
          "md5": "ddf6305e4823c7b9dcd5b292941daf74"
        }
      ]
    }
  ]
}
