{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-code-reader",
    "version": "1.9.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.9.5"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-view",
          "version": {
            "requires": "1.9.5"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-code-reader-1.9.5.aar",
          "url": "nautilus-code-reader-1.9.5.aar",
          "size": 36007,
          "sha512": "f5514072dca0701cdfb7515059d4b8591b902ec48390b489802c6458717de2f90effde53c9ad649717ab4cf0ef118fa16e939a000b00f347eb31f04681c68593",
          "sha256": "9ad5e8c39ae92e110da0870f1fb254202431cd22076a0b5bcd32db62a86059f4",
          "sha1": "7f1786ea79d2294730613b7edbb3f156a024af1c",
          "md5": "35f0ea8acacacb465bdf405b5789de89"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "17.0.3"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.9.5"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-view",
          "version": {
            "requires": "1.9.5"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-code-reader-1.9.5.aar",
          "url": "nautilus-code-reader-1.9.5.aar",
          "size": 36007,
          "sha512": "f5514072dca0701cdfb7515059d4b8591b902ec48390b489802c6458717de2f90effde53c9ad649717ab4cf0ef118fa16e939a000b00f347eb31f04681c68593",
          "sha256": "9ad5e8c39ae92e110da0870f1fb254202431cd22076a0b5bcd32db62a86059f4",
          "sha1": "7f1786ea79d2294730613b7edbb3f156a024af1c",
          "md5": "35f0ea8acacacb465bdf405b5789de89"
        }
      ]
    }
  ]
}
