{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-map",
    "version": "1.25.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-map-1.25.6.aar",
          "url": "nautilus-util-map-1.25.6.aar",
          "size": 3860,
          "sha512": "dd71821dc6575f616c4dd3a242d2539d23f20f2b48db9c3ea7600963d2f1ef3cd0feebd2964f7e4d7c7f4a0f1b8dbae560a600edd959c4566a426a4e24be3b6e",
          "sha256": "ad80c1a990f3a405218c95f3aa5a963ca57f22397eb426f40ca4b02437d311d9",
          "sha1": "73f1b80a7adb0e2d3dca00d9cec5c7216e572267",
          "md5": "ed831adaac8ba8762951e7b4455efaa4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.9"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-maps",
          "version": {
            "requires": "20.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-map-1.25.6.aar",
          "url": "nautilus-util-map-1.25.6.aar",
          "size": 3860,
          "sha512": "dd71821dc6575f616c4dd3a242d2539d23f20f2b48db9c3ea7600963d2f1ef3cd0feebd2964f7e4d7c7f4a0f1b8dbae560a600edd959c4566a426a4e24be3b6e",
          "sha256": "ad80c1a990f3a405218c95f3aa5a963ca57f22397eb426f40ca4b02437d311d9",
          "sha1": "73f1b80a7adb0e2d3dca00d9cec5c7216e572267",
          "md5": "ed831adaac8ba8762951e7b4455efaa4"
        }
      ]
    }
  ]
}
