{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-shop",
    "version": "1.7.27-hotfix2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.7.27-hotfix2"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-analytics",
          "version": {
            "requires": "1.7.27-hotfix2"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-imaging",
          "version": {
            "requires": "1.7.27-hotfix2"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-geo",
          "version": {
            "requires": "1.7.27-hotfix2"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-config",
          "version": {
            "requires": "1.7.27-hotfix2"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-view",
          "version": {
            "requires": "1.7.27-hotfix2"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-format",
          "version": {
            "requires": "1.7.27-hotfix2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-shop-1.7.27-hotfix2.aar",
          "url": "nautilus-shop-1.7.27-hotfix2.aar",
          "size": 1157366,
          "sha512": "43693ab5d325676a40881c9a2ed09c0bc04862d2823714e49b30172a95e7f18908dffcf4280146fde330f6797037f528ace01df1de9e20b096ec64f3ada71bc1",
          "sha256": "57815ce034f039f151c8663f7ad7b54ee6cc4553889902d9f5af6b5b81682441",
          "sha1": "37705fd4777514475a0f69e6e82f8e9eaf7b86c7",
          "md5": "c778ec6dd1c4f3ac485be88ae41bc8e1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.7.27-hotfix2"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-analytics",
          "version": {
            "requires": "1.7.27-hotfix2"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-imaging",
          "version": {
            "requires": "1.7.27-hotfix2"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-geo",
          "version": {
            "requires": "1.7.27-hotfix2"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-config",
          "version": {
            "requires": "1.7.27-hotfix2"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-view",
          "version": {
            "requires": "1.7.27-hotfix2"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-format",
          "version": {
            "requires": "1.7.27-hotfix2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.3"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.4.3"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-maps",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-shop-1.7.27-hotfix2.aar",
          "url": "nautilus-shop-1.7.27-hotfix2.aar",
          "size": 1157366,
          "sha512": "43693ab5d325676a40881c9a2ed09c0bc04862d2823714e49b30172a95e7f18908dffcf4280146fde330f6797037f528ace01df1de9e20b096ec64f3ada71bc1",
          "sha256": "57815ce034f039f151c8663f7ad7b54ee6cc4553889902d9f5af6b5b81682441",
          "sha1": "37705fd4777514475a0f69e6e82f8e9eaf7b86c7",
          "md5": "c778ec6dd1c4f3ac485be88ae41bc8e1"
        }
      ]
    }
  ]
}
