{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-wovn",
    "version": "1.20.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-wovn-1.20.2.jar",
          "url": "nautilus-util-wovn-1.20.2.jar",
          "size": 4985,
          "sha512": "5cd44816c2ad3818a7c05b8875371541abe2f0b758638592860dec8f1e53762335a99abfae36df9e6a3b4b6e6948c08c70cddf46099686ace8423d1a47a8575b",
          "sha256": "9f08071bc542ce7c13cabf0c3e2ad28604afa881abbab632f10177125ace6363",
          "sha1": "f6305190dbfcd97502079a70a1067b67ad9ef100",
          "md5": "d1493f0b5266ffe0e166fbc7ae626c41"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-wovn-1.20.2.jar",
          "url": "nautilus-util-wovn-1.20.2.jar",
          "size": 4985,
          "sha512": "5cd44816c2ad3818a7c05b8875371541abe2f0b758638592860dec8f1e53762335a99abfae36df9e6a3b4b6e6948c08c70cddf46099686ace8423d1a47a8575b",
          "sha256": "9f08071bc542ce7c13cabf0c3e2ad28604afa881abbab632f10177125ace6363",
          "sha1": "f6305190dbfcd97502079a70a1067b67ad9ef100",
          "md5": "d1493f0b5266ffe0e166fbc7ae626c41"
        }
      ]
    }
  ]
}
