{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-core",
    "version": "1.21.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.21.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-cryptography",
          "version": {
            "requires": "1.21.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-core-1.21.0.aar",
          "url": "nautilus-core-1.21.0.aar",
          "size": 101434,
          "sha512": "2798d9a9499a869279cc58733c0612aaf65e85d78e128c53ecd00c7e3e614e79c1e77d8f13adddd18d4443663dfda792f2b1635d9fe6f0c08a02a89401d3aeb6",
          "sha256": "590213bb928b41aa41c2af4a33b82388a44cc39e9bd7b53ca7ede503aed4c8bf",
          "sha1": "661f854540e3e25b9a971410a29c2fa0bcdf0450",
          "md5": "5e76b62dc3020d3c95185b45384802da"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.21.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-cryptography",
          "version": {
            "requires": "1.21.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-core-1.21.0.aar",
          "url": "nautilus-core-1.21.0.aar",
          "size": 101434,
          "sha512": "2798d9a9499a869279cc58733c0612aaf65e85d78e128c53ecd00c7e3e614e79c1e77d8f13adddd18d4443663dfda792f2b1635d9fe6f0c08a02a89401d3aeb6",
          "sha256": "590213bb928b41aa41c2af4a33b82388a44cc39e9bd7b53ca7ede503aed4c8bf",
          "sha1": "661f854540e3e25b9a971410a29c2fa0bcdf0450",
          "md5": "5e76b62dc3020d3c95185b45384802da"
        }
      ]
    }
  ]
}
