{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-analytics",
    "version": "1.11.0-alpha1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.11.0-alpha1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-1.11.0-alpha1.aar",
          "url": "nautilus-analytics-1.11.0-alpha1.aar",
          "size": 173030,
          "sha512": "e7c7daec8b8c596eefc08899835615c4172afadfa4f51da67f6757a9d0c9b6a2b479d0e6d5e3bd546d3fafc4a7ebdf158c5cf9e597e23f819dc3e764f99c863e",
          "sha256": "3bec195036a6590f8b00216ab894243bc75d5e56968c56e2808b559a5e6d2725",
          "sha1": "204e3642613ef41dc8408e1dab1254c227107beb",
          "md5": "9c06d55ae0d2075a435bf385b54a859a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.11.0-alpha1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-1.11.0-alpha1.aar",
          "url": "nautilus-analytics-1.11.0-alpha1.aar",
          "size": 173030,
          "sha512": "e7c7daec8b8c596eefc08899835615c4172afadfa4f51da67f6757a9d0c9b6a2b479d0e6d5e3bd546d3fafc4a7ebdf158c5cf9e597e23f819dc3e764f99c863e",
          "sha256": "3bec195036a6590f8b00216ab894243bc75d5e56968c56e2808b559a5e6d2725",
          "sha1": "204e3642613ef41dc8408e1dab1254c227107beb",
          "md5": "9c06d55ae0d2075a435bf385b54a859a"
        }
      ]
    }
  ]
}
