{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-imaging",
    "version": "1.9.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-network",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-imaging-1.9.3.aar",
          "url": "nautilus-util-imaging-1.9.3.aar",
          "size": 11262,
          "sha512": "778d2293f11bffb684d154817a7fef6e3c46890b00338b89743ea319a9c47e6050f3bddf4a82717a2cc08ee82fa94bcb88f95e1dc501f83448760f4c4fcb314e",
          "sha256": "4a90547ab7ce485e046715d9e7e9ea2dd174b64353cf11152b26a0767118c78f",
          "sha1": "dd2426cc670a1ae3ce0971ae6c84e0e1ebe12755",
          "md5": "57135d8dc1a7cde61a9fc70d0e18be22"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-network",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-imaging-1.9.3.aar",
          "url": "nautilus-util-imaging-1.9.3.aar",
          "size": 11262,
          "sha512": "778d2293f11bffb684d154817a7fef6e3c46890b00338b89743ea319a9c47e6050f3bddf4a82717a2cc08ee82fa94bcb88f95e1dc501f83448760f4c4fcb314e",
          "sha256": "4a90547ab7ce485e046715d9e7e9ea2dd174b64353cf11152b26a0767118c78f",
          "sha1": "dd2426cc670a1ae3ce0971ae6c84e0e1ebe12755",
          "md5": "57135d8dc1a7cde61a9fc70d0e18be22"
        }
      ]
    }
  ]
}
