{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-core",
    "version": "1.19.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.19.23"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-cryptography",
          "version": {
            "requires": "1.19.23"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-core-1.19.23.aar",
          "url": "nautilus-core-1.19.23.aar",
          "size": 100644,
          "sha512": "7a015a11e55b36f5246b3686c3afd3279848c83316aebd6e1072e00a714858c84c52d39971a41beb7e6699ae74407483196ac29d69a485146f6626dbb34c333c",
          "sha256": "b90d9f229fdc9c6546f9f43b456310e550d97f4747f67b8b7ee970d14867bab9",
          "sha1": "1474fe71837056186a07d07763aeb632f9882629",
          "md5": "6a88a5285223cbe670660c04e915f208"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.19.23"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-cryptography",
          "version": {
            "requires": "1.19.23"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-core-1.19.23.aar",
          "url": "nautilus-core-1.19.23.aar",
          "size": 100644,
          "sha512": "7a015a11e55b36f5246b3686c3afd3279848c83316aebd6e1072e00a714858c84c52d39971a41beb7e6699ae74407483196ac29d69a485146f6626dbb34c333c",
          "sha256": "b90d9f229fdc9c6546f9f43b456310e550d97f4747f67b8b7ee970d14867bab9",
          "sha1": "1474fe71837056186a07d07763aeb632f9882629",
          "md5": "6a88a5285223cbe670660c04e915f208"
        }
      ]
    }
  ]
}
