{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-analytics",
    "version": "1.9.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.9.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-1.9.8.aar",
          "url": "nautilus-analytics-1.9.8.aar",
          "size": 173036,
          "sha512": "dd0f27c49ed16a54b1de0cf8787f7edc2d793ddf9c93b061453e33b6f8ae452bdf06418c71b6142868db219fa62abec2350cef5cbc38f1ca938b86e311073d08",
          "sha256": "2d427c25330f8458350da613a61467909f3b5af4b5bcc225cd5b2f2703d80ee5",
          "sha1": "35824f349453d2b703633dedeaaf31605cfcccd2",
          "md5": "a699ed809647e49d4012450309e87b5a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.9.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-1.9.8.aar",
          "url": "nautilus-analytics-1.9.8.aar",
          "size": 173036,
          "sha512": "dd0f27c49ed16a54b1de0cf8787f7edc2d793ddf9c93b061453e33b6f8ae452bdf06418c71b6142868db219fa62abec2350cef5cbc38f1ca938b86e311073d08",
          "sha256": "2d427c25330f8458350da613a61467909f3b5af4b5bcc225cd5b2f2703d80ee5",
          "sha1": "35824f349453d2b703633dedeaaf31605cfcccd2",
          "md5": "a699ed809647e49d4012450309e87b5a"
        }
      ]
    }
  ]
}
