{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-analytics",
    "version": "1.5.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.5.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-1.5.5.aar",
          "url": "nautilus-analytics-1.5.5.aar",
          "size": 144329,
          "sha512": "438cf4a736f7fda4828164265b8caa2334904d80a9590b8bb8d0535efb30ed6c88c5e2b9fb8c413fdac062f279f956074d2269df501ec18712aba8778f2bbdc6",
          "sha256": "907a13319c1cffbe4500e3deb9d391e97ba2cdab1639bda603c2fb8b24ef0dc1",
          "sha1": "19d08772f3985bad74c4bfd2faff728434276c9e",
          "md5": "44c1ab3e13378c3879f4c06a5e27d289"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.5.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-1.5.5.aar",
          "url": "nautilus-analytics-1.5.5.aar",
          "size": 144329,
          "sha512": "438cf4a736f7fda4828164265b8caa2334904d80a9590b8bb8d0535efb30ed6c88c5e2b9fb8c413fdac062f279f956074d2269df501ec18712aba8778f2bbdc6",
          "sha256": "907a13319c1cffbe4500e3deb9d391e97ba2cdab1639bda603c2fb8b24ef0dc1",
          "sha1": "19d08772f3985bad74c4bfd2faff728434276c9e",
          "md5": "44c1ab3e13378c3879f4c06a5e27d289"
        }
      ]
    }
  ]
}
