{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-format",
    "version": "1.6.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.6.8.aar",
          "url": "nautilus-util-format-1.6.8.aar",
          "size": 8802,
          "sha512": "e10a7f1edeb65574a3d0e862f446d72dd770fcbef1b2401abba492a7abb06884101b9ffb5bfbed4af921de635698a34e9022a41793173b042e425d664b415b8f",
          "sha256": "f38edf990436581528c2fa2140ecd7c88df7583a2042e5663ecae69c7c1fb912",
          "sha1": "b9d663d206e071cbcc3ca2e4e3325f85334a4605",
          "md5": "baba4d176866535e67c1dbfdbde22a14"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.6.8.aar",
          "url": "nautilus-util-format-1.6.8.aar",
          "size": 8802,
          "sha512": "e10a7f1edeb65574a3d0e862f446d72dd770fcbef1b2401abba492a7abb06884101b9ffb5bfbed4af921de635698a34e9022a41793173b042e425d664b415b8f",
          "sha256": "f38edf990436581528c2fa2140ecd7c88df7583a2042e5663ecae69c7c1fb912",
          "sha1": "b9d663d206e071cbcc3ca2e4e3325f85334a4605",
          "md5": "baba4d176866535e67c1dbfdbde22a14"
        }
      ]
    }
  ]
}
