{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-code-reader",
    "version": "1.25.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.25.13"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-view",
          "version": {
            "requires": "1.25.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "9.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-code-reader-1.25.13.aar",
          "url": "nautilus-code-reader-1.25.13.aar",
          "size": 25957,
          "sha512": "f955f50ec179e11c65da6a6736494ffd4766dc924f93d5277cf12c7e5163f4af3b7b2523e7788eec6cf9095ed650104e6c86a0a79547eb8c7e81d347c791b0fa",
          "sha256": "845654d3982c53f50044380c8e88a60d76c2501b3d53e05675cc499f7b9e3044",
          "sha1": "256ca19438d709047c4feba5ef2621e4051c762f",
          "md5": "7de3d37e5dd6430be8728b31e1f6c563"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.9"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "17.3.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.25.13"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-view",
          "version": {
            "requires": "1.25.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "9.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-code-reader-1.25.13.aar",
          "url": "nautilus-code-reader-1.25.13.aar",
          "size": 25957,
          "sha512": "f955f50ec179e11c65da6a6736494ffd4766dc924f93d5277cf12c7e5163f4af3b7b2523e7788eec6cf9095ed650104e6c86a0a79547eb8c7e81d347c791b0fa",
          "sha256": "845654d3982c53f50044380c8e88a60d76c2501b3d53e05675cc499f7b9e3044",
          "sha1": "256ca19438d709047c4feba5ef2621e4051c762f",
          "md5": "7de3d37e5dd6430be8728b31e1f6c563"
        }
      ]
    }
  ]
}
