{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-imaging",
    "version": "1.12.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-network",
          "version": {
            "requires": "1.12.11"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-imaging-1.12.11.aar",
          "url": "nautilus-util-imaging-1.12.11.aar",
          "size": 11256,
          "sha512": "d825aabe2822b89ef7d8f89f19f191e303e24f58fac88dd32bb5b33f094caa06bae592e9eda39601f2c9c9ec00d32ed73dfaefaf815df2996c30f89d79988958",
          "sha256": "a33a0e387b1d4bccc9d122522bb6138bae46e5a511b851b3ce3d7e6f26f86f93",
          "sha1": "1034b33c635168c96c022f76e86cf2c99922300d",
          "md5": "27fc7953d005b4e1dcda907f328ac19e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-network",
          "version": {
            "requires": "1.12.11"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-imaging-1.12.11.aar",
          "url": "nautilus-util-imaging-1.12.11.aar",
          "size": 11256,
          "sha512": "d825aabe2822b89ef7d8f89f19f191e303e24f58fac88dd32bb5b33f094caa06bae592e9eda39601f2c9c9ec00d32ed73dfaefaf815df2996c30f89d79988958",
          "sha256": "a33a0e387b1d4bccc9d122522bb6138bae46e5a511b851b3ce3d7e6f26f86f93",
          "sha1": "1034b33c635168c96c022f76e86cf2c99922300d",
          "md5": "27fc7953d005b4e1dcda907f328ac19e"
        }
      ]
    }
  ]
}
