{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-core",
    "version": "1.7.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.7.14"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-cryptography",
          "version": {
            "requires": "1.7.14"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-core-1.7.14.aar",
          "url": "nautilus-core-1.7.14.aar",
          "size": 116059,
          "sha512": "dd80da03a10e4f08cf029e22942367919a12241c000050faf46fac188ddbf8f5b317c07c54b92164598acee241c307a4acad5823bfe3969fffceeed8ff0aa540",
          "sha256": "df276c5a39effe8522701bcede9843d358498608a5aaa66392654bf08ec9de83",
          "sha1": "c8300e8982a82680fc3b7e32192d6ab8db5c996c",
          "md5": "a49804babcae6703719f884afa059a71"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.7.14"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-cryptography",
          "version": {
            "requires": "1.7.14"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-core-1.7.14.aar",
          "url": "nautilus-core-1.7.14.aar",
          "size": 116059,
          "sha512": "dd80da03a10e4f08cf029e22942367919a12241c000050faf46fac188ddbf8f5b317c07c54b92164598acee241c307a4acad5823bfe3969fffceeed8ff0aa540",
          "sha256": "df276c5a39effe8522701bcede9843d358498608a5aaa66392654bf08ec9de83",
          "sha1": "c8300e8982a82680fc3b7e32192d6ab8db5c996c",
          "md5": "a49804babcae6703719f884afa059a71"
        }
      ]
    }
  ]
}
