{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-imaging",
    "version": "1.7.30",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-network",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-imaging-1.7.30.aar",
          "url": "nautilus-util-imaging-1.7.30.aar",
          "size": 11064,
          "sha512": "28b39b5cbf2faa151e66aa353543f0bd2e9b0f0a3afa86d8f00c41d83cf815e2dd3b06d8e9211046b1ca3368219fb0b993c2c61828b0693d8d2452a48605274e",
          "sha256": "4e35870ed1e1ea9e53dc898154072d54f8b779437dc5b973fa4a393a6d4ecd03",
          "sha1": "7bded428c10dd4d074ff1add72f624069584ebe1",
          "md5": "f8d68377d54e40f3f53e88499199f0d9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-network",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-imaging-1.7.30.aar",
          "url": "nautilus-util-imaging-1.7.30.aar",
          "size": 11064,
          "sha512": "28b39b5cbf2faa151e66aa353543f0bd2e9b0f0a3afa86d8f00c41d83cf815e2dd3b06d8e9211046b1ca3368219fb0b993c2c61828b0693d8d2452a48605274e",
          "sha256": "4e35870ed1e1ea9e53dc898154072d54f8b779437dc5b973fa4a393a6d4ecd03",
          "sha1": "7bded428c10dd4d074ff1add72f624069584ebe1",
          "md5": "f8d68377d54e40f3f53e88499199f0d9"
        }
      ]
    }
  ]
}
