{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-tools-cryptography",
    "version": "1.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-cryptography-1.5.2.aar",
          "url": "nautilus-tools-cryptography-1.5.2.aar",
          "size": 18724,
          "sha512": "7d52e3f5f209279278bbb31a3626891f493bef0cbf72d40c063cb2ec15b8a09fc74b11f1a594b9d9078f3f663efc5d5e25f6af3280b542921eb93da22ad9e2da",
          "sha256": "8e6078a531bd1f0c7d095f81c15d7a9bd25071a139c81ad1be7269597a841f5a",
          "sha1": "f102624f87434414347898f2095ef5d032dac891",
          "md5": "7d2dd27bf46cfa658fe095e22812f1ab"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-cryptography-1.5.2.aar",
          "url": "nautilus-tools-cryptography-1.5.2.aar",
          "size": 18724,
          "sha512": "7d52e3f5f209279278bbb31a3626891f493bef0cbf72d40c063cb2ec15b8a09fc74b11f1a594b9d9078f3f663efc5d5e25f6af3280b542921eb93da22ad9e2da",
          "sha256": "8e6078a531bd1f0c7d095f81c15d7a9bd25071a139c81ad1be7269597a841f5a",
          "sha1": "f102624f87434414347898f2095ef5d032dac891",
          "md5": "7d2dd27bf46cfa658fe095e22812f1ab"
        }
      ]
    }
  ]
}
