{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-network",
    "version": "1.16.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.16.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.16.4.aar",
          "url": "nautilus-util-network-1.16.4.aar",
          "size": 23276,
          "sha512": "ea69ef3922fca7844773a7960be03573f55642c76c54ee5008a040da266a20c8f7059e13d3c87f4aa823ba36401961792168369ba0a28aec2ddd6120a1b306a4",
          "sha256": "c2453d9f89d6785aef95ef963058467c451e780cddf93edbf0673a1277d3ad61",
          "sha1": "3425324154d77f60d1c6cb1a8c969da4b9eb1887",
          "md5": "8015479d79b3343cb2aa1914dbf05283"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.16.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.16.4.aar",
          "url": "nautilus-util-network-1.16.4.aar",
          "size": 23276,
          "sha512": "ea69ef3922fca7844773a7960be03573f55642c76c54ee5008a040da266a20c8f7059e13d3c87f4aa823ba36401961792168369ba0a28aec2ddd6120a1b306a4",
          "sha256": "c2453d9f89d6785aef95ef963058467c451e780cddf93edbf0673a1277d3ad61",
          "sha1": "3425324154d77f60d1c6cb1a8c969da4b9eb1887",
          "md5": "8015479d79b3343cb2aa1914dbf05283"
        }
      ]
    }
  ]
}
