{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-format",
    "version": "1.18.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.18.0.aar",
          "url": "nautilus-util-format-1.18.0.aar",
          "size": 8967,
          "sha512": "b84504a4c67505c67851c547b38b801f808342f092493f3b34dca939790da97babb19c07da4e6a49930e26b674214a319a7e2d91a0a8a8f4adf7809a3fd6ee5e",
          "sha256": "84cecfd20bcac3cc9c88b3dbbc4535e9b0317fa2c2e5e5441be0950d8dd00d3d",
          "sha1": "8a49b754d12487a4d6be3d2ddc91cefeba8caad3",
          "md5": "eb3e115aa520c8ddc6fee605c87c92f3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.18.0.aar",
          "url": "nautilus-util-format-1.18.0.aar",
          "size": 8967,
          "sha512": "b84504a4c67505c67851c547b38b801f808342f092493f3b34dca939790da97babb19c07da4e6a49930e26b674214a319a7e2d91a0a8a8f4adf7809a3fd6ee5e",
          "sha256": "84cecfd20bcac3cc9c88b3dbbc4535e9b0317fa2c2e5e5441be0950d8dd00d3d",
          "sha1": "8a49b754d12487a4d6be3d2ddc91cefeba8caad3",
          "md5": "eb3e115aa520c8ddc6fee605c87c92f3"
        }
      ]
    }
  ]
}
