{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-core",
    "version": "1.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-cryptography",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-core-1.6.0.aar",
          "url": "nautilus-core-1.6.0.aar",
          "size": 85596,
          "sha512": "cbcdd98da9f414063168956015dd237fce249b1ee76b27e3170b04eaf5cbd19d1d847ea4f0956986581dd29692aedd464a50291b2a313f28a90b38cc42a77a26",
          "sha256": "4141f86bb7c86a082514a5c98ff25011b434c6d2c300c1ba496710dd375d8ce1",
          "sha1": "651c45b5981da0c267d7f20ce8ebfa49eee5133d",
          "md5": "b982b981ff04227492ab200070e15034"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-cryptography",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-core-1.6.0.aar",
          "url": "nautilus-core-1.6.0.aar",
          "size": 85596,
          "sha512": "cbcdd98da9f414063168956015dd237fce249b1ee76b27e3170b04eaf5cbd19d1d847ea4f0956986581dd29692aedd464a50291b2a313f28a90b38cc42a77a26",
          "sha256": "4141f86bb7c86a082514a5c98ff25011b434c6d2c300c1ba496710dd375d8ce1",
          "sha1": "651c45b5981da0c267d7f20ce8ebfa49eee5133d",
          "md5": "b982b981ff04227492ab200070e15034"
        }
      ]
    }
  ]
}
