{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-code-image-providers",
    "version": "1.7.9-hotfix1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.7.9-hotfix1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-code-image-providers-1.7.9-hotfix1.aar",
          "url": "nautilus-code-image-providers-1.7.9-hotfix1.aar",
          "size": 12998,
          "sha512": "4f5ae1d909e752089b24b7921141d20f7ad4c80be11203a9651c0a5e4903543ad2e00b4d45bf15e1ba10257c755d3902dfba5f984b7a4458401e94f53f6f25b2",
          "sha256": "35f594850341c6b395f172cb0632b1b6af224a20efffa9c32438550ea6fe98e5",
          "sha1": "94405b78f53fc99a4b26ee298851b45557a9093e",
          "md5": "776d9b57ae245fa070125b1423ca10dd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.7.9-hotfix1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-code-image-providers-1.7.9-hotfix1.aar",
          "url": "nautilus-code-image-providers-1.7.9-hotfix1.aar",
          "size": 12998,
          "sha512": "4f5ae1d909e752089b24b7921141d20f7ad4c80be11203a9651c0a5e4903543ad2e00b4d45bf15e1ba10257c755d3902dfba5f984b7a4458401e94f53f6f25b2",
          "sha256": "35f594850341c6b395f172cb0632b1b6af224a20efffa9c32438550ea6fe98e5",
          "sha1": "94405b78f53fc99a4b26ee298851b45557a9093e",
          "md5": "776d9b57ae245fa070125b1423ca10dd"
        }
      ]
    }
  ]
}
