{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-format",
    "version": "1.12.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.12.1.aar",
          "url": "nautilus-util-format-1.12.1.aar",
          "size": 8942,
          "sha512": "1c88620c62ad779f3781d90177b4d6ba87e41eb51869f5ffd2bfb47b4f2c59fdc846ebfbc715ad71efaf6ea99841578c38d17c615a0969da57509123ee23e688",
          "sha256": "3685ed22952d8b3d092bf04f7b6d9a74c2b6f9e118ca2d2a9f7dbff395c09224",
          "sha1": "379daec914fd2249574fdf62759927a5505fa02e",
          "md5": "e07f52f1cd1ed535b607d61d28f9a861"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.12.1.aar",
          "url": "nautilus-util-format-1.12.1.aar",
          "size": 8942,
          "sha512": "1c88620c62ad779f3781d90177b4d6ba87e41eb51869f5ffd2bfb47b4f2c59fdc846ebfbc715ad71efaf6ea99841578c38d17c615a0969da57509123ee23e688",
          "sha256": "3685ed22952d8b3d092bf04f7b6d9a74c2b6f9e118ca2d2a9f7dbff395c09224",
          "sha1": "379daec914fd2249574fdf62759927a5505fa02e",
          "md5": "e07f52f1cd1ed535b607d61d28f9a861"
        }
      ]
    }
  ]
}
