{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-network",
    "version": "1.15.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.15.0.aar",
          "url": "nautilus-util-network-1.15.0.aar",
          "size": 23281,
          "sha512": "2810b2f0f807b2ab65ca78cc78cd13df31a505c29302338dd66587c153d6f216f8e3329b5295417c1c853799f47fa1956739cd1396395cc0c2b11838c76d77ee",
          "sha256": "08de3689c453e97ce720d86ee22f3be1ecf349c9ccc3b888136e8bf720a50380",
          "sha1": "36a6949555d4e41bf88d0d15aa826aca57530efa",
          "md5": "29fdf3655381935f717b83f941f52f0f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.15.0.aar",
          "url": "nautilus-util-network-1.15.0.aar",
          "size": 23281,
          "sha512": "2810b2f0f807b2ab65ca78cc78cd13df31a505c29302338dd66587c153d6f216f8e3329b5295417c1c853799f47fa1956739cd1396395cc0c2b11838c76d77ee",
          "sha256": "08de3689c453e97ce720d86ee22f3be1ecf349c9ccc3b888136e8bf720a50380",
          "sha1": "36a6949555d4e41bf88d0d15aa826aca57530efa",
          "md5": "29fdf3655381935f717b83f941f52f0f"
        }
      ]
    }
  ]
}
