{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-format",
    "version": "1.19.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.19.21.aar",
          "url": "nautilus-util-format-1.19.21.aar",
          "size": 8974,
          "sha512": "760665cf50a30b0b5668b0c7505a864f18cab5e25ae1e57132d26012d61f18610afac2779826c25477a0838b041282c679357565b0e850a9256c1ed1da344321",
          "sha256": "51b85a6d5ab594b4b6434e7907dc41d232f4e824ecd5f2295a72ea73afd9fc26",
          "sha1": "bc848f4e1aa1f252fdf3d57a679dbfdcb0fafee6",
          "md5": "0c5242cc416e36b7a77008245240a1fa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.19.21.aar",
          "url": "nautilus-util-format-1.19.21.aar",
          "size": 8974,
          "sha512": "760665cf50a30b0b5668b0c7505a864f18cab5e25ae1e57132d26012d61f18610afac2779826c25477a0838b041282c679357565b0e850a9256c1ed1da344321",
          "sha256": "51b85a6d5ab594b4b6434e7907dc41d232f4e824ecd5f2295a72ea73afd9fc26",
          "sha1": "bc848f4e1aa1f252fdf3d57a679dbfdcb0fafee6",
          "md5": "0c5242cc416e36b7a77008245240a1fa"
        }
      ]
    }
  ]
}
