{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-network",
    "version": "1.9.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.9.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.9.7.aar",
          "url": "nautilus-util-network-1.9.7.aar",
          "size": 23247,
          "sha512": "dc4f6ca8f27f76b6cd3086b538a2dc6f3c4bda95ed8a288cd91cae94b48b9d305235177a7eaab2c2b2cb37b60f1cb16b30ae81b3066c43f67d0c524b0346b195",
          "sha256": "5c46eebbe159b967b0ef3d0c8104135ddd6b9179bf52660f7994a3a55fa4773f",
          "sha1": "73089dd08fb2107f4656cf7abfa56b7b9478860b",
          "md5": "934cd39bbee6c1ee8ccc04437109b523"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.9.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.9.7.aar",
          "url": "nautilus-util-network-1.9.7.aar",
          "size": 23247,
          "sha512": "dc4f6ca8f27f76b6cd3086b538a2dc6f3c4bda95ed8a288cd91cae94b48b9d305235177a7eaab2c2b2cb37b60f1cb16b30ae81b3066c43f67d0c524b0346b195",
          "sha256": "5c46eebbe159b967b0ef3d0c8104135ddd6b9179bf52660f7994a3a55fa4773f",
          "sha1": "73089dd08fb2107f4656cf7abfa56b7b9478860b",
          "md5": "934cd39bbee6c1ee8ccc04437109b523"
        }
      ]
    }
  ]
}
