{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-format",
    "version": "1.19.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.19.19.aar",
          "url": "nautilus-util-format-1.19.19.aar",
          "size": 8979,
          "sha512": "141015ba797995ef57256879f004aa89c45bfe0c5463418ae5075ed6942af5e75bc988a384e99178638bd6b273ed0e2481c4818f854c3bf46624e88faac62076",
          "sha256": "1a57c122ffbc91a75df1eef11e2765615505da0e64e7ec2a9f7b15011ef6cdfb",
          "sha1": "7fe2dadfb42018613c9477d8127c1ef2644af280",
          "md5": "8635c87f06133e7812c5b18e7007d74e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.19.19.aar",
          "url": "nautilus-util-format-1.19.19.aar",
          "size": 8979,
          "sha512": "141015ba797995ef57256879f004aa89c45bfe0c5463418ae5075ed6942af5e75bc988a384e99178638bd6b273ed0e2481c4818f854c3bf46624e88faac62076",
          "sha256": "1a57c122ffbc91a75df1eef11e2765615505da0e64e7ec2a9f7b15011ef6cdfb",
          "sha1": "7fe2dadfb42018613c9477d8127c1ef2644af280",
          "md5": "8635c87f06133e7812c5b18e7007d74e"
        }
      ]
    }
  ]
}
