{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-config",
    "version": "1.7.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-config-1.7.22.aar",
          "url": "nautilus-config-1.7.22.aar",
          "size": 143888,
          "sha512": "8666eb714ec66a213dacddd988cb52beb60b7446d29d71573b9fc3db4863bc37bb00092a401cffd70d480aab430505171e9f1959ebdadbdea31894af7fc0339d",
          "sha256": "e3e2589ea645433a267f923d06cc345309729d7aaeab13d49b64852f3610297a",
          "sha1": "af13941a2f02f53151d3f0f40e8e03b1d45fa7f1",
          "md5": "942332124a2533af90fce6e6d060a8d4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.3"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.4.3"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-config-1.7.22.aar",
          "url": "nautilus-config-1.7.22.aar",
          "size": 143888,
          "sha512": "8666eb714ec66a213dacddd988cb52beb60b7446d29d71573b9fc3db4863bc37bb00092a401cffd70d480aab430505171e9f1959ebdadbdea31894af7fc0339d",
          "sha256": "e3e2589ea645433a267f923d06cc345309729d7aaeab13d49b64852f3610297a",
          "sha1": "af13941a2f02f53151d3f0f40e8e03b1d45fa7f1",
          "md5": "942332124a2533af90fce6e6d060a8d4"
        }
      ]
    }
  ]
}
