{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-stamp",
    "version": "1.7.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.7.24"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-config",
          "version": {
            "requires": "1.7.24"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-format",
          "version": {
            "requires": "1.7.24"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-stamp-1.7.24.aar",
          "url": "nautilus-stamp-1.7.24.aar",
          "size": 220559,
          "sha512": "7a0f3befe5add49a40769cbab281aaee6469144c9ad5dec4919e0ccc22dfbd26785d4bee2ed1947ae40d8ab212bd944a969927d623969bc1d57829dd8872851f",
          "sha256": "a6ae2a1836f65c1cb779faecb2719ad16f5ddb49fc839118370a6858749c98b1",
          "sha1": "2da12d052f0f7da3e3790e674ca14816c922b175",
          "md5": "d6c5bc7bbac23e9d5a7b3a9d4cfea927"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.7.24"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-config",
          "version": {
            "requires": "1.7.24"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-format",
          "version": {
            "requires": "1.7.24"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.3"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.4.3"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-maps",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-stamp-1.7.24.aar",
          "url": "nautilus-stamp-1.7.24.aar",
          "size": 220559,
          "sha512": "7a0f3befe5add49a40769cbab281aaee6469144c9ad5dec4919e0ccc22dfbd26785d4bee2ed1947ae40d8ab212bd944a969927d623969bc1d57829dd8872851f",
          "sha256": "a6ae2a1836f65c1cb779faecb2719ad16f5ddb49fc839118370a6858749c98b1",
          "sha1": "2da12d052f0f7da3e3790e674ca14816c922b175",
          "md5": "d6c5bc7bbac23e9d5a7b3a9d4cfea927"
        }
      ]
    }
  ]
}
