{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-config",
    "version": "1.19.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.19.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-config-1.19.9.aar",
          "url": "nautilus-config-1.19.9.aar",
          "size": 145671,
          "sha512": "77a51f69b8490e5caef78deda308028aad2ef42efef0ee476268c64c954539072b0416031f8e5d95f9e56455766f4e312173f59f99e8e567a2711e77f89c7e6b",
          "sha256": "c1472ebf30878d8d8be2dc801c57f5ad65e9fb9eed33b19204b24a4952408286",
          "sha1": "772055fae1efaf0b8d247e50a5bb52cee7be7b4b",
          "md5": "fbf9f94bb804e83bc1ec321a120f416f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.19.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-config-1.19.9.aar",
          "url": "nautilus-config-1.19.9.aar",
          "size": 145671,
          "sha512": "77a51f69b8490e5caef78deda308028aad2ef42efef0ee476268c64c954539072b0416031f8e5d95f9e56455766f4e312173f59f99e8e567a2711e77f89c7e6b",
          "sha256": "c1472ebf30878d8d8be2dc801c57f5ad65e9fb9eed33b19204b24a4952408286",
          "sha1": "772055fae1efaf0b8d247e50a5bb52cee7be7b4b",
          "md5": "fbf9f94bb804e83bc1ec321a120f416f"
        }
      ]
    }
  ]
}
