{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-server-time",
    "version": "1.19.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.19.25"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-network",
          "version": {
            "requires": "1.19.25"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-config",
          "version": {
            "requires": "1.19.25"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-server-time-1.19.25.aar",
          "url": "nautilus-server-time-1.19.25.aar",
          "size": 64406,
          "sha512": "ccca14ee5398e0418a15a089782cc1e64e6d6c000bc6baffde6fa911402fed7204646a3695842c3bb7de5aa2541e64774e3a3f53eaf3e44571285190b9242543",
          "sha256": "3b57c154af2735e2fe96814fb8ea3ce0e28261dd979fba3fad49fec7b6f81fa6",
          "sha1": "51688d65b79b8cfbf71c05c438a44f6d7efd246c",
          "md5": "289bcef0509a1335335c6095e011c378"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.19.25"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-network",
          "version": {
            "requires": "1.19.25"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-config",
          "version": {
            "requires": "1.19.25"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-server-time-1.19.25.aar",
          "url": "nautilus-server-time-1.19.25.aar",
          "size": 64406,
          "sha512": "ccca14ee5398e0418a15a089782cc1e64e6d6c000bc6baffde6fa911402fed7204646a3695842c3bb7de5aa2541e64774e3a3f53eaf3e44571285190b9242543",
          "sha256": "3b57c154af2735e2fe96814fb8ea3ce0e28261dd979fba3fad49fec7b6f81fa6",
          "sha1": "51688d65b79b8cfbf71c05c438a44f6d7efd246c",
          "md5": "289bcef0509a1335335c6095e011c378"
        }
      ]
    }
  ]
}
