{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-tools-logging",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-logging-1.10.0.aar",
          "url": "nautilus-tools-logging-1.10.0.aar",
          "size": 19640,
          "sha512": "8bb17cae6885020013edd62bb4a48d9a862a27dba4e2866986ceecdcc8b1475a5121d8e7258faf7a225162200b331a14fe40a03e41961d948e835f6b6cda81ad",
          "sha256": "82ab64caa68e7f368b55fc6332599b9a460bca9603f734c5b67d27d5b75a1c0d",
          "sha1": "9d4d7539395d832defa3282197fdde59a9b28fe9",
          "md5": "6d29a543296db550fc6647384ebe5934"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-logging-1.10.0.aar",
          "url": "nautilus-tools-logging-1.10.0.aar",
          "size": 19640,
          "sha512": "8bb17cae6885020013edd62bb4a48d9a862a27dba4e2866986ceecdcc8b1475a5121d8e7258faf7a225162200b331a14fe40a03e41961d948e835f6b6cda81ad",
          "sha256": "82ab64caa68e7f368b55fc6332599b9a460bca9603f734c5b67d27d5b75a1c0d",
          "sha1": "9d4d7539395d832defa3282197fdde59a9b28fe9",
          "md5": "6d29a543296db550fc6647384ebe5934"
        }
      ]
    }
  ]
}
