{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-network",
    "version": "1.5.0-alpha3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.5.0-alpha3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.5.0-alpha3.aar",
          "url": "nautilus-util-network-1.5.0-alpha3.aar",
          "size": 23896,
          "sha512": "5ed82e28130cf7b085bebcd5b8bcef3c86eb78f9fc8c786f772878a8c23fd4a6f23a97aa5de758b413ee581019c3313f5c7f98120462dd8692b61d2f9d9ce644",
          "sha256": "6d14024f070bd7ef5db38d5b92c06a1efcb69ba20fe3f137741b4e1a935f50ad",
          "sha1": "2448fdeebde3f8fbdbf3d14a42948c34e0e0a199",
          "md5": "7623910c0ed67f8d707c9e02a2cb6e85"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.5.0-alpha3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.5.0-alpha3.aar",
          "url": "nautilus-util-network-1.5.0-alpha3.aar",
          "size": 23896,
          "sha512": "5ed82e28130cf7b085bebcd5b8bcef3c86eb78f9fc8c786f772878a8c23fd4a6f23a97aa5de758b413ee581019c3313f5c7f98120462dd8692b61d2f9d9ce644",
          "sha256": "6d14024f070bd7ef5db38d5b92c06a1efcb69ba20fe3f137741b4e1a935f50ad",
          "sha1": "2448fdeebde3f8fbdbf3d14a42948c34e0e0a199",
          "md5": "7623910c0ed67f8d707c9e02a2cb6e85"
        }
      ]
    }
  ]
}
