{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-format",
    "version": "1.13.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.13.4.aar",
          "url": "nautilus-util-format-1.13.4.aar",
          "size": 8945,
          "sha512": "726218620e3fac7537f23cca348d56afb9cd51bf8285c3013f8e11ff78006a43ed2a8db23a035836c0a2a8b5ccb0905a67c6b042383095f8c4443a9f15b68ddd",
          "sha256": "64860210a174afd62ef988f11f5021d8b131ecdb5520d17290ee1d3fbacccb6d",
          "sha1": "e985a7e6b4a836de64b15c92b85f4b4c1306487f",
          "md5": "e189b1970aac6cdc45e0f5afcf0a6020"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.13.4.aar",
          "url": "nautilus-util-format-1.13.4.aar",
          "size": 8945,
          "sha512": "726218620e3fac7537f23cca348d56afb9cd51bf8285c3013f8e11ff78006a43ed2a8db23a035836c0a2a8b5ccb0905a67c6b042383095f8c4443a9f15b68ddd",
          "sha256": "64860210a174afd62ef988f11f5021d8b131ecdb5520d17290ee1d3fbacccb6d",
          "sha1": "e985a7e6b4a836de64b15c92b85f4b4c1306487f",
          "md5": "e189b1970aac6cdc45e0f5afcf0a6020"
        }
      ]
    }
  ]
}
