{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-tools-logging",
    "version": "1.12.2-hotfix3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-logging-1.12.2-hotfix3.aar",
          "url": "nautilus-tools-logging-1.12.2-hotfix3.aar",
          "size": 19643,
          "sha512": "96872062da6a1cf1e998af5e678b9a12667cdc8882c8ea631f55948aacde84ee696d68082d9924c187598254e0471099ad66bf28030565ad8af2391284528208",
          "sha256": "c3fd57ebb42dd58ec68ca23ec6ad2b92755ae73a03fafef4e74adfa5a8a4119b",
          "sha1": "fae11412b6cb03cbc22b9e50aa24444773ab2d9f",
          "md5": "a9811f18554e2626fce28f5e85a6838a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-logging-1.12.2-hotfix3.aar",
          "url": "nautilus-tools-logging-1.12.2-hotfix3.aar",
          "size": 19643,
          "sha512": "96872062da6a1cf1e998af5e678b9a12667cdc8882c8ea631f55948aacde84ee696d68082d9924c187598254e0471099ad66bf28030565ad8af2391284528208",
          "sha256": "c3fd57ebb42dd58ec68ca23ec6ad2b92755ae73a03fafef4e74adfa5a8a4119b",
          "sha1": "fae11412b6cb03cbc22b9e50aa24444773ab2d9f",
          "md5": "a9811f18554e2626fce28f5e85a6838a"
        }
      ]
    }
  ]
}
