{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-core",
    "version": "1.7.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-cryptography",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-core-1.7.20.aar",
          "url": "nautilus-core-1.7.20.aar",
          "size": 113250,
          "sha512": "3656c1f5aefe1d2cd1873239c49e964782c259bf669a9f303679d6a2c8589a9f52d5dc014b630f55b84181a57b06f4d85417b782fbd7b17683d569b505520298",
          "sha256": "85f4f7b0d9b23afe454d34c1f6ea697461a603036d26a0e616df2257848e6f2e",
          "sha1": "56a930c3de2b00fac821b3a4c24ca367c3162b19",
          "md5": "7a180afbe1a4ba0bdbb16460ce73fe08"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-cryptography",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-core-1.7.20.aar",
          "url": "nautilus-core-1.7.20.aar",
          "size": 113250,
          "sha512": "3656c1f5aefe1d2cd1873239c49e964782c259bf669a9f303679d6a2c8589a9f52d5dc014b630f55b84181a57b06f4d85417b782fbd7b17683d569b505520298",
          "sha256": "85f4f7b0d9b23afe454d34c1f6ea697461a603036d26a0e616df2257848e6f2e",
          "sha1": "56a930c3de2b00fac821b3a4c24ca367c3162b19",
          "md5": "7a180afbe1a4ba0bdbb16460ce73fe08"
        }
      ]
    }
  ]
}
