{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-analytics",
    "version": "1.16.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.16.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-1.16.3.aar",
          "url": "nautilus-analytics-1.16.3.aar",
          "size": 165065,
          "sha512": "6815301c7992ea507ad32991166ec73bf5b7cdc1dea65c93c3364657fd426a3d91c16ee2d6011f78815f72b6837398ab6e492c2981ae5cf75a7509962933b59c",
          "sha256": "8449ef5325276896b23efe9e4b93c9a8efadc26715b8e8605c455a79c8ca6bd3",
          "sha1": "9a89fd5b32ba64d28bd7ee1c8961de76d80e09c5",
          "md5": "6e14a10a81e6564e8c79a8ec707c170e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.16.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-1.16.3.aar",
          "url": "nautilus-analytics-1.16.3.aar",
          "size": 165065,
          "sha512": "6815301c7992ea507ad32991166ec73bf5b7cdc1dea65c93c3364657fd426a3d91c16ee2d6011f78815f72b6837398ab6e492c2981ae5cf75a7509962933b59c",
          "sha256": "8449ef5325276896b23efe9e4b93c9a8efadc26715b8e8605c455a79c8ca6bd3",
          "sha1": "9a89fd5b32ba64d28bd7ee1c8961de76d80e09c5",
          "md5": "6e14a10a81e6564e8c79a8ec707c170e"
        }
      ]
    }
  ]
}
