{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-tools-livedata",
    "version": "1.7.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-livedata-1.7.8.aar",
          "url": "nautilus-tools-livedata-1.7.8.aar",
          "size": 10332,
          "sha512": "bd3e526ed05ce8134a19bdd63169ae85d2f94b239f1f0d618311148e5e6a78310c65fece8ac03fa4d472acadcb5fe8f5b8195f88d98c922ede1d92dd1adf90b8",
          "sha256": "8673ebbaa4cc40939ad412d58daf042446ee08b516699db247f869fb1ea557ea",
          "sha1": "ee773ccb7c28a145ba22ad984b854e573d01cbd3",
          "md5": "13fec31adaaa3c660cc6c174496c2762"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-livedata-1.7.8.aar",
          "url": "nautilus-tools-livedata-1.7.8.aar",
          "size": 10332,
          "sha512": "bd3e526ed05ce8134a19bdd63169ae85d2f94b239f1f0d618311148e5e6a78310c65fece8ac03fa4d472acadcb5fe8f5b8195f88d98c922ede1d92dd1adf90b8",
          "sha256": "8673ebbaa4cc40939ad412d58daf042446ee08b516699db247f869fb1ea557ea",
          "sha1": "ee773ccb7c28a145ba22ad984b854e573d01cbd3",
          "md5": "13fec31adaaa3c660cc6c174496c2762"
        }
      ]
    }
  ]
}
