{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-campaign",
    "version": "1.25.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.25.11"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-format",
          "version": {
            "requires": "1.25.11"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-campaign-1.25.11.aar",
          "url": "nautilus-campaign-1.25.11.aar",
          "size": 132337,
          "sha512": "5b11780dfcfa5b7a55dc841defa4172732018bb2d17ef8365b0a8238b89e2ea26937fd99634ca55302174fc95cfcb639b6b0f8088530a330ec9a5ad4893afbad",
          "sha256": "6d0f8a573550649c26f07088bb7737c6d6cfa1660f47c37a69c54b8238e3e757",
          "sha1": "777bd34b59ff8a303f18be2c3005b986c304a92f",
          "md5": "b4d1f07dc14c742cbf4032ada4633401"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.3.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.3.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.15.2"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.15.2"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.25.11"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-format",
          "version": {
            "requires": "1.25.11"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-campaign-1.25.11.aar",
          "url": "nautilus-campaign-1.25.11.aar",
          "size": 132337,
          "sha512": "5b11780dfcfa5b7a55dc841defa4172732018bb2d17ef8365b0a8238b89e2ea26937fd99634ca55302174fc95cfcb639b6b0f8088530a330ec9a5ad4893afbad",
          "sha256": "6d0f8a573550649c26f07088bb7737c6d6cfa1660f47c37a69c54b8238e3e757",
          "sha1": "777bd34b59ff8a303f18be2c3005b986c304a92f",
          "md5": "b4d1f07dc14c742cbf4032ada4633401"
        }
      ]
    }
  ]
}
