{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-core",
    "version": "1.7.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.7.24"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-cryptography",
          "version": {
            "requires": "1.7.24"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-core-1.7.24.aar",
          "url": "nautilus-core-1.7.24.aar",
          "size": 113253,
          "sha512": "438a0d10d2048e803a5da39a6cafc97394343c01441ed00b26deec266911b67cd7d127d880dc6dec0f8702c30d5b76acbbc4dec31a9eb6abe8ac8e48000bb137",
          "sha256": "c55ffc3949036159f3203b0f71ddc42555ca53cde6f6ab0c41c6cdd614f7641a",
          "sha1": "a00f48f88f02eacc7f9eb0e15fc70f61669bb957",
          "md5": "28a7f3beb2725fa866615267eed8114d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.7.24"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-cryptography",
          "version": {
            "requires": "1.7.24"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-core-1.7.24.aar",
          "url": "nautilus-core-1.7.24.aar",
          "size": 113253,
          "sha512": "438a0d10d2048e803a5da39a6cafc97394343c01441ed00b26deec266911b67cd7d127d880dc6dec0f8702c30d5b76acbbc4dec31a9eb6abe8ac8e48000bb137",
          "sha256": "c55ffc3949036159f3203b0f71ddc42555ca53cde6f6ab0c41c6cdd614f7641a",
          "sha1": "a00f48f88f02eacc7f9eb0e15fc70f61669bb957",
          "md5": "28a7f3beb2725fa866615267eed8114d"
        }
      ]
    }
  ]
}
