{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-network",
    "version": "1.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.8.0.aar",
          "url": "nautilus-util-network-1.8.0.aar",
          "size": 23244,
          "sha512": "443d8bb6070d6899bc92fe66b601fcae9acc7c69f8a8383f0660ac0a3dabd102a75f23743f1add3d2f2c5d1887b9b82afca7de4ef86a5f81d3b571f708857c26",
          "sha256": "04a7d4ec5740f77a1ebe3d6cc2af71c2c8b46e229a4c202fc8675d35efbd8bdf",
          "sha1": "a0f9fffa73c1ef640abc5803dd222e2876a2649f",
          "md5": "a5adab0938712773c93a2c6a83fe8120"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.8.0.aar",
          "url": "nautilus-util-network-1.8.0.aar",
          "size": 23244,
          "sha512": "443d8bb6070d6899bc92fe66b601fcae9acc7c69f8a8383f0660ac0a3dabd102a75f23743f1add3d2f2c5d1887b9b82afca7de4ef86a5f81d3b571f708857c26",
          "sha256": "04a7d4ec5740f77a1ebe3d6cc2af71c2c8b46e229a4c202fc8675d35efbd8bdf",
          "sha1": "a0f9fffa73c1ef640abc5803dd222e2876a2649f",
          "md5": "a5adab0938712773c93a2c6a83fe8120"
        }
      ]
    }
  ]
}
