{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-format",
    "version": "1.12.13-hotfix1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.12.13-hotfix1.aar",
          "url": "nautilus-util-format-1.12.13-hotfix1.aar",
          "size": 8943,
          "sha512": "19b1daf7083a9e377bbf68cbd272594f92d1f0a4db710c41c653032af8fd27851a00827bc957f966d8cdb81ef273b0ac5bdc78c8f97bd217e18a5dbf69b2c917",
          "sha256": "6eed8bfe53a4a532010bd028b120ff46a836f86b6e9d3ecd4db296fb904d2deb",
          "sha1": "96feb5ab41a87454d6a97de906a6cada3218b81a",
          "md5": "e0722c535bbbfabcc9d481c6dccd27ee"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.12.13-hotfix1.aar",
          "url": "nautilus-util-format-1.12.13-hotfix1.aar",
          "size": 8943,
          "sha512": "19b1daf7083a9e377bbf68cbd272594f92d1f0a4db710c41c653032af8fd27851a00827bc957f966d8cdb81ef273b0ac5bdc78c8f97bd217e18a5dbf69b2c917",
          "sha256": "6eed8bfe53a4a532010bd028b120ff46a836f86b6e9d3ecd4db296fb904d2deb",
          "sha1": "96feb5ab41a87454d6a97de906a6cada3218b81a",
          "md5": "e0722c535bbbfabcc9d481c6dccd27ee"
        }
      ]
    }
  ]
}
