{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-json",
    "version": "1.7.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-json-1.7.17.aar",
          "url": "nautilus-util-json-1.7.17.aar",
          "size": 11152,
          "sha512": "2b83049eade5b78aa517c44711b7f14e36195cd1e8e9d4521011604d1c1355f822059b83c2cfef31ffd6d973dae0f00c6ada6a6f80290f6d2d65246d546f08fd",
          "sha256": "763af53043d5f5a05d93111f82eabb1d28d23df8c6fd509d7f0fd1c901514ef0",
          "sha1": "7c26cf6123c649829ccfa43292ea75b52477bbe6",
          "md5": "b3a645f374571d1164b8485ea5b496e7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-json-1.7.17.aar",
          "url": "nautilus-util-json-1.7.17.aar",
          "size": 11152,
          "sha512": "2b83049eade5b78aa517c44711b7f14e36195cd1e8e9d4521011604d1c1355f822059b83c2cfef31ffd6d973dae0f00c6ada6a6f80290f6d2d65246d546f08fd",
          "sha256": "763af53043d5f5a05d93111f82eabb1d28d23df8c6fd509d7f0fd1c901514ef0",
          "sha1": "7c26cf6123c649829ccfa43292ea75b52477bbe6",
          "md5": "b3a645f374571d1164b8485ea5b496e7"
        }
      ]
    }
  ]
}
