{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-format",
    "version": "1.19.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.19.11.aar",
          "url": "nautilus-util-format-1.19.11.aar",
          "size": 8980,
          "sha512": "aad3d3357cfaa55492aa7fa7135c5f8c1eaa088b2eed8e3afc6411585a2505d8d524a4fa7cabcacb318b4053105e7e47b5aef25842dcbe6bc48847b97815c7a4",
          "sha256": "2f8f1df031dd45555f78a1795e155404a7f63981f662376c1fd97d0189cebacb",
          "sha1": "3b1ccac06001ef3d77a67f146b7c3aa9d7f116fe",
          "md5": "6e10ea452ba6c02c7dea50e3016c9f90"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.19.11.aar",
          "url": "nautilus-util-format-1.19.11.aar",
          "size": 8980,
          "sha512": "aad3d3357cfaa55492aa7fa7135c5f8c1eaa088b2eed8e3afc6411585a2505d8d524a4fa7cabcacb318b4053105e7e47b5aef25842dcbe6bc48847b97815c7a4",
          "sha256": "2f8f1df031dd45555f78a1795e155404a7f63981f662376c1fd97d0189cebacb",
          "sha1": "3b1ccac06001ef3d77a67f146b7c3aa9d7f116fe",
          "md5": "6e10ea452ba6c02c7dea50e3016c9f90"
        }
      ]
    }
  ]
}
