{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-analytics",
    "version": "1.15.7-hotfix1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.15.7-hotfix1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-1.15.7-hotfix1.aar",
          "url": "nautilus-analytics-1.15.7-hotfix1.aar",
          "size": 165079,
          "sha512": "81256802c69f11ec8cdffc0a03db93982c2cd3187741472aa12b9f60512791c986546ae1aa0a53dc983beff9e96f1762f4123599167404d8277aa075299c9364",
          "sha256": "6b64f4ab1bbb2edfe0c7ab87b0b97d02754fd310ca35463a446def5731d68534",
          "sha1": "54696ff781bf5304d6468f482b6431cbf192c5d2",
          "md5": "013d9dfcb33d2a7ae5fc26c84c7287dc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.15.7-hotfix1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-1.15.7-hotfix1.aar",
          "url": "nautilus-analytics-1.15.7-hotfix1.aar",
          "size": 165079,
          "sha512": "81256802c69f11ec8cdffc0a03db93982c2cd3187741472aa12b9f60512791c986546ae1aa0a53dc983beff9e96f1762f4123599167404d8277aa075299c9364",
          "sha256": "6b64f4ab1bbb2edfe0c7ab87b0b97d02754fd310ca35463a446def5731d68534",
          "sha1": "54696ff781bf5304d6468f482b6431cbf192c5d2",
          "md5": "013d9dfcb33d2a7ae5fc26c84c7287dc"
        }
      ]
    }
  ]
}
