{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-format",
    "version": "1.14.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.14.1.aar",
          "url": "nautilus-util-format-1.14.1.aar",
          "size": 8954,
          "sha512": "db3dfabfeca430302ad7f4b3b5c0d0aea04c8cc364de6cea0d8c8d1aa894a8fe81bb16899a2b030828efe8f505f4b2392aa542883c52136f20f62289b336263b",
          "sha256": "48bd11643ca1e0760aa4705c133997acabc8e7f8d9b144d1a5ada672721603e6",
          "sha1": "8e1cc5ba2765697eddd25c69c44b30e6f1751555",
          "md5": "6a600aa4fe05ce4c48ed675bf6896d18"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.14.1.aar",
          "url": "nautilus-util-format-1.14.1.aar",
          "size": 8954,
          "sha512": "db3dfabfeca430302ad7f4b3b5c0d0aea04c8cc364de6cea0d8c8d1aa894a8fe81bb16899a2b030828efe8f505f4b2392aa542883c52136f20f62289b336263b",
          "sha256": "48bd11643ca1e0760aa4705c133997acabc8e7f8d9b144d1a5ada672721603e6",
          "sha1": "8e1cc5ba2765697eddd25c69c44b30e6f1751555",
          "md5": "6a600aa4fe05ce4c48ed675bf6896d18"
        }
      ]
    }
  ]
}
