{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-tools-cryptography",
    "version": "1.8.0-alpha1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-cryptography-1.8.0-alpha1.aar",
          "url": "nautilus-tools-cryptography-1.8.0-alpha1.aar",
          "size": 26307,
          "sha512": "cab0bbe0af17a11e24dfa8551e970c1429275867f63886377f3d83b47a3d4401d003dbb1d4bff5598f8427089c08a6d985a5b13cb4353433cdf8379271b82432",
          "sha256": "c350b21f6783285910bf13bafa4eb3994011fa4d96118a9cbbc50b1271ac28d2",
          "sha1": "530d86c821f06c7a319edf85a9afe41ff916c27e",
          "md5": "3937dfe8bf2996269b813889eba1982d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-cryptography-1.8.0-alpha1.aar",
          "url": "nautilus-tools-cryptography-1.8.0-alpha1.aar",
          "size": 26307,
          "sha512": "cab0bbe0af17a11e24dfa8551e970c1429275867f63886377f3d83b47a3d4401d003dbb1d4bff5598f8427089c08a6d985a5b13cb4353433cdf8379271b82432",
          "sha256": "c350b21f6783285910bf13bafa4eb3994011fa4d96118a9cbbc50b1271ac28d2",
          "sha1": "530d86c821f06c7a319edf85a9afe41ff916c27e",
          "md5": "3937dfe8bf2996269b813889eba1982d"
        }
      ]
    }
  ]
}
