{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-imaging",
    "version": "1.7.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-network",
          "version": {
            "requires": "1.7.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-imaging-1.7.5.aar",
          "url": "nautilus-util-imaging-1.7.5.aar",
          "size": 11066,
          "sha512": "7c64365acd116c00d6a96fe95039758b6abc110e43754b316cc24cdabcfa67eed525bb90d89ca0be74decc6a49cd702af3a005538f3f2e2a8dea87c4fb516094",
          "sha256": "68100d4b6a611125fc557e84ac086e24b820cf9f863360d77e7198bb895938e3",
          "sha1": "edb44d75d68d836ca1c9196362ee38f00d7e7b5a",
          "md5": "b2cab289f7454e495480d3f0527251f8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-network",
          "version": {
            "requires": "1.7.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-imaging-1.7.5.aar",
          "url": "nautilus-util-imaging-1.7.5.aar",
          "size": 11066,
          "sha512": "7c64365acd116c00d6a96fe95039758b6abc110e43754b316cc24cdabcfa67eed525bb90d89ca0be74decc6a49cd702af3a005538f3f2e2a8dea87c4fb516094",
          "sha256": "68100d4b6a611125fc557e84ac086e24b820cf9f863360d77e7198bb895938e3",
          "sha1": "edb44d75d68d836ca1c9196362ee38f00d7e7b5a",
          "md5": "b2cab289f7454e495480d3f0527251f8"
        }
      ]
    }
  ]
}
