{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-tools-livedata",
    "version": "1.5.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-livedata-1.5.0-alpha.aar",
          "url": "nautilus-tools-livedata-1.5.0-alpha.aar",
          "size": 10167,
          "sha512": "d52db38708c3a199fe1a7386cd9ce5f2ee4de1f4ecdf6b9de514d1ebad3979e1aec0793b66887f31cae9c53aa4093f56d923082a2ecb0dd9ceffc5fe4a06667f",
          "sha256": "504a5ed079728f6cdac8e9914b95463dedc0bbc6d6e0d71201d4240b76cee499",
          "sha1": "ef76db93f23105a7b33e43bdde6ab7b590ecfe67",
          "md5": "446d48ecc394ccdc7bb7dc897e05b9b4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-livedata-1.5.0-alpha.aar",
          "url": "nautilus-tools-livedata-1.5.0-alpha.aar",
          "size": 10167,
          "sha512": "d52db38708c3a199fe1a7386cd9ce5f2ee4de1f4ecdf6b9de514d1ebad3979e1aec0793b66887f31cae9c53aa4093f56d923082a2ecb0dd9ceffc5fe4a06667f",
          "sha256": "504a5ed079728f6cdac8e9914b95463dedc0bbc6d6e0d71201d4240b76cee499",
          "sha1": "ef76db93f23105a7b33e43bdde6ab7b590ecfe67",
          "md5": "446d48ecc394ccdc7bb7dc897e05b9b4"
        }
      ]
    }
  ]
}
