{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-network",
    "version": "1.15.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.15.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.15.8.aar",
          "url": "nautilus-util-network-1.15.8.aar",
          "size": 23272,
          "sha512": "6d8e22e77a3469163faf816560f53032e7685cd09e4530ed63b8c997e825ad684ae4470dd54526e6498c7058d344c290d8ef3c72e22576aef84ff415b653404a",
          "sha256": "e4fdd7bdbd3b6141dd5b04621b0fd37c2c6083a4a36fc01ef019deee940dc22b",
          "sha1": "b5c7e494bbebfb50d77c05714ba2e9b037e12613",
          "md5": "e134bb3ef0b8e0a92f0d6d35b541605b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.15.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.15.8.aar",
          "url": "nautilus-util-network-1.15.8.aar",
          "size": 23272,
          "sha512": "6d8e22e77a3469163faf816560f53032e7685cd09e4530ed63b8c997e825ad684ae4470dd54526e6498c7058d344c290d8ef3c72e22576aef84ff415b653404a",
          "sha256": "e4fdd7bdbd3b6141dd5b04621b0fd37c2c6083a4a36fc01ef019deee940dc22b",
          "sha1": "b5c7e494bbebfb50d77c05714ba2e9b037e12613",
          "md5": "e134bb3ef0b8e0a92f0d6d35b541605b"
        }
      ]
    }
  ]
}
