{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-json",
    "version": "1.14.0-alpha1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-json-1.14.0-alpha1.aar",
          "url": "nautilus-util-json-1.14.0-alpha1.aar",
          "size": 11362,
          "sha512": "f58320691715d1883ae7ccf4aacc95fed0d97b28f5cdb6c15aadddb82cbd0c40fa24e177ca8af6d65454f2d1c6556a519461836f14e7e5109ced9f8c7d071011",
          "sha256": "f60c0e60290647c281a878894f80633b2e46f05721bf13d9c99cd23f8b3bb108",
          "sha1": "4a4cdfdb4ecdf0de6f7903eac44e4e76c53e64e9",
          "md5": "f6962b262390b05bb11fc9ac6c513c8b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-json-1.14.0-alpha1.aar",
          "url": "nautilus-util-json-1.14.0-alpha1.aar",
          "size": 11362,
          "sha512": "f58320691715d1883ae7ccf4aacc95fed0d97b28f5cdb6c15aadddb82cbd0c40fa24e177ca8af6d65454f2d1c6556a519461836f14e7e5109ced9f8c7d071011",
          "sha256": "f60c0e60290647c281a878894f80633b2e46f05721bf13d9c99cd23f8b3bb108",
          "sha1": "4a4cdfdb4ecdf0de6f7903eac44e4e76c53e64e9",
          "md5": "f6962b262390b05bb11fc9ac6c513c8b"
        }
      ]
    }
  ]
}
