{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-shop",
    "version": "1.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-analytics",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-imaging",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-geo",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-config",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-view",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-format",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-shop-1.6.1.aar",
          "url": "nautilus-shop-1.6.1.aar",
          "size": 1093202,
          "sha512": "0e139c2889adc1e79728db3fb349c0b4b675b437396c194cb1bcd43943e207b9b64ed19727cbb1051cb6ba7190839596c3a6d1c0c47cfd697d1ddd4afc8f1fba",
          "sha256": "e0ceac3519695c26f3ddcc5313236b3f804424a95119b015388d1723f0ba2b78",
          "sha1": "7239cc05dbeb09d195438db945167a2026592110",
          "md5": "f545ff34c4c491b8c77c4ab16dc9b893"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-analytics",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-imaging",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-geo",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-config",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-view",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-format",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.3"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.4.3"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-maps",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-shop-1.6.1.aar",
          "url": "nautilus-shop-1.6.1.aar",
          "size": 1093202,
          "sha512": "0e139c2889adc1e79728db3fb349c0b4b675b437396c194cb1bcd43943e207b9b64ed19727cbb1051cb6ba7190839596c3a6d1c0c47cfd697d1ddd4afc8f1fba",
          "sha256": "e0ceac3519695c26f3ddcc5313236b3f804424a95119b015388d1723f0ba2b78",
          "sha1": "7239cc05dbeb09d195438db945167a2026592110",
          "md5": "f545ff34c4c491b8c77c4ab16dc9b893"
        }
      ]
    }
  ]
}
