{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-format",
    "version": "1.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.4.3.aar",
          "url": "nautilus-util-format-1.4.3.aar",
          "size": 8820,
          "sha512": "ed5af19d2e77fa978fada76ebd99000084cc6ee5690254b4820625c58fd3ed10c219d7df50483ba699d6aefc64cfe571ae99aaae358bb1ba6d86fbed639b3045",
          "sha256": "c69eb256324afcd6789514e571300ef3843e5e1d40f2d5ebe204a0a1562f1126",
          "sha1": "e5087ce1f11cdff14cf302d5c6dd5419a57b940a",
          "md5": "0c45bf7c1b4d6786fd5f1ffeec85c023"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.4.3.aar",
          "url": "nautilus-util-format-1.4.3.aar",
          "size": 8820,
          "sha512": "ed5af19d2e77fa978fada76ebd99000084cc6ee5690254b4820625c58fd3ed10c219d7df50483ba699d6aefc64cfe571ae99aaae358bb1ba6d86fbed639b3045",
          "sha256": "c69eb256324afcd6789514e571300ef3843e5e1d40f2d5ebe204a0a1562f1126",
          "sha1": "e5087ce1f11cdff14cf302d5c6dd5419a57b940a",
          "md5": "0c45bf7c1b4d6786fd5f1ffeec85c023"
        }
      ]
    }
  ]
}
