{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-core",
    "version": "1.7.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.7.18"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-cryptography",
          "version": {
            "requires": "1.7.18"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-core-1.7.18.aar",
          "url": "nautilus-core-1.7.18.aar",
          "size": 115163,
          "sha512": "359536581b33196ca801ae26b505279ae78619ea5a55fc6d8a0b24ec6f6ef89b15dc2402353105940d01dfecc87d589343ef2e8b6b23aa62671bb491ad023b88",
          "sha256": "5c3f71d9e88740ae6a8f81e3e03bc019a390ea22a7ab974ac0a26366012322ba",
          "sha1": "dd59292b93581235cafdff5443dfe679a4680a38",
          "md5": "1074b4a002375a06035b16ad9384da98"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.7.18"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-cryptography",
          "version": {
            "requires": "1.7.18"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-core-1.7.18.aar",
          "url": "nautilus-core-1.7.18.aar",
          "size": 115163,
          "sha512": "359536581b33196ca801ae26b505279ae78619ea5a55fc6d8a0b24ec6f6ef89b15dc2402353105940d01dfecc87d589343ef2e8b6b23aa62671bb491ad023b88",
          "sha256": "5c3f71d9e88740ae6a8f81e3e03bc019a390ea22a7ab974ac0a26366012322ba",
          "sha1": "dd59292b93581235cafdff5443dfe679a4680a38",
          "md5": "1074b4a002375a06035b16ad9384da98"
        }
      ]
    }
  ]
}
