{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-maintenance",
    "version": "1.12.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-network",
          "version": {
            "requires": "1.12.4"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.12.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-maintenance-1.12.4.aar",
          "url": "nautilus-maintenance-1.12.4.aar",
          "size": 41042,
          "sha512": "9f70f2bcab54bbdb1f7f4195a92e7a03ebb4753f804147d2ef9896abf6a4c397c5efc7fb56acb9bb14f1d3a9e7b9295e870dd83f573f42ec71aa66128e836312",
          "sha256": "1467c0e1e2aa4b36073b4943a7114ed3c0a8862ae948294107c7d93a1d85f67a",
          "sha1": "fcbd5695f8a460887cc4bcc8874a59c4a21b8087",
          "md5": "2c7f2dfe94933c40c8b67647f59b7921"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-network",
          "version": {
            "requires": "1.12.4"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.12.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-maintenance-1.12.4.aar",
          "url": "nautilus-maintenance-1.12.4.aar",
          "size": 41042,
          "sha512": "9f70f2bcab54bbdb1f7f4195a92e7a03ebb4753f804147d2ef9896abf6a4c397c5efc7fb56acb9bb14f1d3a9e7b9295e870dd83f573f42ec71aa66128e836312",
          "sha256": "1467c0e1e2aa4b36073b4943a7114ed3c0a8862ae948294107c7d93a1d85f67a",
          "sha1": "fcbd5695f8a460887cc4bcc8874a59c4a21b8087",
          "md5": "2c7f2dfe94933c40c8b67647f59b7921"
        }
      ]
    }
  ]
}
