{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-network",
    "version": "1.18.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.18.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.18.0.aar",
          "url": "nautilus-util-network-1.18.0.aar",
          "size": 23268,
          "sha512": "956cbfeb373a45e7e0db97da41d3d763392d3394c5d1c4603bfdd084250ccd337679e9a69a2975ec05f1a65fdcdc69ad78867cec2010df9e549b5754633f0236",
          "sha256": "62d401f718ac2c60010b3961fec3ccd31c7afd6085048b0fb40166083d766c04",
          "sha1": "bcd99ccad38da5c64b243895171c2fce6f0e29c4",
          "md5": "fba8993d157539b4ca68c27780dd0641"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.18.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.18.0.aar",
          "url": "nautilus-util-network-1.18.0.aar",
          "size": 23268,
          "sha512": "956cbfeb373a45e7e0db97da41d3d763392d3394c5d1c4603bfdd084250ccd337679e9a69a2975ec05f1a65fdcdc69ad78867cec2010df9e549b5754633f0236",
          "sha256": "62d401f718ac2c60010b3961fec3ccd31c7afd6085048b0fb40166083d766c04",
          "sha1": "bcd99ccad38da5c64b243895171c2fce6f0e29c4",
          "md5": "fba8993d157539b4ca68c27780dd0641"
        }
      ]
    }
  ]
}
