{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-maintenance",
    "version": "1.14.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-network",
          "version": {
            "requires": "1.14.3"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.14.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-maintenance-1.14.3.aar",
          "url": "nautilus-maintenance-1.14.3.aar",
          "size": 41040,
          "sha512": "2a9592715ee0a5b1658ddf83bd5574d59d6f4926ab840871a0ec62eed79374b8037e166a6fcc016fa8be91dec0bbe55419f2579e68ad67d2d53a5a831c183997",
          "sha256": "7749692d1fd6bfa93c62cbb0dd3b355818562e507967c30685a6ad61598bf740",
          "sha1": "3a956a1f455e3bee028bae7d690a606416e8641e",
          "md5": "43e3025a5b23818e248810685a372f34"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-network",
          "version": {
            "requires": "1.14.3"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.14.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-maintenance-1.14.3.aar",
          "url": "nautilus-maintenance-1.14.3.aar",
          "size": 41040,
          "sha512": "2a9592715ee0a5b1658ddf83bd5574d59d6f4926ab840871a0ec62eed79374b8037e166a6fcc016fa8be91dec0bbe55419f2579e68ad67d2d53a5a831c183997",
          "sha256": "7749692d1fd6bfa93c62cbb0dd3b355818562e507967c30685a6ad61598bf740",
          "sha1": "3a956a1f455e3bee028bae7d690a606416e8641e",
          "md5": "43e3025a5b23818e248810685a372f34"
        }
      ]
    }
  ]
}
