{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-map",
    "version": "1.19.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-map-1.19.23.aar",
          "url": "nautilus-util-map-1.19.23.aar",
          "size": 10408,
          "sha512": "7c25d75bdd390737ae1882c497b0c2d928ffdc2934c10a8907654c0f1da5da2a5df3428ad9443ebc8a1cc14f6c30b82fb0a93e9adf4800cf30a237db8c7f4665",
          "sha256": "7f76d41c2a94498d62b9928739a7dee6c01bab8eb0be6864b7e15d67b93a337c",
          "sha1": "c2268d58caad952e02802f49a273b1db4a8c3e63",
          "md5": "31e0df86629e76c519a6c8ce94e25f9e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-maps",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-map-1.19.23.aar",
          "url": "nautilus-util-map-1.19.23.aar",
          "size": 10408,
          "sha512": "7c25d75bdd390737ae1882c497b0c2d928ffdc2934c10a8907654c0f1da5da2a5df3428ad9443ebc8a1cc14f6c30b82fb0a93e9adf4800cf30a237db8c7f4665",
          "sha256": "7f76d41c2a94498d62b9928739a7dee6c01bab8eb0be6864b7e15d67b93a337c",
          "sha1": "c2268d58caad952e02802f49a273b1db4a8c3e63",
          "md5": "31e0df86629e76c519a6c8ce94e25f9e"
        }
      ]
    }
  ]
}
