{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-format",
    "version": "1.19.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.19.14.aar",
          "url": "nautilus-util-format-1.19.14.aar",
          "size": 8979,
          "sha512": "4bad6e350b79173cf99d391c33267e05fdabecc5b3b91b4ca32d91ac1e110544ae4f7ffa1173e76c25450b6e7586b88f0ab42c65b515439bdf94ffb08e5f1983",
          "sha256": "fe7ebc4799a98fcf932d13076c1f5ee2101f2c2b817677305b3d4c91ca315bbf",
          "sha1": "f4b8df1969a7fd20d0ca5d509f23d6fc4550bfb0",
          "md5": "e166badc80f276ccd5d7ab57f56b2296"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.19.14.aar",
          "url": "nautilus-util-format-1.19.14.aar",
          "size": 8979,
          "sha512": "4bad6e350b79173cf99d391c33267e05fdabecc5b3b91b4ca32d91ac1e110544ae4f7ffa1173e76c25450b6e7586b88f0ab42c65b515439bdf94ffb08e5f1983",
          "sha256": "fe7ebc4799a98fcf932d13076c1f5ee2101f2c2b817677305b3d4c91ca315bbf",
          "sha1": "f4b8df1969a7fd20d0ca5d509f23d6fc4550bfb0",
          "md5": "e166badc80f276ccd5d7ab57f56b2296"
        }
      ]
    }
  ]
}
