{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-network",
    "version": "1.25.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.25.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.25.13.aar",
          "url": "nautilus-util-network-1.25.13.aar",
          "size": 19315,
          "sha512": "8b0c44c6fa81c0abd9fe365a2bbafca2493db2f47cfd3693172051ad1a32932d7eefd0d0869e407b37d219451b67f26259478adf75af3e5857aec1ded9ab24ef",
          "sha256": "13a8b21453cdf348849f65a3c9a81bad95a73647a3baa02bfb0e16ac928d5e2c",
          "sha1": "4c769e3d52bfc1f301786a2a70d6185c20cf1497",
          "md5": "d3b82fea6c18a76662e98369eaeb7bbd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.3.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.3.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.15.2"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.15.2"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.25.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.25.13.aar",
          "url": "nautilus-util-network-1.25.13.aar",
          "size": 19315,
          "sha512": "8b0c44c6fa81c0abd9fe365a2bbafca2493db2f47cfd3693172051ad1a32932d7eefd0d0869e407b37d219451b67f26259478adf75af3e5857aec1ded9ab24ef",
          "sha256": "13a8b21453cdf348849f65a3c9a81bad95a73647a3baa02bfb0e16ac928d5e2c",
          "sha1": "4c769e3d52bfc1f301786a2a70d6185c20cf1497",
          "md5": "d3b82fea6c18a76662e98369eaeb7bbd"
        }
      ]
    }
  ]
}
