{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-network",
    "version": "1.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.5.0.aar",
          "url": "nautilus-util-network-1.5.0.aar",
          "size": 23889,
          "sha512": "35de4d4755c76db68efb18888305e1d812c8aa5017afe8517c6ebe273def89cbf478ef02bbb1e824daa7e428dc41c5c3caa1651da5ad857611cd8aee1bbe129d",
          "sha256": "7141d15bb47c73a055d7bdff167789a8c8532634c11781ce7b86bbb26191f10d",
          "sha1": "a8dd7e3b7e6fbb408e510953d10e1721e3610aac",
          "md5": "0aa3f2b9e2c50b6a71a673d19d0f79a4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.5.0.aar",
          "url": "nautilus-util-network-1.5.0.aar",
          "size": 23889,
          "sha512": "35de4d4755c76db68efb18888305e1d812c8aa5017afe8517c6ebe273def89cbf478ef02bbb1e824daa7e428dc41c5c3caa1651da5ad857611cd8aee1bbe129d",
          "sha256": "7141d15bb47c73a055d7bdff167789a8c8532634c11781ce7b86bbb26191f10d",
          "sha1": "a8dd7e3b7e6fbb408e510953d10e1721e3610aac",
          "md5": "0aa3f2b9e2c50b6a71a673d19d0f79a4"
        }
      ]
    }
  ]
}
