{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-format",
    "version": "1.14.0-alpha1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.14.0-alpha1.aar",
          "url": "nautilus-util-format-1.14.0-alpha1.aar",
          "size": 8948,
          "sha512": "8194f67dd8853cf67afb728fa13dbe6fc2ef899033516017a5bbecd21f41d7f4a22badeac065fb30de60e2b68124dafc11ffae8fc0552891d44eb687967fb5d7",
          "sha256": "526de0fcd457b1cfb66a0c5fbcea042cdf3baefc3f84d3c8b3869f6211857df6",
          "sha1": "8f0ff1819f6641fd11e6e754adda28e79c299c38",
          "md5": "b899a22dcb63de6282dadc3f3b544b4f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.14.0-alpha1.aar",
          "url": "nautilus-util-format-1.14.0-alpha1.aar",
          "size": 8948,
          "sha512": "8194f67dd8853cf67afb728fa13dbe6fc2ef899033516017a5bbecd21f41d7f4a22badeac065fb30de60e2b68124dafc11ffae8fc0552891d44eb687967fb5d7",
          "sha256": "526de0fcd457b1cfb66a0c5fbcea042cdf3baefc3f84d3c8b3869f6211857df6",
          "sha1": "8f0ff1819f6641fd11e6e754adda28e79c299c38",
          "md5": "b899a22dcb63de6282dadc3f3b544b4f"
        }
      ]
    }
  ]
}
