{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-imaging",
    "version": "1.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-network",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-imaging-1.4.3.aar",
          "url": "nautilus-util-imaging-1.4.3.aar",
          "size": 11084,
          "sha512": "1c911d15109c8385879251366616c8623ada0893c39f4d11d99a0e476b460c33937f7df4a7dc85917981ffa467ac87916492549998c362a0c84ea957dae0f6e6",
          "sha256": "4e3b91f882fbaf2b02230baae860d386ebc91bbb37d9a0a3b15e2dcfda1c9eb5",
          "sha1": "05ceddfbb31123b4358b67ab5bf9e8244f04e47e",
          "md5": "54ff5c5d7da6ff6857132df9a31266e8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-network",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-imaging-1.4.3.aar",
          "url": "nautilus-util-imaging-1.4.3.aar",
          "size": 11084,
          "sha512": "1c911d15109c8385879251366616c8623ada0893c39f4d11d99a0e476b460c33937f7df4a7dc85917981ffa467ac87916492549998c362a0c84ea957dae0f6e6",
          "sha256": "4e3b91f882fbaf2b02230baae860d386ebc91bbb37d9a0a3b15e2dcfda1c9eb5",
          "sha1": "05ceddfbb31123b4358b67ab5bf9e8244f04e47e",
          "md5": "54ff5c5d7da6ff6857132df9a31266e8"
        }
      ]
    }
  ]
}
