{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-core",
    "version": "1.7.27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.7.27"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-cryptography",
          "version": {
            "requires": "1.7.27"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-core-1.7.27.aar",
          "url": "nautilus-core-1.7.27.aar",
          "size": 113250,
          "sha512": "e7d2d3ad6f0c1c3b66a4d6de2a288a37f0f0d80740890ccec25bc79a40f6159e1585fda35dc423587e2d580087e3f12710fb1a5cfeb295b950475f5fe5675822",
          "sha256": "18aae1721d64bf756c3e3ed20ea9db7457ec8c05672c30d5e86ea2f14ae68e52",
          "sha1": "616bae1b43b2d081a00ead7a357592ba7035f5e4",
          "md5": "368180aacb3fa11f2953beb5541aa552"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.7.27"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-cryptography",
          "version": {
            "requires": "1.7.27"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-core-1.7.27.aar",
          "url": "nautilus-core-1.7.27.aar",
          "size": 113250,
          "sha512": "e7d2d3ad6f0c1c3b66a4d6de2a288a37f0f0d80740890ccec25bc79a40f6159e1585fda35dc423587e2d580087e3f12710fb1a5cfeb295b950475f5fe5675822",
          "sha256": "18aae1721d64bf756c3e3ed20ea9db7457ec8c05672c30d5e86ea2f14ae68e52",
          "sha1": "616bae1b43b2d081a00ead7a357592ba7035f5e4",
          "md5": "368180aacb3fa11f2953beb5541aa552"
        }
      ]
    }
  ]
}
