{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-network",
    "version": "1.9.0-alpha1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.9.0-alpha1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.9.0-alpha1.aar",
          "url": "nautilus-util-network-1.9.0-alpha1.aar",
          "size": 23245,
          "sha512": "e2dcc688112c20e13e6732e358e30f1d81757b23dfd8c06cef9b68d7767fb205ec2392ffe76787884bb6b15f3bb2c7d0c7831e71cc50ef60ec3d2db20fbdb59b",
          "sha256": "8857b075c8dcf3a25a5342923bbb4816a34cade20dc853c65f83869590e2c76c",
          "sha1": "2e11a4ccc0418267bc120599fb9010b71659137e",
          "md5": "2afa3dc68df7d2b19e9b1ac16b31ecea"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.9.0-alpha1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.9.0-alpha1.aar",
          "url": "nautilus-util-network-1.9.0-alpha1.aar",
          "size": 23245,
          "sha512": "e2dcc688112c20e13e6732e358e30f1d81757b23dfd8c06cef9b68d7767fb205ec2392ffe76787884bb6b15f3bb2c7d0c7831e71cc50ef60ec3d2db20fbdb59b",
          "sha256": "8857b075c8dcf3a25a5342923bbb4816a34cade20dc853c65f83869590e2c76c",
          "sha1": "2e11a4ccc0418267bc120599fb9010b71659137e",
          "md5": "2afa3dc68df7d2b19e9b1ac16b31ecea"
        }
      ]
    }
  ]
}
