{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-tools-cryptography",
    "version": "1.16.0-hotfix1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-cryptography-1.16.0-hotfix1.aar",
          "url": "nautilus-tools-cryptography-1.16.0-hotfix1.aar",
          "size": 26327,
          "sha512": "127c6661ec17a19158fde63438d57cd8ad50cce7dd60899c8e71abe4514d1268dd138340ec4d6190d61e9cc767021ff5609642f94bd707923d30befa75faff47",
          "sha256": "819351ba3631dd3b8e3611f2e03b7d784e47305c62d5c709bc9e2843dc228382",
          "sha1": "3f1bd1f688395a14a7f51e2ae4cbd89b3caccceb",
          "md5": "7a3f601710acfe2b3c9db4848bfe6ed7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-cryptography-1.16.0-hotfix1.aar",
          "url": "nautilus-tools-cryptography-1.16.0-hotfix1.aar",
          "size": 26327,
          "sha512": "127c6661ec17a19158fde63438d57cd8ad50cce7dd60899c8e71abe4514d1268dd138340ec4d6190d61e9cc767021ff5609642f94bd707923d30befa75faff47",
          "sha256": "819351ba3631dd3b8e3611f2e03b7d784e47305c62d5c709bc9e2843dc228382",
          "sha1": "3f1bd1f688395a14a7f51e2ae4cbd89b3caccceb",
          "md5": "7a3f601710acfe2b3c9db4848bfe6ed7"
        }
      ]
    }
  ]
}
