{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-network",
    "version": "1.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.8.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.8.5.aar",
          "url": "nautilus-util-network-1.8.5.aar",
          "size": 23247,
          "sha512": "88b42ac11587b17708cc10c953b9184f1fd26b215013515bd717c7e8aea8bd2526be947a53a0a45febd986a47af0509cbef59144c297c78582e88f6e8bded345",
          "sha256": "7945a63e9583eb75073367fa9831b49eb46ec03d15f225a6f4aa4f49961f3468",
          "sha1": "d7eccc17e4782ce28ffec6d023f0d619b3870279",
          "md5": "4eba48d9d1c1a299012292acf6122393"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.8.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.8.5.aar",
          "url": "nautilus-util-network-1.8.5.aar",
          "size": 23247,
          "sha512": "88b42ac11587b17708cc10c953b9184f1fd26b215013515bd717c7e8aea8bd2526be947a53a0a45febd986a47af0509cbef59144c297c78582e88f6e8bded345",
          "sha256": "7945a63e9583eb75073367fa9831b49eb46ec03d15f225a6f4aa4f49961f3468",
          "sha1": "d7eccc17e4782ce28ffec6d023f0d619b3870279",
          "md5": "4eba48d9d1c1a299012292acf6122393"
        }
      ]
    }
  ]
}
