{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-format",
    "version": "1.9.5-hotfix1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.9.5-hotfix1.aar",
          "url": "nautilus-util-format-1.9.5-hotfix1.aar",
          "size": 8955,
          "sha512": "247f4c1ef9abb41d675fbf6ce026230deb2589220701f8f83648a54eb42151abb1299724f1f16d9081da9cebad98a69daa844a5109762686a4bc317b39d5c5ae",
          "sha256": "363998e4b17e52c911cda340f3c3b42aa17c304aa072e27d60845c98921efe19",
          "sha1": "2849a7b1597dc2d5f8dbb7dd51a277bd74fa530e",
          "md5": "00a8cc35e710d4a4f82202c846c36684"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.9.5-hotfix1.aar",
          "url": "nautilus-util-format-1.9.5-hotfix1.aar",
          "size": 8955,
          "sha512": "247f4c1ef9abb41d675fbf6ce026230deb2589220701f8f83648a54eb42151abb1299724f1f16d9081da9cebad98a69daa844a5109762686a4bc317b39d5c5ae",
          "sha256": "363998e4b17e52c911cda340f3c3b42aa17c304aa072e27d60845c98921efe19",
          "sha1": "2849a7b1597dc2d5f8dbb7dd51a277bd74fa530e",
          "md5": "00a8cc35e710d4a4f82202c846c36684"
        }
      ]
    }
  ]
}
