{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-analytics-amplitude-plugin",
    "version": "1.7.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.amplitude",
          "module": "android-sdk",
          "version": {
            "requires": "2.38.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-amplitude-plugin-1.7.5.aar",
          "url": "nautilus-analytics-amplitude-plugin-1.7.5.aar",
          "size": 11800,
          "sha512": "84fda934ddc236032e4bbf44cdd18cb96421f27bd69d3b5a138409dc48215d38787f51986ba4330fe94eeab5af66ecdc134bca52f765d3be7ba6f39417a1e911",
          "sha256": "b52e05f8ad390acd7e1ba4cddfec2110cbfd2679f2f60202451638a38a161778",
          "sha1": "b4512aa83a792830c7bbe5c69f4a1c20edc4ed0a",
          "md5": "819795f72a01aef7cd74a80cf9eac329"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.amplitude",
          "module": "android-sdk",
          "version": {
            "requires": "2.38.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-analytics",
          "version": {
            "requires": "1.7.5"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.7.5"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-amplitude-plugin-1.7.5.aar",
          "url": "nautilus-analytics-amplitude-plugin-1.7.5.aar",
          "size": 11800,
          "sha512": "84fda934ddc236032e4bbf44cdd18cb96421f27bd69d3b5a138409dc48215d38787f51986ba4330fe94eeab5af66ecdc134bca52f765d3be7ba6f39417a1e911",
          "sha256": "b52e05f8ad390acd7e1ba4cddfec2110cbfd2679f2f60202451638a38a161778",
          "sha1": "b4512aa83a792830c7bbe5c69f4a1c20edc4ed0a",
          "md5": "819795f72a01aef7cd74a80cf9eac329"
        }
      ]
    }
  ]
}
