{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-imaging",
    "version": "1.15.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-network",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-imaging-1.15.0.aar",
          "url": "nautilus-util-imaging-1.15.0.aar",
          "size": 11295,
          "sha512": "ec185307377d2058e372900e55970093c727b8319f5d0c2a277959ab1f4778da97ed54642f9a0bad1220f9b21749fc403f0464622268f8f6ca5376b6d3a9b3f9",
          "sha256": "aba93eb5cfceb04933d7d440d38c4d3e4a1a6afcc344146280f07aff2c4f6201",
          "sha1": "5de5a791cff2a2da8b1081e483a5f4a5ac2fe888",
          "md5": "11d24c307e4b4c60dfe6d3914361fda9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-network",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-imaging-1.15.0.aar",
          "url": "nautilus-util-imaging-1.15.0.aar",
          "size": 11295,
          "sha512": "ec185307377d2058e372900e55970093c727b8319f5d0c2a277959ab1f4778da97ed54642f9a0bad1220f9b21749fc403f0464622268f8f6ca5376b6d3a9b3f9",
          "sha256": "aba93eb5cfceb04933d7d440d38c4d3e4a1a6afcc344146280f07aff2c4f6201",
          "sha1": "5de5a791cff2a2da8b1081e483a5f4a5ac2fe888",
          "md5": "11d24c307e4b4c60dfe6d3914361fda9"
        }
      ]
    }
  ]
}
