{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-analytics-amplitude-plugin",
    "version": "1.19.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.amplitude",
          "module": "analytics-android",
          "version": {
            "requires": "1.21.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-amplitude-plugin-1.19.12.aar",
          "url": "nautilus-analytics-amplitude-plugin-1.19.12.aar",
          "size": 12113,
          "sha512": "221c451f4c0788f66c1e7cce71e560bb10a78a20fccaba4d5d1b2a3c9a06dfeb425f4e708e084fbd98cd36ae1e5dd094bb4897c97b9d2387818152c13fddf495",
          "sha256": "0ae354abd97b103df5dc49936ba588af9c57690a11923d172b87c795c69bb2f1",
          "sha1": "59a68435e2b7249f1a8f100df649a5b27e193388",
          "md5": "03cfd93aadcb7fc60d9a6fbea00eca11"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.amplitude",
          "module": "plugin-session-replay-android",
          "version": {
            "requires": "0.20.12"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-analytics",
          "version": {
            "requires": "1.19.12"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.19.12"
          }
        },
        {
          "group": "com.amplitude",
          "module": "analytics-android",
          "version": {
            "requires": "1.21.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-amplitude-plugin-1.19.12.aar",
          "url": "nautilus-analytics-amplitude-plugin-1.19.12.aar",
          "size": 12113,
          "sha512": "221c451f4c0788f66c1e7cce71e560bb10a78a20fccaba4d5d1b2a3c9a06dfeb425f4e708e084fbd98cd36ae1e5dd094bb4897c97b9d2387818152c13fddf495",
          "sha256": "0ae354abd97b103df5dc49936ba588af9c57690a11923d172b87c795c69bb2f1",
          "sha1": "59a68435e2b7249f1a8f100df649a5b27e193388",
          "md5": "03cfd93aadcb7fc60d9a6fbea00eca11"
        }
      ]
    }
  ]
}
