{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-format",
    "version": "1.19.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.19.20.aar",
          "url": "nautilus-util-format-1.19.20.aar",
          "size": 8967,
          "sha512": "68b3b34ad26bac27bc0a5a526c8ff7bb7516fa0b3d0280bb61ed1ae66faf57cb163f75543663b52138611f7981f635b250eabd245bdb28868414a80cc55da86e",
          "sha256": "6467600474569c44015b278abdc9893e9cb2743e3e2e02bd938d080ae558765c",
          "sha1": "d7b60e3c5c8792527e1e85e6a4b6eff63cd66e73",
          "md5": "24675be0620a6250232220292686758a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.19.20.aar",
          "url": "nautilus-util-format-1.19.20.aar",
          "size": 8967,
          "sha512": "68b3b34ad26bac27bc0a5a526c8ff7bb7516fa0b3d0280bb61ed1ae66faf57cb163f75543663b52138611f7981f635b250eabd245bdb28868414a80cc55da86e",
          "sha256": "6467600474569c44015b278abdc9893e9cb2743e3e2e02bd938d080ae558765c",
          "sha1": "d7b60e3c5c8792527e1e85e6a4b6eff63cd66e73",
          "md5": "24675be0620a6250232220292686758a"
        }
      ]
    }
  ]
}
