{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-tools-logging",
    "version": "1.16.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-logging-1.16.0.aar",
          "url": "nautilus-tools-logging-1.16.0.aar",
          "size": 19670,
          "sha512": "3ebf4e9b8708c8f5f97324d43f966302fe1ed5306e2a5d01d39ffa86c6378b76f8b211bb80166802a2fd342321cf722efc0ed8ff273331371f019bb3fab10f5e",
          "sha256": "3a6aad39a57a59b9c11c5e27b2c24dcfce5993ccdebc1958a3711e41166c42a2",
          "sha1": "fb008c74c0fa8d5265e37a965964cb3fc7a9eb11",
          "md5": "75a478e0aee6d4270cd745b881574d68"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-logging-1.16.0.aar",
          "url": "nautilus-tools-logging-1.16.0.aar",
          "size": 19670,
          "sha512": "3ebf4e9b8708c8f5f97324d43f966302fe1ed5306e2a5d01d39ffa86c6378b76f8b211bb80166802a2fd342321cf722efc0ed8ff273331371f019bb3fab10f5e",
          "sha256": "3a6aad39a57a59b9c11c5e27b2c24dcfce5993ccdebc1958a3711e41166c42a2",
          "sha1": "fb008c74c0fa8d5265e37a965964cb3fc7a9eb11",
          "md5": "75a478e0aee6d4270cd745b881574d68"
        }
      ]
    }
  ]
}
