{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-analytics",
    "version": "1.7.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-1.7.10.aar",
          "url": "nautilus-analytics-1.7.10.aar",
          "size": 157549,
          "sha512": "577921f5b07e483d36a6c1a53f6a13999dec860da298d63e05d6d7b7aa84236fd3ae9b0ad4ea9ed1ffb95b912ec397e3c1aa03f3838909ec33e5273a61f18991",
          "sha256": "b32f8b4d807442795d43e6311ebb6055c2b438bdf1e1ab190d6ef154db756b1b",
          "sha1": "d2075279b6df37cf307c8fb6650e3d2e43655c6d",
          "md5": "1b442d62ce88a1ae8c7889a885b67b95"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-1.7.10.aar",
          "url": "nautilus-analytics-1.7.10.aar",
          "size": 157549,
          "sha512": "577921f5b07e483d36a6c1a53f6a13999dec860da298d63e05d6d7b7aa84236fd3ae9b0ad4ea9ed1ffb95b912ec397e3c1aa03f3838909ec33e5273a61f18991",
          "sha256": "b32f8b4d807442795d43e6311ebb6055c2b438bdf1e1ab190d6ef154db756b1b",
          "sha1": "d2075279b6df37cf307c8fb6650e3d2e43655c6d",
          "md5": "1b442d62ce88a1ae8c7889a885b67b95"
        }
      ]
    }
  ]
}
