{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-format",
    "version": "1.8.0-alpha1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.8.0-alpha1.aar",
          "url": "nautilus-util-format-1.8.0-alpha1.aar",
          "size": 8943,
          "sha512": "71dbf86022220c262afd791646bcf86f6ca2271bc2db822a1c9f276620f276cbc91e305a19c757b94ae4a6031df802ddcdf5aec8c794335957e2128807681cd7",
          "sha256": "8f21e933e4d0705fef3c2c10f2605508965e27e7cbb6b61106fc3c5d6a110ee5",
          "sha1": "101ad0a8fb4f2346461efeb64ee96bf4f1d386a8",
          "md5": "959ee3bc3cf9b71bdaa985653834db36"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.8.0-alpha1.aar",
          "url": "nautilus-util-format-1.8.0-alpha1.aar",
          "size": 8943,
          "sha512": "71dbf86022220c262afd791646bcf86f6ca2271bc2db822a1c9f276620f276cbc91e305a19c757b94ae4a6031df802ddcdf5aec8c794335957e2128807681cd7",
          "sha256": "8f21e933e4d0705fef3c2c10f2605508965e27e7cbb6b61106fc3c5d6a110ee5",
          "sha1": "101ad0a8fb4f2346461efeb64ee96bf4f1d386a8",
          "md5": "959ee3bc3cf9b71bdaa985653834db36"
        }
      ]
    }
  ]
}
