{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-analytics",
    "version": "1.9.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.9.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-1.9.5.aar",
          "url": "nautilus-analytics-1.9.5.aar",
          "size": 173087,
          "sha512": "e44d8f491617f55266d661e9ef52d3d1bf021e6ea06c865e17ea46fd94ba155b5f8c5955a09357a7c7c03176ffb63c8d987caf1d7dd40615d1fee8a228bea46e",
          "sha256": "fb44ebf35bdfd5afe75adbe553d0ee7ca5873ebcba9a78c1d3151b2b141e227c",
          "sha1": "7236f106220cdce98e94562d47979304ed6f0aa2",
          "md5": "f4f98c49142c55680c1bcf095a505623"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.9.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-1.9.5.aar",
          "url": "nautilus-analytics-1.9.5.aar",
          "size": 173087,
          "sha512": "e44d8f491617f55266d661e9ef52d3d1bf021e6ea06c865e17ea46fd94ba155b5f8c5955a09357a7c7c03176ffb63c8d987caf1d7dd40615d1fee8a228bea46e",
          "sha256": "fb44ebf35bdfd5afe75adbe553d0ee7ca5873ebcba9a78c1d3151b2b141e227c",
          "sha1": "7236f106220cdce98e94562d47979304ed6f0aa2",
          "md5": "f4f98c49142c55680c1bcf095a505623"
        }
      ]
    }
  ]
}
