{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-analytics",
    "version": "1.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-1.5.0.aar",
          "url": "nautilus-analytics-1.5.0.aar",
          "size": 141330,
          "sha512": "85d5d370fce3119fd15e5c27f2976064a742ee37bc11be5d3498963c7295d3280f9224cb09f71f3dbc9ccfd9653d3ce8f180f13527748a23282ce9fba4510e85",
          "sha256": "09e811e0bcb207dcd8888b144dbf3ae9d85fd039460a4e9a125283ed79a14c84",
          "sha1": "2c40e1ca862e1d8c027d566e3237302127d9b9b5",
          "md5": "6bd990defea20f5280cab9f56cba9ec6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-1.5.0.aar",
          "url": "nautilus-analytics-1.5.0.aar",
          "size": 141330,
          "sha512": "85d5d370fce3119fd15e5c27f2976064a742ee37bc11be5d3498963c7295d3280f9224cb09f71f3dbc9ccfd9653d3ce8f180f13527748a23282ce9fba4510e85",
          "sha256": "09e811e0bcb207dcd8888b144dbf3ae9d85fd039460a4e9a125283ed79a14c84",
          "sha1": "2c40e1ca862e1d8c027d566e3237302127d9b9b5",
          "md5": "6bd990defea20f5280cab9f56cba9ec6"
        }
      ]
    }
  ]
}
