{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-tools-logging",
    "version": "1.5.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-logging-1.5.5.aar",
          "url": "nautilus-tools-logging-1.5.5.aar",
          "size": 16709,
          "sha512": "4c0a5548d8fe30a175f549c60b06b09a2d23db2af39c16c102b08d4c299819d8ebeebbd133f5363946933f10f9fe9548210ed8ed55c90dd3f128c0d249d6b36f",
          "sha256": "87040b621b473020dd32de88c6624c4b04b6a54dc7178111b7cd25eafbc96c7b",
          "sha1": "b7ec7a84a2cc196638deaf7e834915fe85137b47",
          "md5": "14798023d21fd35fb85b03df7c70aff6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-logging-1.5.5.aar",
          "url": "nautilus-tools-logging-1.5.5.aar",
          "size": 16709,
          "sha512": "4c0a5548d8fe30a175f549c60b06b09a2d23db2af39c16c102b08d4c299819d8ebeebbd133f5363946933f10f9fe9548210ed8ed55c90dd3f128c0d249d6b36f",
          "sha256": "87040b621b473020dd32de88c6624c4b04b6a54dc7178111b7cd25eafbc96c7b",
          "sha1": "b7ec7a84a2cc196638deaf7e834915fe85137b47",
          "md5": "14798023d21fd35fb85b03df7c70aff6"
        }
      ]
    }
  ]
}
