{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-code-image-providers",
    "version": "1.7.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-code-image-providers-1.7.10.aar",
          "url": "nautilus-code-image-providers-1.7.10.aar",
          "size": 12996,
          "sha512": "1d5a093247e5ece41175a4882f37d438d0517721379a962b5e0ad438924fc6cf70d03f54ad73e8a96f9b5ded07ad08c1f44fbd725f194fc1ac30d4af5ab044a8",
          "sha256": "d300dd3193161b13574aeeb92829102ef4b4c8ff4c065d7464849bf57c16f22e",
          "sha1": "ecd58367d592c72c31d5ac98352d2b9d95f64f49",
          "md5": "5a441aca09a5a74f1419854ffe9bc928"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-code-image-providers-1.7.10.aar",
          "url": "nautilus-code-image-providers-1.7.10.aar",
          "size": 12996,
          "sha512": "1d5a093247e5ece41175a4882f37d438d0517721379a962b5e0ad438924fc6cf70d03f54ad73e8a96f9b5ded07ad08c1f44fbd725f194fc1ac30d4af5ab044a8",
          "sha256": "d300dd3193161b13574aeeb92829102ef4b4c8ff4c065d7464849bf57c16f22e",
          "sha1": "ecd58367d592c72c31d5ac98352d2b9d95f64f49",
          "md5": "5a441aca09a5a74f1419854ffe9bc928"
        }
      ]
    }
  ]
}
