{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-datetime",
    "version": "1.5.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.5.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-datetime-1.5.5.aar",
          "url": "nautilus-util-datetime-1.5.5.aar",
          "size": 13929,
          "sha512": "c1f1ec8fa74074e9b279a5606f4f479230ad14b82dba2f80582d00d8fe962da3b64a59026078f41643ef13f432a84192055c39ebe08df3dde16a6941648a139e",
          "sha256": "d7ac66178a10d98d5ee0684b58c390aa24f58b41fb82231ee005f529c3d252c4",
          "sha1": "2605ce59e38dd02b5c1a1fe5ccf2ac575e939a4a",
          "md5": "a191e62048d972dade8a177af4701eaf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.5.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.jakewharton.threetenabp",
          "module": "threetenabp",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-datetime-1.5.5.aar",
          "url": "nautilus-util-datetime-1.5.5.aar",
          "size": 13929,
          "sha512": "c1f1ec8fa74074e9b279a5606f4f479230ad14b82dba2f80582d00d8fe962da3b64a59026078f41643ef13f432a84192055c39ebe08df3dde16a6941648a139e",
          "sha256": "d7ac66178a10d98d5ee0684b58c390aa24f58b41fb82231ee005f529c3d252c4",
          "sha1": "2605ce59e38dd02b5c1a1fe5ccf2ac575e939a4a",
          "md5": "a191e62048d972dade8a177af4701eaf"
        }
      ]
    }
  ]
}
