{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-analytics-amplitude-plugin",
    "version": "1.23.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.amplitude",
          "module": "analytics-android",
          "version": {
            "requires": "1.21.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-amplitude-plugin-1.23.9.aar",
          "url": "nautilus-analytics-amplitude-plugin-1.23.9.aar",
          "size": 5995,
          "sha512": "2038838fb918408ac67e213788d246acc393fc9f30a4a8d2382c55cdede4fd1218c48a02308117dfcb20bdc83e77b8921042bf9e14db006685e67453eb062c24",
          "sha256": "ed5f59871b4d026edf9ff6a6e6fb429182b7410d4cc17d5ce2370bfe409a0d3e",
          "sha1": "6bb11d42b55f9311b753da6492657fd44036512c",
          "md5": "e1b12050134e7671d2fceabf35070599"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.amplitude",
          "module": "plugin-session-replay-android",
          "version": {
            "requires": "0.20.12"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-analytics",
          "version": {
            "requires": "1.23.9"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.23.9"
          }
        },
        {
          "group": "com.amplitude",
          "module": "analytics-android",
          "version": {
            "requires": "1.21.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-amplitude-plugin-1.23.9.aar",
          "url": "nautilus-analytics-amplitude-plugin-1.23.9.aar",
          "size": 5995,
          "sha512": "2038838fb918408ac67e213788d246acc393fc9f30a4a8d2382c55cdede4fd1218c48a02308117dfcb20bdc83e77b8921042bf9e14db006685e67453eb062c24",
          "sha256": "ed5f59871b4d026edf9ff6a6e6fb429182b7410d4cc17d5ce2370bfe409a0d3e",
          "sha1": "6bb11d42b55f9311b753da6492657fd44036512c",
          "md5": "e1b12050134e7671d2fceabf35070599"
        }
      ]
    }
  ]
}
