{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-code-image-providers",
    "version": "1.19.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.19.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-code-image-providers-1.19.12.aar",
          "url": "nautilus-code-image-providers-1.19.12.aar",
          "size": 12790,
          "sha512": "8afb6f8c4a6385d3eacb7470c3c6ee12a9e844e2fa64e817bc69f731e191d13e18136d2e69b59db11af0308879856feec7ef29830e480b71153ef4b1fb36595f",
          "sha256": "2ac16b1d789e41c9b0585a06b29373be57b5aa4330b29d1df159b6b8bcb1b09e",
          "sha1": "d2c01c541ea69360403ec6beea21514f9059b146",
          "md5": "0fdc089b9bb4713bd7f27aca1993d216"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.19.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-code-image-providers-1.19.12.aar",
          "url": "nautilus-code-image-providers-1.19.12.aar",
          "size": 12790,
          "sha512": "8afb6f8c4a6385d3eacb7470c3c6ee12a9e844e2fa64e817bc69f731e191d13e18136d2e69b59db11af0308879856feec7ef29830e480b71153ef4b1fb36595f",
          "sha256": "2ac16b1d789e41c9b0585a06b29373be57b5aa4330b29d1df159b6b8bcb1b09e",
          "sha1": "d2c01c541ea69360403ec6beea21514f9059b146",
          "md5": "0fdc089b9bb4713bd7f27aca1993d216"
        }
      ]
    }
  ]
}
