{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-analytics",
    "version": "1.19.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.19.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-1.19.1.aar",
          "url": "nautilus-analytics-1.19.1.aar",
          "size": 165860,
          "sha512": "a53bf399497286b26b20b6afd68cda09b26db0387ad0029183e0e52340c827514a38ca2bb3bb8a9bdd01580530ae016889dd4726b9e39140972764fada090233",
          "sha256": "4d91e367dfa9a71ec889110ddbf4a3a473f69639d0df59b99ca1961609b62a32",
          "sha1": "db6723927748b1888008774290b3c4906980a89b",
          "md5": "6fc3e67313ab55533b9d9fe3bbb6e8e6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.19.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-1.19.1.aar",
          "url": "nautilus-analytics-1.19.1.aar",
          "size": 165860,
          "sha512": "a53bf399497286b26b20b6afd68cda09b26db0387ad0029183e0e52340c827514a38ca2bb3bb8a9bdd01580530ae016889dd4726b9e39140972764fada090233",
          "sha256": "4d91e367dfa9a71ec889110ddbf4a3a473f69639d0df59b99ca1961609b62a32",
          "sha1": "db6723927748b1888008774290b3c4906980a89b",
          "md5": "6fc3e67313ab55533b9d9fe3bbb6e8e6"
        }
      ]
    }
  ]
}
