{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-map",
    "version": "1.19.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-map-1.19.6.aar",
          "url": "nautilus-util-map-1.19.6.aar",
          "size": 10422,
          "sha512": "e781eb6ffb5ca1e246c5071bd34fb0664f6f85344dbc4078c6bcf0882179a9dd2f440a30929466bb857cfdae5b90972ff366ef3651c800356a531f73704f7aaa",
          "sha256": "93bcd2c0a71d139f240b9467f5fb63a8cb16f0ad30f8de91383dc7550ae516a1",
          "sha1": "b9218e77da98318f74af0dd765b0d31285fc2891",
          "md5": "5a802cd3f18bc724eff20b58125e666c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-maps",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-map-1.19.6.aar",
          "url": "nautilus-util-map-1.19.6.aar",
          "size": 10422,
          "sha512": "e781eb6ffb5ca1e246c5071bd34fb0664f6f85344dbc4078c6bcf0882179a9dd2f440a30929466bb857cfdae5b90972ff366ef3651c800356a531f73704f7aaa",
          "sha256": "93bcd2c0a71d139f240b9467f5fb63a8cb16f0ad30f8de91383dc7550ae516a1",
          "sha1": "b9218e77da98318f74af0dd765b0d31285fc2891",
          "md5": "5a802cd3f18bc724eff20b58125e666c"
        }
      ]
    }
  ]
}
