{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-user-info",
    "version": "1.7.2-hotfix",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.7.2-hotfix"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-imaging",
          "version": {
            "requires": "1.7.2-hotfix"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-geo",
          "version": {
            "requires": "1.7.2-hotfix"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-datetime",
          "version": {
            "requires": "1.7.2-hotfix"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-config",
          "version": {
            "requires": "1.7.2-hotfix"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-view",
          "version": {
            "requires": "1.7.2-hotfix"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-livedata",
          "version": {
            "requires": "1.7.2-hotfix"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-user-info-1.7.2-hotfix.aar",
          "url": "nautilus-user-info-1.7.2-hotfix.aar",
          "size": 141469,
          "sha512": "4a65191726b8473710d46821a55902203044b36353e7e6930092ce8d9b112f023fb780aceb4e0f7e72e69f961ea4cd000668f852b75f53a86238587000186f28",
          "sha256": "d7639e48720f17183719cf253b2e17c7d2fce289d6e70d48739c0c4375361c02",
          "sha1": "487768a88ba313a01eda6b5d4b8d994012352a18",
          "md5": "9cb681bfe1a5d54c045689271d9b74e7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.7.2-hotfix"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-imaging",
          "version": {
            "requires": "1.7.2-hotfix"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-geo",
          "version": {
            "requires": "1.7.2-hotfix"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-datetime",
          "version": {
            "requires": "1.7.2-hotfix"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-config",
          "version": {
            "requires": "1.7.2-hotfix"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-view",
          "version": {
            "requires": "1.7.2-hotfix"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-livedata",
          "version": {
            "requires": "1.7.2-hotfix"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.3"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.4.3"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-user-info-1.7.2-hotfix.aar",
          "url": "nautilus-user-info-1.7.2-hotfix.aar",
          "size": 141469,
          "sha512": "4a65191726b8473710d46821a55902203044b36353e7e6930092ce8d9b112f023fb780aceb4e0f7e72e69f961ea4cd000668f852b75f53a86238587000186f28",
          "sha256": "d7639e48720f17183719cf253b2e17c7d2fce289d6e70d48739c0c4375361c02",
          "sha1": "487768a88ba313a01eda6b5d4b8d994012352a18",
          "md5": "9cb681bfe1a5d54c045689271d9b74e7"
        }
      ]
    }
  ]
}
