{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-tools-logging",
    "version": "1.17.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-logging-1.17.5.aar",
          "url": "nautilus-tools-logging-1.17.5.aar",
          "size": 19671,
          "sha512": "931d08df5881b43636e536bb968209ed57d38b0de211ce40b148c82c47e054671dafb3caff1d5590f2a3c2e4cf96e8f33e793f5e285253df96a1890e06473f35",
          "sha256": "bae156c79643f9964a111ea2d3ebbc2f0b6b633be5c953b7ed70b2f6379a4f7d",
          "sha1": "dbce18c5c1a2cf58e2a12a3b5a5d0a500e065c5a",
          "md5": "108adcfb58b18e3995a81fb1528c57a1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-logging-1.17.5.aar",
          "url": "nautilus-tools-logging-1.17.5.aar",
          "size": 19671,
          "sha512": "931d08df5881b43636e536bb968209ed57d38b0de211ce40b148c82c47e054671dafb3caff1d5590f2a3c2e4cf96e8f33e793f5e285253df96a1890e06473f35",
          "sha256": "bae156c79643f9964a111ea2d3ebbc2f0b6b633be5c953b7ed70b2f6379a4f7d",
          "sha1": "dbce18c5c1a2cf58e2a12a3b5a5d0a500e065c5a",
          "md5": "108adcfb58b18e3995a81fb1528c57a1"
        }
      ]
    }
  ]
}
