{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-maintenance",
    "version": "1.16.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-network",
          "version": {
            "requires": "1.16.6"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.16.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-maintenance-1.16.6.aar",
          "url": "nautilus-maintenance-1.16.6.aar",
          "size": 41108,
          "sha512": "15d0e40eb7b8a50c3f55882ef8ebd9ccc318ea8b777331642b281d2271f3337178d92cb35f3173eb22f729ad93c73efc3c092f874ff1278afec2f7a6051fa673",
          "sha256": "9ab0ce30eeb3446ba755a9f1e840d3785ff2a1ebc9050253d134423c98472da4",
          "sha1": "ddf77a2af82e4c3ec018c8cadc83401505788e7e",
          "md5": "7a69ac75195f1abfc83773c9730e1f89"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-network",
          "version": {
            "requires": "1.16.6"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.16.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-maintenance-1.16.6.aar",
          "url": "nautilus-maintenance-1.16.6.aar",
          "size": 41108,
          "sha512": "15d0e40eb7b8a50c3f55882ef8ebd9ccc318ea8b777331642b281d2271f3337178d92cb35f3173eb22f729ad93c73efc3c092f874ff1278afec2f7a6051fa673",
          "sha256": "9ab0ce30eeb3446ba755a9f1e840d3785ff2a1ebc9050253d134423c98472da4",
          "sha1": "ddf77a2af82e4c3ec018c8cadc83401505788e7e",
          "md5": "7a69ac75195f1abfc83773c9730e1f89"
        }
      ]
    }
  ]
}
