{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-tools-cryptography",
    "version": "1.13.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-cryptography-1.13.6.aar",
          "url": "nautilus-tools-cryptography-1.13.6.aar",
          "size": 26312,
          "sha512": "d724827ca660ff13eec578902e99ee41fd7ea8da3e99ed58e2b32581a4a5df2b3a4f61392032cfbaeefa7b7f6abbb2dfcdc8e6c4e692d45d079957dadce5b748",
          "sha256": "f3675248364c9bed35d7de88f5fd994b42f63ea51336bd9482ab6add011af080",
          "sha1": "ea8f5c08e1f71411a753397155dc35252509b1a7",
          "md5": "b229f436b162c1b892322d95cd3ab452"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-cryptography-1.13.6.aar",
          "url": "nautilus-tools-cryptography-1.13.6.aar",
          "size": 26312,
          "sha512": "d724827ca660ff13eec578902e99ee41fd7ea8da3e99ed58e2b32581a4a5df2b3a4f61392032cfbaeefa7b7f6abbb2dfcdc8e6c4e692d45d079957dadce5b748",
          "sha256": "f3675248364c9bed35d7de88f5fd994b42f63ea51336bd9482ab6add011af080",
          "sha1": "ea8f5c08e1f71411a753397155dc35252509b1a7",
          "md5": "b229f436b162c1b892322d95cd3ab452"
        }
      ]
    }
  ]
}
