{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-datetime",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-datetime-1.4.0.aar",
          "url": "nautilus-util-datetime-1.4.0.aar",
          "size": 13931,
          "sha512": "69cd4cfa564616deb57eecf3ad14de2fec4c4ce220a873d3cb7016bc346728a41ce2aa9bfa11721d05e301c72ada4f4ee4499a2b5c8bd44a46e19efee02e5fb5",
          "sha256": "68cbfb7d7fa89515d10da83ab877205acf61f50709838f1f93340c4733dea41b",
          "sha1": "89ee50e5d2e9fbc40b5589fef602116b903e0976",
          "md5": "787d7dfe9283cdb5e349f8756cda38b9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.jakewharton.threetenabp",
          "module": "threetenabp",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-datetime-1.4.0.aar",
          "url": "nautilus-util-datetime-1.4.0.aar",
          "size": 13931,
          "sha512": "69cd4cfa564616deb57eecf3ad14de2fec4c4ce220a873d3cb7016bc346728a41ce2aa9bfa11721d05e301c72ada4f4ee4499a2b5c8bd44a46e19efee02e5fb5",
          "sha256": "68cbfb7d7fa89515d10da83ab877205acf61f50709838f1f93340c4733dea41b",
          "sha1": "89ee50e5d2e9fbc40b5589fef602116b903e0976",
          "md5": "787d7dfe9283cdb5e349f8756cda38b9"
        }
      ]
    }
  ]
}
