{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-code-image-providers",
    "version": "1.19.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.19.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-code-image-providers-1.19.5.aar",
          "url": "nautilus-code-image-providers-1.19.5.aar",
          "size": 12791,
          "sha512": "b1ded0b4f294475ddd41c5afd3d72fac57df4ea8541ffcf62f0ad30faaf433fefa4ec44b424faa4816f197d50481778aa8798e083d727440d571a8b4cbbabc84",
          "sha256": "79c01c30d3fc5112b9e347a4c665cd8e5b3a247f7902c4f93a77368f2528b68b",
          "sha1": "4fee3b3b197689e32ae88dbbba7199d00ffcd839",
          "md5": "fb406702458c3a337e4e76e482c7ebec"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.19.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-code-image-providers-1.19.5.aar",
          "url": "nautilus-code-image-providers-1.19.5.aar",
          "size": 12791,
          "sha512": "b1ded0b4f294475ddd41c5afd3d72fac57df4ea8541ffcf62f0ad30faaf433fefa4ec44b424faa4816f197d50481778aa8798e083d727440d571a8b4cbbabc84",
          "sha256": "79c01c30d3fc5112b9e347a4c665cd8e5b3a247f7902c4f93a77368f2528b68b",
          "sha1": "4fee3b3b197689e32ae88dbbba7199d00ffcd839",
          "md5": "fb406702458c3a337e4e76e482c7ebec"
        }
      ]
    }
  ]
}
