{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-core",
    "version": "1.12.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.12.9"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-cryptography",
          "version": {
            "requires": "1.12.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-core-1.12.9.aar",
          "url": "nautilus-core-1.12.9.aar",
          "size": 108600,
          "sha512": "d22b93914fe212971517349182d35b4e5dde3df463b09a35fb17f78bbbfbb7b399fc0dcddf72db69ba914af64f4a53b5333457b5c43c322099c59dc00c8597f3",
          "sha256": "3bc2bbf367775828af164eace379692d103e61e555296e4d95992178ee8e181d",
          "sha1": "cdd9250023f61b8cbc118d7dfdaf363cd72c1e5f",
          "md5": "890e9818c769744e5b5e43b0f250b3e0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.12.9"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-cryptography",
          "version": {
            "requires": "1.12.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-core-1.12.9.aar",
          "url": "nautilus-core-1.12.9.aar",
          "size": 108600,
          "sha512": "d22b93914fe212971517349182d35b4e5dde3df463b09a35fb17f78bbbfbb7b399fc0dcddf72db69ba914af64f4a53b5333457b5c43c322099c59dc00c8597f3",
          "sha256": "3bc2bbf367775828af164eace379692d103e61e555296e4d95992178ee8e181d",
          "sha1": "cdd9250023f61b8cbc118d7dfdaf363cd72c1e5f",
          "md5": "890e9818c769744e5b5e43b0f250b3e0"
        }
      ]
    }
  ]
}
