{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-server-time",
    "version": "1.17.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.17.3"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-network",
          "version": {
            "requires": "1.17.3"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-config",
          "version": {
            "requires": "1.17.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-server-time-1.17.3.aar",
          "url": "nautilus-server-time-1.17.3.aar",
          "size": 76753,
          "sha512": "be32c2563c33ef70cb645f7dbdee3ce9d90ab399adb19efeead53cb90d0c5e8c87bd631d6896de8c343df0b2841d2f5714f3c176d4de1d09e2749f3ff444e96c",
          "sha256": "ff3ac6c7626219e44826929d8e30fd5af1b2426429356bc6e4befed9280c5742",
          "sha1": "53623782e06792c2bfe59917ce06678741b2e881",
          "md5": "53fcf0e6fb17ec4ac96fa943521fe06d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.17.3"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-network",
          "version": {
            "requires": "1.17.3"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-config",
          "version": {
            "requires": "1.17.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-server-time-1.17.3.aar",
          "url": "nautilus-server-time-1.17.3.aar",
          "size": 76753,
          "sha512": "be32c2563c33ef70cb645f7dbdee3ce9d90ab399adb19efeead53cb90d0c5e8c87bd631d6896de8c343df0b2841d2f5714f3c176d4de1d09e2749f3ff444e96c",
          "sha256": "ff3ac6c7626219e44826929d8e30fd5af1b2426429356bc6e4befed9280c5742",
          "sha1": "53623782e06792c2bfe59917ce06678741b2e881",
          "md5": "53fcf0e6fb17ec4ac96fa943521fe06d"
        }
      ]
    }
  ]
}
