{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-maintenance",
    "version": "1.15.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-network",
          "version": {
            "requires": "1.15.3"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.15.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-maintenance-1.15.3.aar",
          "url": "nautilus-maintenance-1.15.3.aar",
          "size": 41119,
          "sha512": "a4ff8866d860686d463fc5cc1098e9dcb8025c58c73e313397802ee56df16b723a40bc36f2e2eeece3d2f4c6e16e1f7c71fda9309ec567a21559e86b581108ca",
          "sha256": "0f571cc15886e8357c17bc98d6b6c1fb5c1959822107b0fe13b28e8493808c2b",
          "sha1": "ff3c817723ac123412afb1e736fa58a19ba08503",
          "md5": "921d96dcb0fb551cacb0da1eca847982"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-network",
          "version": {
            "requires": "1.15.3"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.15.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-maintenance-1.15.3.aar",
          "url": "nautilus-maintenance-1.15.3.aar",
          "size": 41119,
          "sha512": "a4ff8866d860686d463fc5cc1098e9dcb8025c58c73e313397802ee56df16b723a40bc36f2e2eeece3d2f4c6e16e1f7c71fda9309ec567a21559e86b581108ca",
          "sha256": "0f571cc15886e8357c17bc98d6b6c1fb5c1959822107b0fe13b28e8493808c2b",
          "sha1": "ff3c817723ac123412afb1e736fa58a19ba08503",
          "md5": "921d96dcb0fb551cacb0da1eca847982"
        }
      ]
    }
  ]
}
