{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-core",
    "version": "1.6.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-cryptography",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-core-1.6.4.aar",
          "url": "nautilus-core-1.6.4.aar",
          "size": 85635,
          "sha512": "f31ed1cdd271bf792d73caae54904cf127cc14bcc351d2b6faed4437e38cdea0fae2e07575998cd614da8a53f5617429a5f119500bd22fef4d415776ff20703c",
          "sha256": "bba92f01d4f484b0792162a821dc85bfada921ea5a81c05b2a89d2bd4a226cd0",
          "sha1": "b30634ad416cba89a8c81ad95de9fcfa8283e17b",
          "md5": "8afc3e4f1c09df63fdfb0067d868a097"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-cryptography",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-core-1.6.4.aar",
          "url": "nautilus-core-1.6.4.aar",
          "size": 85635,
          "sha512": "f31ed1cdd271bf792d73caae54904cf127cc14bcc351d2b6faed4437e38cdea0fae2e07575998cd614da8a53f5617429a5f119500bd22fef4d415776ff20703c",
          "sha256": "bba92f01d4f484b0792162a821dc85bfada921ea5a81c05b2a89d2bd4a226cd0",
          "sha1": "b30634ad416cba89a8c81ad95de9fcfa8283e17b",
          "md5": "8afc3e4f1c09df63fdfb0067d868a097"
        }
      ]
    }
  ]
}
