{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-analytics-amplitude-plugin",
    "version": "1.7.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.amplitude",
          "module": "android-sdk",
          "version": {
            "requires": "2.38.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-amplitude-plugin-1.7.18.aar",
          "url": "nautilus-analytics-amplitude-plugin-1.7.18.aar",
          "size": 11797,
          "sha512": "0f900a0c0b0214a7508ed2c373ed45f092cfa55a0c9eed3dd8a463cba6886e85130a133916b264069bb4713491f9fe3321c3488159dc72c32697f75add8a1ab7",
          "sha256": "5c0eb79d4cf9df8a0dba991fcbd3bd23e1b118b6da628ea58d405b8f59032a70",
          "sha1": "060252dc5b1451b134fcf45a064bf953d02d0e44",
          "md5": "33ad90afbd12ef4321bf6e3c7cc3c5e0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.amplitude",
          "module": "android-sdk",
          "version": {
            "requires": "2.38.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-analytics",
          "version": {
            "requires": "1.7.18"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.7.18"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-amplitude-plugin-1.7.18.aar",
          "url": "nautilus-analytics-amplitude-plugin-1.7.18.aar",
          "size": 11797,
          "sha512": "0f900a0c0b0214a7508ed2c373ed45f092cfa55a0c9eed3dd8a463cba6886e85130a133916b264069bb4713491f9fe3321c3488159dc72c32697f75add8a1ab7",
          "sha256": "5c0eb79d4cf9df8a0dba991fcbd3bd23e1b118b6da628ea58d405b8f59032a70",
          "sha1": "060252dc5b1451b134fcf45a064bf953d02d0e44",
          "md5": "33ad90afbd12ef4321bf6e3c7cc3c5e0"
        }
      ]
    }
  ]
}
