{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-core",
    "version": "1.16.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.16.2"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-cryptography",
          "version": {
            "requires": "1.16.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-core-1.16.2.aar",
          "url": "nautilus-core-1.16.2.aar",
          "size": 107557,
          "sha512": "302b1411d88f543b81ecc172c55337e7436b04ae87b138f1c57d72efd2cdf762664531673e55b2f0af37836dc0587b3936305fdc80e8a04425fbced33eaa314c",
          "sha256": "aa0a9399ba2d32c9627a7115aaac4405d7dd90f261ff3471ac87090e9096a439",
          "sha1": "b9ec8a0d6347f973c2ed38d351700d5e863593bd",
          "md5": "9ba660df8dca0c9fcf7d3a09182c0b47"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.16.2"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-cryptography",
          "version": {
            "requires": "1.16.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-core-1.16.2.aar",
          "url": "nautilus-core-1.16.2.aar",
          "size": 107557,
          "sha512": "302b1411d88f543b81ecc172c55337e7436b04ae87b138f1c57d72efd2cdf762664531673e55b2f0af37836dc0587b3936305fdc80e8a04425fbced33eaa314c",
          "sha256": "aa0a9399ba2d32c9627a7115aaac4405d7dd90f261ff3471ac87090e9096a439",
          "sha1": "b9ec8a0d6347f973c2ed38d351700d5e863593bd",
          "md5": "9ba660df8dca0c9fcf7d3a09182c0b47"
        }
      ]
    }
  ]
}
