{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-code-image-providers",
    "version": "1.19.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.19.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-code-image-providers-1.19.22.aar",
          "url": "nautilus-code-image-providers-1.19.22.aar",
          "size": 12777,
          "sha512": "6b8fdad38e14eacb6ab4aa22802d12047d373cc9e93d493afbb3196bf67c78dffa9883d17595b8d50c980de069f67d4bd60a15ce6cfee861bdcb1f21061debae",
          "sha256": "7b09d6d109f9b3da2042f4f3108c2d49560dfc25a8974295e1fa174005c206f6",
          "sha1": "9558cf8d68bcbf023eff96965a4f8d5532d562b0",
          "md5": "7b00faef59cd0730f2cf5755f92c5f55"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.19.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-code-image-providers-1.19.22.aar",
          "url": "nautilus-code-image-providers-1.19.22.aar",
          "size": 12777,
          "sha512": "6b8fdad38e14eacb6ab4aa22802d12047d373cc9e93d493afbb3196bf67c78dffa9883d17595b8d50c980de069f67d4bd60a15ce6cfee861bdcb1f21061debae",
          "sha256": "7b09d6d109f9b3da2042f4f3108c2d49560dfc25a8974295e1fa174005c206f6",
          "sha1": "9558cf8d68bcbf023eff96965a4f8d5532d562b0",
          "md5": "7b00faef59cd0730f2cf5755f92c5f55"
        }
      ]
    }
  ]
}
