{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-core",
    "version": "1.18.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.18.2"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-cryptography",
          "version": {
            "requires": "1.18.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-core-1.18.2.aar",
          "url": "nautilus-core-1.18.2.aar",
          "size": 107550,
          "sha512": "87eb6f2ccfba3e78f73c83a19f9da3efd9dfe880ddcb426950768da66693382dcbda51506fbfe355bdab0458ce21787359eb5a7ad592ec8ca7913a175c4e3bf7",
          "sha256": "bed046e6c174c68b0e22fed1296f68f7c10e73041c01a0f56c4e58d8269123a5",
          "sha1": "9f038736e509741f20452961b616c6a9ec37a47c",
          "md5": "21be349663c4470c13ffb4cc0f4393cd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.18.2"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-cryptography",
          "version": {
            "requires": "1.18.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-core-1.18.2.aar",
          "url": "nautilus-core-1.18.2.aar",
          "size": 107550,
          "sha512": "87eb6f2ccfba3e78f73c83a19f9da3efd9dfe880ddcb426950768da66693382dcbda51506fbfe355bdab0458ce21787359eb5a7ad592ec8ca7913a175c4e3bf7",
          "sha256": "bed046e6c174c68b0e22fed1296f68f7c10e73041c01a0f56c4e58d8269123a5",
          "sha1": "9f038736e509741f20452961b616c6a9ec37a47c",
          "md5": "21be349663c4470c13ffb4cc0f4393cd"
        }
      ]
    }
  ]
}
