{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-analytics",
    "version": "1.20.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.20.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-1.20.0.aar",
          "url": "nautilus-analytics-1.20.0.aar",
          "size": 165863,
          "sha512": "35c9c952f1d332db0334cae076bb4e335781b08d793056369a1f2c8fb8eba724712374e44c8d82f736bc31a1d644fe84dccc4caf8992170909cb7d5f467e910f",
          "sha256": "942068d6a9c8d8ef675fd1782aa44092e1b8a991e3fa7eb18e4756dd7aa599ea",
          "sha1": "3f3ef77f2fbe38bd0c77396221ede9635c5910ba",
          "md5": "24d45aa4b2cfaeb10206ba04e3c9d7ec"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.20.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-1.20.0.aar",
          "url": "nautilus-analytics-1.20.0.aar",
          "size": 165863,
          "sha512": "35c9c952f1d332db0334cae076bb4e335781b08d793056369a1f2c8fb8eba724712374e44c8d82f736bc31a1d644fe84dccc4caf8992170909cb7d5f467e910f",
          "sha256": "942068d6a9c8d8ef675fd1782aa44092e1b8a991e3fa7eb18e4756dd7aa599ea",
          "sha1": "3f3ef77f2fbe38bd0c77396221ede9635c5910ba",
          "md5": "24d45aa4b2cfaeb10206ba04e3c9d7ec"
        }
      ]
    }
  ]
}
