{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-code-image-providers",
    "version": "1.16.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.16.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-code-image-providers-1.16.2.aar",
          "url": "nautilus-code-image-providers-1.16.2.aar",
          "size": 12787,
          "sha512": "e9f46aa74b16c65c67cfea928a4d13e6c55edff6220b932ba888cd8efb12ddee82be291e393dc3d7f6910ab63cebdba962f6245adb8ecbea728bc36d8b5cb463",
          "sha256": "131c8edeb174fdc7d1577e050eb24b41fd07ec9b78e3299a04fdd90c56984ee3",
          "sha1": "3a8585ac5d91e7c0d66931e8e571f6c6b9a1ea41",
          "md5": "aa622f1bb48c6046f70c3f3ff1e88901"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.16.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-code-image-providers-1.16.2.aar",
          "url": "nautilus-code-image-providers-1.16.2.aar",
          "size": 12787,
          "sha512": "e9f46aa74b16c65c67cfea928a4d13e6c55edff6220b932ba888cd8efb12ddee82be291e393dc3d7f6910ab63cebdba962f6245adb8ecbea728bc36d8b5cb463",
          "sha256": "131c8edeb174fdc7d1577e050eb24b41fd07ec9b78e3299a04fdd90c56984ee3",
          "sha1": "3a8585ac5d91e7c0d66931e8e571f6c6b9a1ea41",
          "md5": "aa622f1bb48c6046f70c3f3ff1e88901"
        }
      ]
    }
  ]
}
