{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-json",
    "version": "1.9.5-hotfix1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-json-1.9.5-hotfix1.aar",
          "url": "nautilus-util-json-1.9.5-hotfix1.aar",
          "size": 11369,
          "sha512": "eea54f8a1e18dad0958ed6ca3e63023be4ac86a576b67f08177cf387eee99236021d312c4af958c27110fb3b271db1e412534ae0e758eac49fa2cdcf0cb08ce7",
          "sha256": "f35b1d7d02d037bf5312363efd331495c3ddc90cf02667815c51d93eca780ed0",
          "sha1": "243a0c35491914364430fbcaa175292ffa4722a3",
          "md5": "ad95adea44d8a5bc8b97877059913131"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-json-1.9.5-hotfix1.aar",
          "url": "nautilus-util-json-1.9.5-hotfix1.aar",
          "size": 11369,
          "sha512": "eea54f8a1e18dad0958ed6ca3e63023be4ac86a576b67f08177cf387eee99236021d312c4af958c27110fb3b271db1e412534ae0e758eac49fa2cdcf0cb08ce7",
          "sha256": "f35b1d7d02d037bf5312363efd331495c3ddc90cf02667815c51d93eca780ed0",
          "sha1": "243a0c35491914364430fbcaa175292ffa4722a3",
          "md5": "ad95adea44d8a5bc8b97877059913131"
        }
      ]
    }
  ]
}
