{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-format",
    "version": "1.5.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.5.3.aar",
          "url": "nautilus-util-format-1.5.3.aar",
          "size": 8820,
          "sha512": "9db34db5c4e2fbaab265e73cf2c9a55a29f61b7078cacf3e1530f5d4f76f2e0007c68270bde751617e47066d1475dd06d97c01d635306b232911bd43b0561569",
          "sha256": "75c36410e7b14b647e36e97df19a19477781002bfbc2b89fd8327405ea5f0adb",
          "sha1": "3226340fd97754bb4e0406ad42aa5baf62163194",
          "md5": "150d1d942ae28de19ef302fa2e741d56"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.5.3.aar",
          "url": "nautilus-util-format-1.5.3.aar",
          "size": 8820,
          "sha512": "9db34db5c4e2fbaab265e73cf2c9a55a29f61b7078cacf3e1530f5d4f76f2e0007c68270bde751617e47066d1475dd06d97c01d635306b232911bd43b0561569",
          "sha256": "75c36410e7b14b647e36e97df19a19477781002bfbc2b89fd8327405ea5f0adb",
          "sha1": "3226340fd97754bb4e0406ad42aa5baf62163194",
          "md5": "150d1d942ae28de19ef302fa2e741d56"
        }
      ]
    }
  ]
}
