{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-network",
    "version": "1.7.28",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.7.28"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.7.28.aar",
          "url": "nautilus-util-network-1.7.28.aar",
          "size": 22702,
          "sha512": "0268a39da52bd8fa83ec9839987d13d9f8bef19f59e78b8dab99d431e0cb4a801acabf42021d5ab6047d95b19d9a71857c3000e20ba0deb895af24fc3fbf593b",
          "sha256": "7f49cf683efb1d054aac2988ce9b1dedac5d0d29d0ae35da2edd8eaf3377ef6e",
          "sha1": "fafc089200903ea11bf6b480ffbbe4d72f315ace",
          "md5": "28db9a4ae346904fd16ad72dc6f2b404"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.7.28"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.7.28.aar",
          "url": "nautilus-util-network-1.7.28.aar",
          "size": 22702,
          "sha512": "0268a39da52bd8fa83ec9839987d13d9f8bef19f59e78b8dab99d431e0cb4a801acabf42021d5ab6047d95b19d9a71857c3000e20ba0deb895af24fc3fbf593b",
          "sha256": "7f49cf683efb1d054aac2988ce9b1dedac5d0d29d0ae35da2edd8eaf3377ef6e",
          "sha1": "fafc089200903ea11bf6b480ffbbe4d72f315ace",
          "md5": "28db9a4ae346904fd16ad72dc6f2b404"
        }
      ]
    }
  ]
}
