{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-config",
    "version": "1.15.5-feu1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.15.5-feu1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-config-1.15.5-feu1.aar",
          "url": "nautilus-config-1.15.5-feu1.aar",
          "size": 151020,
          "sha512": "6b12585d1593c74fd6bb5a95d0883be5003383e49bac7fd96f4a06c136f07e8a006c8d6f5ed93a0ea3dc61e63e3f65020ccc295ed9072df7a619781e12088e1f",
          "sha256": "1509f77efdd2bc11bc2ed9e2c7058420474ca348374d0d398c5040921ad03dee",
          "sha1": "c34e40bce2716cbee7bed1e80d3d685b9b2108cc",
          "md5": "375668e2d2823569480dfae9617db6c0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.15.5-feu1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-config-1.15.5-feu1.aar",
          "url": "nautilus-config-1.15.5-feu1.aar",
          "size": 151020,
          "sha512": "6b12585d1593c74fd6bb5a95d0883be5003383e49bac7fd96f4a06c136f07e8a006c8d6f5ed93a0ea3dc61e63e3f65020ccc295ed9072df7a619781e12088e1f",
          "sha256": "1509f77efdd2bc11bc2ed9e2c7058420474ca348374d0d398c5040921ad03dee",
          "sha1": "c34e40bce2716cbee7bed1e80d3d685b9b2108cc",
          "md5": "375668e2d2823569480dfae9617db6c0"
        }
      ]
    }
  ]
}
