{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-analytics-amplitude-plugin",
    "version": "1.17.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.amplitude",
          "module": "android-sdk",
          "version": {
            "requires": "2.40.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-amplitude-plugin-1.17.1.aar",
          "url": "nautilus-analytics-amplitude-plugin-1.17.1.aar",
          "size": 11350,
          "sha512": "2f51edafe668f8dd2278eef1999587bf8f298d45f0e72c1020ac15926d6f6a6b967ca35d55820ece8261ab938c48a84d2ffa8a12528b5fe328aaf851c7f4cd7b",
          "sha256": "3411a8ff9578fecee6c268b25f65d421df432becab7b8af2952cafd1d9eeda2d",
          "sha1": "d66b6564d0940adf6518d233101b46d2ae3d142d",
          "md5": "bb610c0e7d7691b8467fda704494b643"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-analytics",
          "version": {
            "requires": "1.17.1"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.17.1"
          }
        },
        {
          "group": "com.amplitude",
          "module": "android-sdk",
          "version": {
            "requires": "2.40.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-amplitude-plugin-1.17.1.aar",
          "url": "nautilus-analytics-amplitude-plugin-1.17.1.aar",
          "size": 11350,
          "sha512": "2f51edafe668f8dd2278eef1999587bf8f298d45f0e72c1020ac15926d6f6a6b967ca35d55820ece8261ab938c48a84d2ffa8a12528b5fe328aaf851c7f4cd7b",
          "sha256": "3411a8ff9578fecee6c268b25f65d421df432becab7b8af2952cafd1d9eeda2d",
          "sha1": "d66b6564d0940adf6518d233101b46d2ae3d142d",
          "md5": "bb610c0e7d7691b8467fda704494b643"
        }
      ]
    }
  ]
}
