{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-network",
    "version": "1.12.13-hotfix1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.12.13-hotfix1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.12.13-hotfix1.aar",
          "url": "nautilus-util-network-1.12.13-hotfix1.aar",
          "size": 23244,
          "sha512": "c5e7e61f5491b6a44b2adc58f9d4dba2a72bcef5880d24ca17f83da08c51a2b1867556fcff13d30c582eb6c2d514487abdfd3920e5d91036e0d3819a63a8ea46",
          "sha256": "9e4af17ef1dd4b73b4dca2ebc70d87cb3d7190a30dded49f3c892ff42d332bd9",
          "sha1": "69d5d1e7358d1f9c08edf3fd6d9cdd75b55e1e5e",
          "md5": "c598629b48da13c2f759315a5b50dbb9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.12.13-hotfix1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.12.13-hotfix1.aar",
          "url": "nautilus-util-network-1.12.13-hotfix1.aar",
          "size": 23244,
          "sha512": "c5e7e61f5491b6a44b2adc58f9d4dba2a72bcef5880d24ca17f83da08c51a2b1867556fcff13d30c582eb6c2d514487abdfd3920e5d91036e0d3819a63a8ea46",
          "sha256": "9e4af17ef1dd4b73b4dca2ebc70d87cb3d7190a30dded49f3c892ff42d332bd9",
          "sha1": "69d5d1e7358d1f9c08edf3fd6d9cdd75b55e1e5e",
          "md5": "c598629b48da13c2f759315a5b50dbb9"
        }
      ]
    }
  ]
}
