{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-format",
    "version": "1.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.6.2.aar",
          "url": "nautilus-util-format-1.6.2.aar",
          "size": 8814,
          "sha512": "78da168069ba9e81105b51c330c1be1d8076695526449f7a30b819ed944d9546e5ab2967d1fa6d6b853e3e68bc7f9aa24be5f8a37fcda52ce651bfa9bf487832",
          "sha256": "1f2368e639479f886fb9077ccda9871432f8f043b3cf587208766eff3d233e9a",
          "sha1": "f9b43a6b02900b987c9d14b6809f4837664792b5",
          "md5": "38f5fd6c7c25c65d2feb4e0907dafc0a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.6.2.aar",
          "url": "nautilus-util-format-1.6.2.aar",
          "size": 8814,
          "sha512": "78da168069ba9e81105b51c330c1be1d8076695526449f7a30b819ed944d9546e5ab2967d1fa6d6b853e3e68bc7f9aa24be5f8a37fcda52ce651bfa9bf487832",
          "sha256": "1f2368e639479f886fb9077ccda9871432f8f043b3cf587208766eff3d233e9a",
          "sha1": "f9b43a6b02900b987c9d14b6809f4837664792b5",
          "md5": "38f5fd6c7c25c65d2feb4e0907dafc0a"
        }
      ]
    }
  ]
}
