{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-network",
    "version": "1.7.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.7.18"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.7.18.aar",
          "url": "nautilus-util-network-1.7.18.aar",
          "size": 23668,
          "sha512": "00a5de13825b8bbd6bc2f4ac4e21390de6143af4c0e5c284b90350a48c44537f323f8fd5a9368b509f9820ba1c496fbc87fa51cfc611568be43830e2b96116ca",
          "sha256": "eb9509f5a43dfa8a4b00d1796c74cfe25225176abf1aafbd9961d342b4af4b89",
          "sha1": "87343c4fe6a828c1ee36184877e84b23edbe70b9",
          "md5": "e821c5fa189c019e0cd39de03f0f2b2f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.7.18"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.7.18.aar",
          "url": "nautilus-util-network-1.7.18.aar",
          "size": 23668,
          "sha512": "00a5de13825b8bbd6bc2f4ac4e21390de6143af4c0e5c284b90350a48c44537f323f8fd5a9368b509f9820ba1c496fbc87fa51cfc611568be43830e2b96116ca",
          "sha256": "eb9509f5a43dfa8a4b00d1796c74cfe25225176abf1aafbd9961d342b4af4b89",
          "sha1": "87343c4fe6a828c1ee36184877e84b23edbe70b9",
          "md5": "e821c5fa189c019e0cd39de03f0f2b2f"
        }
      ]
    }
  ]
}
