{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-tools-logging",
    "version": "1.7.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-logging-1.7.22.aar",
          "url": "nautilus-tools-logging-1.7.22.aar",
          "size": 19137,
          "sha512": "18775532ada5bfbe3683b1a5514abed647872088ecce8032a4b74fe9251803e07608ad7ecb590971dbc62ef4ddda77a2a43c44fc56ebb701f28662f7f8bc1219",
          "sha256": "5ff161fc23a96dd64745b2dee698e6ab6cf66259266fb26010da873a479e2c08",
          "sha1": "743a96348c3bb2c527cafa09233d3cf217f706f2",
          "md5": "4fa4e518ace2a55972bbef604e3d8686"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-logging-1.7.22.aar",
          "url": "nautilus-tools-logging-1.7.22.aar",
          "size": 19137,
          "sha512": "18775532ada5bfbe3683b1a5514abed647872088ecce8032a4b74fe9251803e07608ad7ecb590971dbc62ef4ddda77a2a43c44fc56ebb701f28662f7f8bc1219",
          "sha256": "5ff161fc23a96dd64745b2dee698e6ab6cf66259266fb26010da873a479e2c08",
          "sha1": "743a96348c3bb2c527cafa09233d3cf217f706f2",
          "md5": "4fa4e518ace2a55972bbef604e3d8686"
        }
      ]
    }
  ]
}
