{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-tools-cryptography",
    "version": "1.16.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-cryptography-1.16.3.aar",
          "url": "nautilus-tools-cryptography-1.16.3.aar",
          "size": 26321,
          "sha512": "9d8f52841d5549a6de4ec61483db99178710fbd3aca55d77177efaacb6b2be11df5fc99e89a39a62f56cb5a4b61b587ba89da20c8726a4a161f056e2add9f207",
          "sha256": "62d5a7a3e130f74401ba00079493d1e1e4c143c672dd3dc6d1683e5770f2cc1c",
          "sha1": "200b22fb249d4384a43909c7da86d7d8cfa0f686",
          "md5": "371d66d361d4ff6d2460463aa70b537e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-cryptography-1.16.3.aar",
          "url": "nautilus-tools-cryptography-1.16.3.aar",
          "size": 26321,
          "sha512": "9d8f52841d5549a6de4ec61483db99178710fbd3aca55d77177efaacb6b2be11df5fc99e89a39a62f56cb5a4b61b587ba89da20c8726a4a161f056e2add9f207",
          "sha256": "62d5a7a3e130f74401ba00079493d1e1e4c143c672dd3dc6d1683e5770f2cc1c",
          "sha1": "200b22fb249d4384a43909c7da86d7d8cfa0f686",
          "md5": "371d66d361d4ff6d2460463aa70b537e"
        }
      ]
    }
  ]
}
