{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-campaign",
    "version": "1.16.0-hotfix1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.16.0-hotfix1"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-format",
          "version": {
            "requires": "1.16.0-hotfix1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-campaign-1.16.0-hotfix1.aar",
          "url": "nautilus-campaign-1.16.0-hotfix1.aar",
          "size": 138274,
          "sha512": "4b36abc7c204dae31979a7cab3ff0ebdfcbe3b86d32ac02dc8ee23a9ecdbf21b02ee6c49a6b0d84fb90e88087f7ddebc00b1b56615d553af7d8b3949441d408b",
          "sha256": "538911b18464ee1c39396b1b13770fa119b9a1af5ebfd0183e34c0cab2df5f7e",
          "sha1": "de96cf514f686d0d16ed269ea143c46e857bd5e5",
          "md5": "fe2bc1ba40cb745ddb7f4bf9875b89d3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.16.0-hotfix1"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-format",
          "version": {
            "requires": "1.16.0-hotfix1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-campaign-1.16.0-hotfix1.aar",
          "url": "nautilus-campaign-1.16.0-hotfix1.aar",
          "size": 138274,
          "sha512": "4b36abc7c204dae31979a7cab3ff0ebdfcbe3b86d32ac02dc8ee23a9ecdbf21b02ee6c49a6b0d84fb90e88087f7ddebc00b1b56615d553af7d8b3949441d408b",
          "sha256": "538911b18464ee1c39396b1b13770fa119b9a1af5ebfd0183e34c0cab2df5f7e",
          "sha1": "de96cf514f686d0d16ed269ea143c46e857bd5e5",
          "md5": "fe2bc1ba40cb745ddb7f4bf9875b89d3"
        }
      ]
    }
  ]
}
