{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-stamp-rally-ui",
    "version": "1.14.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-code-reader",
          "version": {
            "requires": "1.14.3"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-server-time",
          "version": {
            "requires": "1.14.3"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-stamp",
          "version": {
            "requires": "1.14.3"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-map",
          "version": {
            "requires": "1.14.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-stamp-rally-ui-1.14.3.aar",
          "url": "nautilus-stamp-rally-ui-1.14.3.aar",
          "size": 471360,
          "sha512": "17fd181dc1564b84315e84b30e881887de4537d70a6ec34e1e64dcccdf73dc0b6ee0eef39c0a2632a0641c4f6f39f3011b15f029018424985ec1af12c58bc9da",
          "sha256": "c8737ffac4c94d8a13cf1d1f0a93c0eb83d707b6fb22c310f13c85f47e223f32",
          "sha1": "12210665af70ff465fa57fda52326335490f446f",
          "md5": "47e19aefeec95db703956f9bcd08d64d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-maps",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-code-reader",
          "version": {
            "requires": "1.14.3"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-server-time",
          "version": {
            "requires": "1.14.3"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-stamp",
          "version": {
            "requires": "1.14.3"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-map",
          "version": {
            "requires": "1.14.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-stamp-rally-ui-1.14.3.aar",
          "url": "nautilus-stamp-rally-ui-1.14.3.aar",
          "size": 471360,
          "sha512": "17fd181dc1564b84315e84b30e881887de4537d70a6ec34e1e64dcccdf73dc0b6ee0eef39c0a2632a0641c4f6f39f3011b15f029018424985ec1af12c58bc9da",
          "sha256": "c8737ffac4c94d8a13cf1d1f0a93c0eb83d707b6fb22c310f13c85f47e223f32",
          "sha1": "12210665af70ff465fa57fda52326335490f446f",
          "md5": "47e19aefeec95db703956f9bcd08d64d"
        }
      ]
    }
  ]
}
