{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-imaging",
    "version": "1.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-network",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-imaging-1.7.0.aar",
          "url": "nautilus-util-imaging-1.7.0.aar",
          "size": 11067,
          "sha512": "cbab8404d21f989e58407e7abf1a547f19e761f932d9af2e6172b3c77da4e63f8916bf6daa8bcaf845efa7cbaaa1c0dbf3c5b59148f02583de99d03c518838ab",
          "sha256": "a3d274cc2f2db1f10e2aea3b4aa0352eca46209163e7aacb8e1807cee33472e3",
          "sha1": "24afaf3529c725e4bde7dedea8b6bcd59a0b3eed",
          "md5": "77a5a9b7611b8012fcbfa06c34a727dd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-network",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-imaging-1.7.0.aar",
          "url": "nautilus-util-imaging-1.7.0.aar",
          "size": 11067,
          "sha512": "cbab8404d21f989e58407e7abf1a547f19e761f932d9af2e6172b3c77da4e63f8916bf6daa8bcaf845efa7cbaaa1c0dbf3c5b59148f02583de99d03c518838ab",
          "sha256": "a3d274cc2f2db1f10e2aea3b4aa0352eca46209163e7aacb8e1807cee33472e3",
          "sha1": "24afaf3529c725e4bde7dedea8b6bcd59a0b3eed",
          "md5": "77a5a9b7611b8012fcbfa06c34a727dd"
        }
      ]
    }
  ]
}
