{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-shop",
    "version": "1.12.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.12.5"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-analytics",
          "version": {
            "requires": "1.12.5"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-imaging",
          "version": {
            "requires": "1.12.5"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-geo",
          "version": {
            "requires": "1.12.5"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-config",
          "version": {
            "requires": "1.12.5"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-view",
          "version": {
            "requires": "1.12.5"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-format",
          "version": {
            "requires": "1.12.5"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-map",
          "version": {
            "requires": "1.12.5"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-shop-1.12.5.aar",
          "url": "nautilus-shop-1.12.5.aar",
          "size": 1405965,
          "sha512": "da41d88495aea756525e51399feb461fd885e8dac0c4008f9caad7bb205169425a8f1be1961f6af664c13c4159735a0fa587ade4def9e99287c18bb053040d61",
          "sha256": "b7fc80f7a6cc42b84ee688f04d900a46da0d215d19ead86ac4916989ec482769",
          "sha1": "212dee58d6d28132174a53585ab37b6e0e630ec7",
          "md5": "7537286ff112ca189072fbf21ee37052"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.3"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.4.3"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-maps",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.12.5"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-analytics",
          "version": {
            "requires": "1.12.5"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-imaging",
          "version": {
            "requires": "1.12.5"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-geo",
          "version": {
            "requires": "1.12.5"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-config",
          "version": {
            "requires": "1.12.5"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-view",
          "version": {
            "requires": "1.12.5"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-format",
          "version": {
            "requires": "1.12.5"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-map",
          "version": {
            "requires": "1.12.5"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-shop-1.12.5.aar",
          "url": "nautilus-shop-1.12.5.aar",
          "size": 1405965,
          "sha512": "da41d88495aea756525e51399feb461fd885e8dac0c4008f9caad7bb205169425a8f1be1961f6af664c13c4159735a0fa587ade4def9e99287c18bb053040d61",
          "sha256": "b7fc80f7a6cc42b84ee688f04d900a46da0d215d19ead86ac4916989ec482769",
          "sha1": "212dee58d6d28132174a53585ab37b6e0e630ec7",
          "md5": "7537286ff112ca189072fbf21ee37052"
        }
      ]
    }
  ]
}
