{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-analytics",
    "version": "1.12.2-hotfix3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.12.2-hotfix3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-1.12.2-hotfix3.aar",
          "url": "nautilus-analytics-1.12.2-hotfix3.aar",
          "size": 173978,
          "sha512": "5dac7b7baf50c133fdf419c99d3b88c0923d7852aa2c5c8d474783dc37c2bc17dc05dd9c586fd0e592e1ce37d86e28ffcaf87054b2a8023052644be7f6f1c2d0",
          "sha256": "c98910945d0edbb8e518007fd77248661f3cd649d9bac6af0e002d5de71f3d92",
          "sha1": "eb7405dea932b9e4527b84d9d3893544e30fe36b",
          "md5": "0335b321bbbcd2c84643909fe367ba77"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.12.2-hotfix3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-1.12.2-hotfix3.aar",
          "url": "nautilus-analytics-1.12.2-hotfix3.aar",
          "size": 173978,
          "sha512": "5dac7b7baf50c133fdf419c99d3b88c0923d7852aa2c5c8d474783dc37c2bc17dc05dd9c586fd0e592e1ce37d86e28ffcaf87054b2a8023052644be7f6f1c2d0",
          "sha256": "c98910945d0edbb8e518007fd77248661f3cd649d9bac6af0e002d5de71f3d92",
          "sha1": "eb7405dea932b9e4527b84d9d3893544e30fe36b",
          "md5": "0335b321bbbcd2c84643909fe367ba77"
        }
      ]
    }
  ]
}
