{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-config",
    "version": "1.15.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.15.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-config-1.15.4.aar",
          "url": "nautilus-config-1.15.4.aar",
          "size": 151020,
          "sha512": "1d62973a69658d5ee83774baf63122aef97dfec15dd6a162cc5c867b90a9b1348672fea74162472d3992a2a86291aae694aead2a0ad8d3defdc93b68c8b0af07",
          "sha256": "173ce0e71b931b2603dfd2755125ed5f0524c39f4eac3da069213b9dec8444fc",
          "sha1": "2b2e9a44128af12a3f66c8bf7dcf97bcb938ceba",
          "md5": "906f596b16fec05ff2e5b96e30f8d60b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.15.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-config-1.15.4.aar",
          "url": "nautilus-config-1.15.4.aar",
          "size": 151020,
          "sha512": "1d62973a69658d5ee83774baf63122aef97dfec15dd6a162cc5c867b90a9b1348672fea74162472d3992a2a86291aae694aead2a0ad8d3defdc93b68c8b0af07",
          "sha256": "173ce0e71b931b2603dfd2755125ed5f0524c39f4eac3da069213b9dec8444fc",
          "sha1": "2b2e9a44128af12a3f66c8bf7dcf97bcb938ceba",
          "md5": "906f596b16fec05ff2e5b96e30f8d60b"
        }
      ]
    }
  ]
}
