{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-tools-livedata",
    "version": "1.7.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-livedata-1.7.5.aar",
          "url": "nautilus-tools-livedata-1.7.5.aar",
          "size": 10336,
          "sha512": "a00073f7d3eb7f60302cb4d2592b44c51045537d6b1297ae92d27fdb69e1e26e958bf0e9f8cac09dbf23e42eb621cd271a72082d4ee5c6ea47961785e0ede291",
          "sha256": "61cd6f443aca97f4ec26472df41904db93023fcc8c593225d1d2c4ca4c7c9cc6",
          "sha1": "65e19a834244735108d84f95adb3487cec9596e4",
          "md5": "12ad1b6ccea3bc58b564f6c6d94bb1f9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-livedata-1.7.5.aar",
          "url": "nautilus-tools-livedata-1.7.5.aar",
          "size": 10336,
          "sha512": "a00073f7d3eb7f60302cb4d2592b44c51045537d6b1297ae92d27fdb69e1e26e958bf0e9f8cac09dbf23e42eb621cd271a72082d4ee5c6ea47961785e0ede291",
          "sha256": "61cd6f443aca97f4ec26472df41904db93023fcc8c593225d1d2c4ca4c7c9cc6",
          "sha1": "65e19a834244735108d84f95adb3487cec9596e4",
          "md5": "12ad1b6ccea3bc58b564f6c6d94bb1f9"
        }
      ]
    }
  ]
}
