{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-maintenance",
    "version": "1.19.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-network",
          "version": {
            "requires": "1.19.3"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.19.3"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-config",
          "version": {
            "requires": "1.19.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-maintenance-1.19.3.aar",
          "url": "nautilus-maintenance-1.19.3.aar",
          "size": 42159,
          "sha512": "b63e2f79d6143b6cc942554c45a3e9af53ad452ea883ac5e9ac4b415de7818fe15949d664a288d462f2f3dd73753833f92c89d3bdb9295f8475a21e990d6830b",
          "sha256": "e06ccb5f50a442fb3c66324ee175c631e1323635010537d940d930829feecf93",
          "sha1": "94237c6e13e7bfea6de83fe9adf33414cb533f07",
          "md5": "f0fd096f6d858fb1f10f630bff93fc84"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-network",
          "version": {
            "requires": "1.19.3"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.19.3"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-config",
          "version": {
            "requires": "1.19.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-maintenance-1.19.3.aar",
          "url": "nautilus-maintenance-1.19.3.aar",
          "size": 42159,
          "sha512": "b63e2f79d6143b6cc942554c45a3e9af53ad452ea883ac5e9ac4b415de7818fe15949d664a288d462f2f3dd73753833f92c89d3bdb9295f8475a21e990d6830b",
          "sha256": "e06ccb5f50a442fb3c66324ee175c631e1323635010537d940d930829feecf93",
          "sha1": "94237c6e13e7bfea6de83fe9adf33414cb533f07",
          "md5": "f0fd096f6d858fb1f10f630bff93fc84"
        }
      ]
    }
  ]
}
