{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-core",
    "version": "1.25.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.25.3"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-cryptography",
          "version": {
            "requires": "1.25.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-core-1.25.3.aar",
          "url": "nautilus-core-1.25.3.aar",
          "size": 85218,
          "sha512": "4cd63b7832dacbb4baa75c428037b0e375426930f735da7da9ed8d1a3160bc435c6406c8d152dc6a195dcbc51bda2152e6b5391d44f946e099b49caa8b5c1d46",
          "sha256": "5a5eb1496c27baceb206358485f00abfca58ba49a0a9c4bd294fb2c66afb34cb",
          "sha1": "590bff9594a69d397b4d32a2fc7ab2b3fa962c03",
          "md5": "33e949a6bd6a944cca2c8d66cff7376d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.18.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.25.3"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-cryptography",
          "version": {
            "requires": "1.25.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-core-1.25.3.aar",
          "url": "nautilus-core-1.25.3.aar",
          "size": 85218,
          "sha512": "4cd63b7832dacbb4baa75c428037b0e375426930f735da7da9ed8d1a3160bc435c6406c8d152dc6a195dcbc51bda2152e6b5391d44f946e099b49caa8b5c1d46",
          "sha256": "5a5eb1496c27baceb206358485f00abfca58ba49a0a9c4bd294fb2c66afb34cb",
          "sha1": "590bff9594a69d397b4d32a2fc7ab2b3fa962c03",
          "md5": "33e949a6bd6a944cca2c8d66cff7376d"
        }
      ]
    }
  ]
}
