{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-maintenance",
    "version": "1.15.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-network",
          "version": {
            "requires": "1.15.7"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.15.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-maintenance-1.15.7.aar",
          "url": "nautilus-maintenance-1.15.7.aar",
          "size": 41118,
          "sha512": "91f8a1b36fb4fbf1736d850cd7b7889df6f0e5b04201f4a2bdc6161870ca4ecbbd3ac0c756085ce05002a95fce127eaf3271e53a98847674cab6e4e4d069e292",
          "sha256": "4ef6ced3635a8df5375f83b18df1ee244540a7fe4885348b799e9a60fec2716d",
          "sha1": "efa9cdbdb422cf7ae7b281b76f340a3ed3387137",
          "md5": "4f705fc8536d1a171dbefeb3215cf075"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-network",
          "version": {
            "requires": "1.15.7"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.15.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-maintenance-1.15.7.aar",
          "url": "nautilus-maintenance-1.15.7.aar",
          "size": 41118,
          "sha512": "91f8a1b36fb4fbf1736d850cd7b7889df6f0e5b04201f4a2bdc6161870ca4ecbbd3ac0c756085ce05002a95fce127eaf3271e53a98847674cab6e4e4d069e292",
          "sha256": "4ef6ced3635a8df5375f83b18df1ee244540a7fe4885348b799e9a60fec2716d",
          "sha1": "efa9cdbdb422cf7ae7b281b76f340a3ed3387137",
          "md5": "4f705fc8536d1a171dbefeb3215cf075"
        }
      ]
    }
  ]
}
