{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-tools-logging",
    "version": "1.7.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-logging-1.7.19.aar",
          "url": "nautilus-tools-logging-1.7.19.aar",
          "size": 16667,
          "sha512": "b6cb74204b90a2e3c39eab0bb4e6007355ee127f3678cd628e5d98095aa0389cdba158d10797c8e629aca0c8cd66328b3c28dcaba3319aca66c0ba12dda15974",
          "sha256": "c6e59354782d6bbc72bf2ea3df896366e5b4a08206d3f9d6dbda349baa2c5d7b",
          "sha1": "3e3c76d397b6a36d58b57def57b988c273dd30e9",
          "md5": "3d23a61dd71353fb0ea8394fdf0f2a51"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-logging-1.7.19.aar",
          "url": "nautilus-tools-logging-1.7.19.aar",
          "size": 16667,
          "sha512": "b6cb74204b90a2e3c39eab0bb4e6007355ee127f3678cd628e5d98095aa0389cdba158d10797c8e629aca0c8cd66328b3c28dcaba3319aca66c0ba12dda15974",
          "sha256": "c6e59354782d6bbc72bf2ea3df896366e5b4a08206d3f9d6dbda349baa2c5d7b",
          "sha1": "3e3c76d397b6a36d58b57def57b988c273dd30e9",
          "md5": "3d23a61dd71353fb0ea8394fdf0f2a51"
        }
      ]
    }
  ]
}
