{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-format",
    "version": "1.15.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.15.3.aar",
          "url": "nautilus-util-format-1.15.3.aar",
          "size": 8980,
          "sha512": "67885e69f009ac9f19e3e36de0ff03c4f5e05a08d2670dd9aead2828a72bd2e8be888a971fd8468a65671ba7c2d3f1525389cefa5322b04785d8fcd4518d4122",
          "sha256": "16f3a319671d34611fef3b83aabd07c86e54a84c8254127d177fd2fbb311fd1d",
          "sha1": "5e17e0eae79abee634a9e60f6049665656cdb695",
          "md5": "cb6d70e5802ee5173ae80cdd5b3dff92"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.15.3.aar",
          "url": "nautilus-util-format-1.15.3.aar",
          "size": 8980,
          "sha512": "67885e69f009ac9f19e3e36de0ff03c4f5e05a08d2670dd9aead2828a72bd2e8be888a971fd8468a65671ba7c2d3f1525389cefa5322b04785d8fcd4518d4122",
          "sha256": "16f3a319671d34611fef3b83aabd07c86e54a84c8254127d177fd2fbb311fd1d",
          "sha1": "5e17e0eae79abee634a9e60f6049665656cdb695",
          "md5": "cb6d70e5802ee5173ae80cdd5b3dff92"
        }
      ]
    }
  ]
}
