{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-imaging",
    "version": "1.16.0-hotfix1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-network",
          "version": {
            "requires": "1.16.0-hotfix1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-imaging-1.16.0-hotfix1.aar",
          "url": "nautilus-util-imaging-1.16.0-hotfix1.aar",
          "size": 11287,
          "sha512": "6ca4e533ebed275979b18ad612e7fe77b5749abe4afb058a13f2c3db35705b13e17c1c4518332fbc129f52044ec376c36e4acd1a5c27f03ccb2180a28c45bf1f",
          "sha256": "357b57f1f2bfba86255475bad168043e95b98c1c0b1db690d7a3849de6934f64",
          "sha1": "828d0fd00514331f94ec71d205d2c2976e0542ce",
          "md5": "b0b3379999ce086f20c24830b056c2b3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-network",
          "version": {
            "requires": "1.16.0-hotfix1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-imaging-1.16.0-hotfix1.aar",
          "url": "nautilus-util-imaging-1.16.0-hotfix1.aar",
          "size": 11287,
          "sha512": "6ca4e533ebed275979b18ad612e7fe77b5749abe4afb058a13f2c3db35705b13e17c1c4518332fbc129f52044ec376c36e4acd1a5c27f03ccb2180a28c45bf1f",
          "sha256": "357b57f1f2bfba86255475bad168043e95b98c1c0b1db690d7a3849de6934f64",
          "sha1": "828d0fd00514331f94ec71d205d2c2976e0542ce",
          "md5": "b0b3379999ce086f20c24830b056c2b3"
        }
      ]
    }
  ]
}
