{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-code-image-providers",
    "version": "1.7.0-hotfix",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.7.0-hotfix"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-code-image-providers-1.7.0-hotfix.aar",
          "url": "nautilus-code-image-providers-1.7.0-hotfix.aar",
          "size": 13008,
          "sha512": "c7ba89df96e4864fa2332220a1769921faf95536e10d1794da050fb367cb38dfe4a176fafb9f9bf035306c53bfb8d652abdad9f0a99dc73943b30f1fea6a2942",
          "sha256": "f8b0e7bca61dae886ac4e4fa27ea9edeaee00b6d3b6e3388d52a4ee36863082c",
          "sha1": "c7399877866ec119e302679a3974c48ece1d1a3a",
          "md5": "e6901c1c599d706293c3a5cde332d3dd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.7.0-hotfix"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-code-image-providers-1.7.0-hotfix.aar",
          "url": "nautilus-code-image-providers-1.7.0-hotfix.aar",
          "size": 13008,
          "sha512": "c7ba89df96e4864fa2332220a1769921faf95536e10d1794da050fb367cb38dfe4a176fafb9f9bf035306c53bfb8d652abdad9f0a99dc73943b30f1fea6a2942",
          "sha256": "f8b0e7bca61dae886ac4e4fa27ea9edeaee00b6d3b6e3388d52a4ee36863082c",
          "sha1": "c7399877866ec119e302679a3974c48ece1d1a3a",
          "md5": "e6901c1c599d706293c3a5cde332d3dd"
        }
      ]
    }
  ]
}
