{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-campaign",
    "version": "1.15.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.15.4"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-format",
          "version": {
            "requires": "1.15.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-campaign-1.15.4.aar",
          "url": "nautilus-campaign-1.15.4.aar",
          "size": 138277,
          "sha512": "6acb88ee20c7c632babcc2d4fb6933fd003d529b827074eb4390e97e7ab16bc2fc46f994f9c3a5b8a0809b01a6fdb1686ff1ec77ee1c69177635a9202b6eda94",
          "sha256": "01c422bfd6a12c3f83e7771207198cc456e3af6a6c72776d06944e207349fa5e",
          "sha1": "f6abdc975cd07f7f6e0ca15497e5d7fed425dfbe",
          "md5": "1d30f124fb6d42301572dcf888b26b3a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.15.4"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-format",
          "version": {
            "requires": "1.15.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-campaign-1.15.4.aar",
          "url": "nautilus-campaign-1.15.4.aar",
          "size": 138277,
          "sha512": "6acb88ee20c7c632babcc2d4fb6933fd003d529b827074eb4390e97e7ab16bc2fc46f994f9c3a5b8a0809b01a6fdb1686ff1ec77ee1c69177635a9202b6eda94",
          "sha256": "01c422bfd6a12c3f83e7771207198cc456e3af6a6c72776d06944e207349fa5e",
          "sha1": "f6abdc975cd07f7f6e0ca15497e5d7fed425dfbe",
          "md5": "1d30f124fb6d42301572dcf888b26b3a"
        }
      ]
    }
  ]
}
