{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-network",
    "version": "1.19.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.19.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.19.6.aar",
          "url": "nautilus-util-network-1.19.6.aar",
          "size": 23283,
          "sha512": "de86eb4cb99f2aaebc43009e4e17d35e53a6f3fd581fb6cc86c63c4e8d53a39a5db582ce8142cbb60592931376962729e073c7a20efbdd9eb6b1ef949d7d5377",
          "sha256": "5b32cca7ac4a01fd62f1805a01c02063efa2606c29fee5c23525ff31ad4aed0e",
          "sha1": "6197b3655e571d5b2db58b74479b2cf32e4c9469",
          "md5": "15086703c392ad7e2f68785c27a17545"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.19.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.19.6.aar",
          "url": "nautilus-util-network-1.19.6.aar",
          "size": 23283,
          "sha512": "de86eb4cb99f2aaebc43009e4e17d35e53a6f3fd581fb6cc86c63c4e8d53a39a5db582ce8142cbb60592931376962729e073c7a20efbdd9eb6b1ef949d7d5377",
          "sha256": "5b32cca7ac4a01fd62f1805a01c02063efa2606c29fee5c23525ff31ad4aed0e",
          "sha1": "6197b3655e571d5b2db58b74479b2cf32e4c9469",
          "md5": "15086703c392ad7e2f68785c27a17545"
        }
      ]
    }
  ]
}
