{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-json",
    "version": "1.6.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-json-1.6.7.aar",
          "url": "nautilus-util-json-1.6.7.aar",
          "size": 11145,
          "sha512": "d8b661c4b06a83a90a3151cd36f1882794e8ebab4b2ea68726b3d031ded49338d2bea4c4d36b272dd6230ef9db196ffc3009bd81d003b18023904dbd23d8823c",
          "sha256": "61230bfbcf4e87c920da4f9b6f1aedf323eb53c94b35278f16667c6a411ed7cd",
          "sha1": "edf0c7f462b2234dc06c6a587753b5df966b118c",
          "md5": "56472fbf29db15c7e7f10fa276aa1381"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-json-1.6.7.aar",
          "url": "nautilus-util-json-1.6.7.aar",
          "size": 11145,
          "sha512": "d8b661c4b06a83a90a3151cd36f1882794e8ebab4b2ea68726b3d031ded49338d2bea4c4d36b272dd6230ef9db196ffc3009bd81d003b18023904dbd23d8823c",
          "sha256": "61230bfbcf4e87c920da4f9b6f1aedf323eb53c94b35278f16667c6a411ed7cd",
          "sha1": "edf0c7f462b2234dc06c6a587753b5df966b118c",
          "md5": "56472fbf29db15c7e7f10fa276aa1381"
        }
      ]
    }
  ]
}
