{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-code-image-providers",
    "version": "1.16.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.16.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-code-image-providers-1.16.3.aar",
          "url": "nautilus-code-image-providers-1.16.3.aar",
          "size": 12777,
          "sha512": "5a609d5e555231465c051725e921cbf426b59c2f9d677e14937cb0c4b8e62455d37ca9997b89d7030a8be03578f631e65be20757441d604c48bfdc902c3b0707",
          "sha256": "0892332e4f1c05aafb0385ecfdd2d2bea00ec15233508705450c02b833f656a3",
          "sha1": "493b6a1f7306d1cc128b1aa2fbece3901afb7f78",
          "md5": "faf26093face1aa48edce4d9b7c62af6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.16.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-code-image-providers-1.16.3.aar",
          "url": "nautilus-code-image-providers-1.16.3.aar",
          "size": 12777,
          "sha512": "5a609d5e555231465c051725e921cbf426b59c2f9d677e14937cb0c4b8e62455d37ca9997b89d7030a8be03578f631e65be20757441d604c48bfdc902c3b0707",
          "sha256": "0892332e4f1c05aafb0385ecfdd2d2bea00ec15233508705450c02b833f656a3",
          "sha1": "493b6a1f7306d1cc128b1aa2fbece3901afb7f78",
          "md5": "faf26093face1aa48edce4d9b7c62af6"
        }
      ]
    }
  ]
}
