{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-network",
    "version": "1.7.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.7.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.7.5.aar",
          "url": "nautilus-util-network-1.7.5.aar",
          "size": 23671,
          "sha512": "41f3a94b92ec0c842fce4a19a4fd5254f2ba2ae048c4cfe4eade56326a3e6dab914963e5cc6c73bcf172d083175a62c0ae8c1fb2558142e83cb305d2fc491aa9",
          "sha256": "d13fc2f1ba5851e3c9efd6157318177d9dfd1d442b6f5ab65b655c57d541760e",
          "sha1": "cf7aa3b6e7609739d80e705aef8ad699a9c19f32",
          "md5": "56c21f8f81b8cd1257190637f6a099e7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.7.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.7.5.aar",
          "url": "nautilus-util-network-1.7.5.aar",
          "size": 23671,
          "sha512": "41f3a94b92ec0c842fce4a19a4fd5254f2ba2ae048c4cfe4eade56326a3e6dab914963e5cc6c73bcf172d083175a62c0ae8c1fb2558142e83cb305d2fc491aa9",
          "sha256": "d13fc2f1ba5851e3c9efd6157318177d9dfd1d442b6f5ab65b655c57d541760e",
          "sha1": "cf7aa3b6e7609739d80e705aef8ad699a9c19f32",
          "md5": "56c21f8f81b8cd1257190637f6a099e7"
        }
      ]
    }
  ]
}
