{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-tools-cryptography",
    "version": "1.18.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-cryptography-1.18.1.aar",
          "url": "nautilus-tools-cryptography-1.18.1.aar",
          "size": 26332,
          "sha512": "0dcdf2c11265682eb98eb29b11c71f56eae976be09252fc32015be641f141ed0da85abb695a06c69280ad5a74946c5d6785b413e69ada8fcfefd599bb3560312",
          "sha256": "0c5bb5b8e0e3f08cba57e5ea01291ef895156889b11a691a8b3bf6c0f0bf870c",
          "sha1": "1f302b6c42f33c6ef31924437a37e3567bc15721",
          "md5": "ad3f7105c6be333f0f455dea98319929"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-cryptography-1.18.1.aar",
          "url": "nautilus-tools-cryptography-1.18.1.aar",
          "size": 26332,
          "sha512": "0dcdf2c11265682eb98eb29b11c71f56eae976be09252fc32015be641f141ed0da85abb695a06c69280ad5a74946c5d6785b413e69ada8fcfefd599bb3560312",
          "sha256": "0c5bb5b8e0e3f08cba57e5ea01291ef895156889b11a691a8b3bf6c0f0bf870c",
          "sha1": "1f302b6c42f33c6ef31924437a37e3567bc15721",
          "md5": "ad3f7105c6be333f0f455dea98319929"
        }
      ]
    }
  ]
}
