{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-format",
    "version": "1.13.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.13.6.aar",
          "url": "nautilus-util-format-1.13.6.aar",
          "size": 8948,
          "sha512": "5cfc34ebf29077dbe21c591040e48c69ec0112e387767f9b474cedc5115f8d5dbdf9ba550b05502bbebad9d75ef82f41ea0946a154ca63f811430a656649982e",
          "sha256": "a709078a1c6decf429756172847dc12e8e0302255d1beb77d28412ae325044b9",
          "sha1": "1c285730aca335207cae21cb4863692a0cdb4263",
          "md5": "9bc1ccd9bb6acb6ea158206af991fdcb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.13.6.aar",
          "url": "nautilus-util-format-1.13.6.aar",
          "size": 8948,
          "sha512": "5cfc34ebf29077dbe21c591040e48c69ec0112e387767f9b474cedc5115f8d5dbdf9ba550b05502bbebad9d75ef82f41ea0946a154ca63f811430a656649982e",
          "sha256": "a709078a1c6decf429756172847dc12e8e0302255d1beb77d28412ae325044b9",
          "sha1": "1c285730aca335207cae21cb4863692a0cdb4263",
          "md5": "9bc1ccd9bb6acb6ea158206af991fdcb"
        }
      ]
    }
  ]
}
