{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-map",
    "version": "1.9.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-map-1.9.8.aar",
          "url": "nautilus-util-map-1.9.8.aar",
          "size": 10489,
          "sha512": "9c8dc239c13bfe573fd13360ba3b2a1473a34efd4aa7e24ca96aa9668149b9a29242ee0eb4dbd1f501c9044cee694b4699c15ff499d21f33ea956517f5b3601a",
          "sha256": "e499c8fa32c0348327a124b4a934531b93c3c6e07af09ed03963b1309b336050",
          "sha1": "d94eb66aea4c2b96bea0a6b50db005b800e3b1eb",
          "md5": "4b81cdfcd61d77091faedf6539bad379"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-maps",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-map-1.9.8.aar",
          "url": "nautilus-util-map-1.9.8.aar",
          "size": 10489,
          "sha512": "9c8dc239c13bfe573fd13360ba3b2a1473a34efd4aa7e24ca96aa9668149b9a29242ee0eb4dbd1f501c9044cee694b4699c15ff499d21f33ea956517f5b3601a",
          "sha256": "e499c8fa32c0348327a124b4a934531b93c3c6e07af09ed03963b1309b336050",
          "sha1": "d94eb66aea4c2b96bea0a6b50db005b800e3b1eb",
          "md5": "4b81cdfcd61d77091faedf6539bad379"
        }
      ]
    }
  ]
}
