{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-maintenance",
    "version": "1.19.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-network",
          "version": {
            "requires": "1.19.23"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.19.23"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-config",
          "version": {
            "requires": "1.19.23"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-maintenance-1.19.23.aar",
          "url": "nautilus-maintenance-1.19.23.aar",
          "size": 42183,
          "sha512": "022e28e214027512b7ea835262c4ef0a453cd468931f36b919ee2108c9daa0c89a82ef19461f0c9996d2f80f70b183783c152fc78fc6385dcf482b8233d714fa",
          "sha256": "c1da364de9ddf1a8f55721ca6f1213f589c6c7b576bf36a0775ac52ed6067ea4",
          "sha1": "a95a6545f7f5c303fe5f4f2fdc9271281eb9b51e",
          "md5": "2af7942995ec8725d88d57a1ecd52446"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-network",
          "version": {
            "requires": "1.19.23"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.19.23"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-config",
          "version": {
            "requires": "1.19.23"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-maintenance-1.19.23.aar",
          "url": "nautilus-maintenance-1.19.23.aar",
          "size": 42183,
          "sha512": "022e28e214027512b7ea835262c4ef0a453cd468931f36b919ee2108c9daa0c89a82ef19461f0c9996d2f80f70b183783c152fc78fc6385dcf482b8233d714fa",
          "sha256": "c1da364de9ddf1a8f55721ca6f1213f589c6c7b576bf36a0775ac52ed6067ea4",
          "sha1": "a95a6545f7f5c303fe5f4f2fdc9271281eb9b51e",
          "md5": "2af7942995ec8725d88d57a1ecd52446"
        }
      ]
    }
  ]
}
