{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-tools-livedata",
    "version": "1.19.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-livedata-1.19.10.aar",
          "url": "nautilus-tools-livedata-1.19.10.aar",
          "size": 10518,
          "sha512": "be5720faa85b6b905f37201ac5b5490a8cddfce9e0b79c0e81715ce6c50ee1bdc4ef843f43cc45c58981dc84498fb7370e4e79715a36976db38460bb05ffcac2",
          "sha256": "ad218b086f72f96fe1682ef2fe19c53f9fddffd9c8a01b85663fb9a755cab522",
          "sha1": "9243101ffcbcf04904590b1b971f735a798df088",
          "md5": "fc8fc9777ffac49a95467561d726dcc2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-livedata-1.19.10.aar",
          "url": "nautilus-tools-livedata-1.19.10.aar",
          "size": 10518,
          "sha512": "be5720faa85b6b905f37201ac5b5490a8cddfce9e0b79c0e81715ce6c50ee1bdc4ef843f43cc45c58981dc84498fb7370e4e79715a36976db38460bb05ffcac2",
          "sha256": "ad218b086f72f96fe1682ef2fe19c53f9fddffd9c8a01b85663fb9a755cab522",
          "sha1": "9243101ffcbcf04904590b1b971f735a798df088",
          "md5": "fc8fc9777ffac49a95467561d726dcc2"
        }
      ]
    }
  ]
}
