{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-tools-logging",
    "version": "1.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-logging-1.4.6.aar",
          "url": "nautilus-tools-logging-1.4.6.aar",
          "size": 16703,
          "sha512": "d1373d72d855d5dbd9440664128ff0604b554e038f1b2988f7ec8d093836e01a0fdeca9aea9efe35ffc8d8cdc8a80939beeb3453522e6890e4aae0bdb7cc6ceb",
          "sha256": "663a8179d28ecb03cbbdcc86df8185a9ef646c2d3088d3d0774f2e8a5e000d78",
          "sha1": "a3322f26aba741a1bd544d5277f055a6fe092502",
          "md5": "1db1a98a47f1aacd76ed072a4934651a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-logging-1.4.6.aar",
          "url": "nautilus-tools-logging-1.4.6.aar",
          "size": 16703,
          "sha512": "d1373d72d855d5dbd9440664128ff0604b554e038f1b2988f7ec8d093836e01a0fdeca9aea9efe35ffc8d8cdc8a80939beeb3453522e6890e4aae0bdb7cc6ceb",
          "sha256": "663a8179d28ecb03cbbdcc86df8185a9ef646c2d3088d3d0774f2e8a5e000d78",
          "sha1": "a3322f26aba741a1bd544d5277f055a6fe092502",
          "md5": "1db1a98a47f1aacd76ed072a4934651a"
        }
      ]
    }
  ]
}
