{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-network",
    "version": "1.12.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.12.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.12.10.aar",
          "url": "nautilus-util-network-1.12.10.aar",
          "size": 23244,
          "sha512": "5e54b1f9be5d6952e0119f175b2a1243f10e3f22174269f9b9da1b224bc6e60f49c84f2e21977f4318848436b35f9c222e13e0a8e5747edb1c61ae8f7e9c031b",
          "sha256": "04ac9a0bbd2ab7e75ee48356bcd8886eafeac896082900264eeb0d9b7337b716",
          "sha1": "21ac4aaea6db489ad842129c0f821489c71081ae",
          "md5": "08ee2c8c5e9597f71d24c8730b8dee97"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.12.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.12.10.aar",
          "url": "nautilus-util-network-1.12.10.aar",
          "size": 23244,
          "sha512": "5e54b1f9be5d6952e0119f175b2a1243f10e3f22174269f9b9da1b224bc6e60f49c84f2e21977f4318848436b35f9c222e13e0a8e5747edb1c61ae8f7e9c031b",
          "sha256": "04ac9a0bbd2ab7e75ee48356bcd8886eafeac896082900264eeb0d9b7337b716",
          "sha1": "21ac4aaea6db489ad842129c0f821489c71081ae",
          "md5": "08ee2c8c5e9597f71d24c8730b8dee97"
        }
      ]
    }
  ]
}
