{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-tools-livedata",
    "version": "1.5.4-hotfix1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-livedata-1.5.4-hotfix1.aar",
          "url": "nautilus-tools-livedata-1.5.4-hotfix1.aar",
          "size": 10161,
          "sha512": "aa72cda7e2be865d7fe3b00030e58411fd4e6c5ac7e6e7a0cbc920f2a0dc9d5af45687a5f0ba237b5eb7c26fd9c331bccdc7b56bfc2278e4117b3719a62caec1",
          "sha256": "31f39c6249e937462c81905a7973a259fcbe4be4bd8594a74540a5e217136646",
          "sha1": "e4a52831587903ca0fab713ac597a69a6d7a69bb",
          "md5": "cb6986d03b35cdf8ceb9764f0533f500"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-livedata-1.5.4-hotfix1.aar",
          "url": "nautilus-tools-livedata-1.5.4-hotfix1.aar",
          "size": 10161,
          "sha512": "aa72cda7e2be865d7fe3b00030e58411fd4e6c5ac7e6e7a0cbc920f2a0dc9d5af45687a5f0ba237b5eb7c26fd9c331bccdc7b56bfc2278e4117b3719a62caec1",
          "sha256": "31f39c6249e937462c81905a7973a259fcbe4be4bd8594a74540a5e217136646",
          "sha1": "e4a52831587903ca0fab713ac597a69a6d7a69bb",
          "md5": "cb6986d03b35cdf8ceb9764f0533f500"
        }
      ]
    }
  ]
}
