{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-network",
    "version": "1.19.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.19.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.19.8.aar",
          "url": "nautilus-util-network-1.19.8.aar",
          "size": 23281,
          "sha512": "d8848e0bfa9396d4b124acb89f5f0155a571e5ad6680be0d11057588249b31d04cacbc314f849a5b467216b269f6f162a701acb53a0c7c41d4e4ff7372184a34",
          "sha256": "b6cce8d9e33ec3b36124e8796446d6950a808d48e7ced2a58346eb94967b1f23",
          "sha1": "cdc74a93dceac494d8e73bee8f5de05bb3bc5c7e",
          "md5": "7124ad7425655275e7d3055bdb52b32a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.19.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.19.8.aar",
          "url": "nautilus-util-network-1.19.8.aar",
          "size": 23281,
          "sha512": "d8848e0bfa9396d4b124acb89f5f0155a571e5ad6680be0d11057588249b31d04cacbc314f849a5b467216b269f6f162a701acb53a0c7c41d4e4ff7372184a34",
          "sha256": "b6cce8d9e33ec3b36124e8796446d6950a808d48e7ced2a58346eb94967b1f23",
          "sha1": "cdc74a93dceac494d8e73bee8f5de05bb3bc5c7e",
          "md5": "7124ad7425655275e7d3055bdb52b32a"
        }
      ]
    }
  ]
}
