{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-campaign",
    "version": "1.19.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.19.14"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-format",
          "version": {
            "requires": "1.19.14"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-campaign-1.19.14.aar",
          "url": "nautilus-campaign-1.19.14.aar",
          "size": 139106,
          "sha512": "67b83d772f89b8d15507ff375cd1558730aa6648d7d0775f074aaef850847dffb24b2ca06bfbe1379d87c6e631dd0d7accb0c11b978166056ba697d65094d281",
          "sha256": "8b1e3c6b6f6ff4d866a8b595fe7b5ccc39d493dc764843a9214e92b461d2d548",
          "sha1": "e40da6b68982713393f7dee6988e3d262ee3ad12",
          "md5": "2d7abd58dceb192a6f20a901e064114d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.19.14"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-util-format",
          "version": {
            "requires": "1.19.14"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-campaign-1.19.14.aar",
          "url": "nautilus-campaign-1.19.14.aar",
          "size": 139106,
          "sha512": "67b83d772f89b8d15507ff375cd1558730aa6648d7d0775f074aaef850847dffb24b2ca06bfbe1379d87c6e631dd0d7accb0c11b978166056ba697d65094d281",
          "sha256": "8b1e3c6b6f6ff4d866a8b595fe7b5ccc39d493dc764843a9214e92b461d2d548",
          "sha1": "e40da6b68982713393f7dee6988e3d262ee3ad12",
          "md5": "2d7abd58dceb192a6f20a901e064114d"
        }
      ]
    }
  ]
}
