{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-analytics-amplitude-plugin",
    "version": "1.5.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.amplitude",
          "module": "android-sdk",
          "version": {
            "requires": "2.38.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-amplitude-plugin-1.5.8.aar",
          "url": "nautilus-analytics-amplitude-plugin-1.5.8.aar",
          "size": 11817,
          "sha512": "00226998f681ae038f9408f1caa11738fa811107f23dbbb2ae759aaf47e7241268fc044a147b413804080c927d2248575906316673c9c59b8b1c96c958d5d7e9",
          "sha256": "14aad4dca75880326d6c15568bed5b2f1343f1107212fdf3060a0b3901925688",
          "sha1": "6046006b0c9b049929d2357783a9cc35285396cc",
          "md5": "de75b3d3f0b5ff539c0adb98055218c4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.amplitude",
          "module": "android-sdk",
          "version": {
            "requires": "2.38.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-analytics",
          "version": {
            "requires": "1.5.8"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.5.8"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-amplitude-plugin-1.5.8.aar",
          "url": "nautilus-analytics-amplitude-plugin-1.5.8.aar",
          "size": 11817,
          "sha512": "00226998f681ae038f9408f1caa11738fa811107f23dbbb2ae759aaf47e7241268fc044a147b413804080c927d2248575906316673c9c59b8b1c96c958d5d7e9",
          "sha256": "14aad4dca75880326d6c15568bed5b2f1343f1107212fdf3060a0b3901925688",
          "sha1": "6046006b0c9b049929d2357783a9cc35285396cc",
          "md5": "de75b3d3f0b5ff539c0adb98055218c4"
        }
      ]
    }
  ]
}
