{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-tools-logging",
    "version": "1.6.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-logging-1.6.10.aar",
          "url": "nautilus-tools-logging-1.6.10.aar",
          "size": 16672,
          "sha512": "df7572db143f1964b536d540b771d3114416329fe39f2750230bd2fd0bcee64d37366ef34238dfb2c1568ff432f6bbd87b9164a7726df4ec01c1081c78a46973",
          "sha256": "354cca019e46f15f1daf078bda878c161241a3e641c483e8da9912bd8d58a0fe",
          "sha1": "ea01a14be49feb2b13cdc6ecc1054922b605be42",
          "md5": "855d6d3924c2d02ad83396501bce458e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-logging-1.6.10.aar",
          "url": "nautilus-tools-logging-1.6.10.aar",
          "size": 16672,
          "sha512": "df7572db143f1964b536d540b771d3114416329fe39f2750230bd2fd0bcee64d37366ef34238dfb2c1568ff432f6bbd87b9164a7726df4ec01c1081c78a46973",
          "sha256": "354cca019e46f15f1daf078bda878c161241a3e641c483e8da9912bd8d58a0fe",
          "sha1": "ea01a14be49feb2b13cdc6ecc1054922b605be42",
          "md5": "855d6d3924c2d02ad83396501bce458e"
        }
      ]
    }
  ]
}
