{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-map",
    "version": "1.15.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-map-1.15.2.aar",
          "url": "nautilus-util-map-1.15.2.aar",
          "size": 10421,
          "sha512": "f713c2d3dacbb34e2cc3638f014222cf142d0fde0df3a76bcc94688161679ad4e8e8030f1a6f4be7d07a5c3128b3c7e791553e51fdffeddf900d19bbdfd1add4",
          "sha256": "6dc02eec75384c8613a93b110e91b6e2d7641ee9598e0a1d19b1e7207d800bc5",
          "sha1": "df12cb5233980cd08e7875ce9b4f1ddb4fe1fdb7",
          "md5": "c90144a9f80354c9c03845c2803163ad"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-maps",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-map-1.15.2.aar",
          "url": "nautilus-util-map-1.15.2.aar",
          "size": 10421,
          "sha512": "f713c2d3dacbb34e2cc3638f014222cf142d0fde0df3a76bcc94688161679ad4e8e8030f1a6f4be7d07a5c3128b3c7e791553e51fdffeddf900d19bbdfd1add4",
          "sha256": "6dc02eec75384c8613a93b110e91b6e2d7641ee9598e0a1d19b1e7207d800bc5",
          "sha1": "df12cb5233980cd08e7875ce9b4f1ddb4fe1fdb7",
          "md5": "c90144a9f80354c9c03845c2803163ad"
        }
      ]
    }
  ]
}
