{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-datetime",
    "version": "1.7.27-hotfix1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.7.27-hotfix1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-datetime-1.7.27-hotfix1.aar",
          "url": "nautilus-util-datetime-1.7.27-hotfix1.aar",
          "size": 15038,
          "sha512": "f005219c50f787627f366fb61e4c116928a1a09a0ab0199d528c13e414556da70af373e929692041ebaf15faa4a7d57ba2f475f0037b13fdf86237c1304a55d7",
          "sha256": "5d7ee9bbebb40c5df003d9f7c0cc9c7e7e7f7d4672d0eb6165206c30ae3358b7",
          "sha1": "61b1a784c10b8d10eec08e27c20e6c6661d76ee8",
          "md5": "eb7ea4d468ae8ff416c0dd5ecb8ab3c0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.7.27-hotfix1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.jakewharton.threetenabp",
          "module": "threetenabp",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-datetime-1.7.27-hotfix1.aar",
          "url": "nautilus-util-datetime-1.7.27-hotfix1.aar",
          "size": 15038,
          "sha512": "f005219c50f787627f366fb61e4c116928a1a09a0ab0199d528c13e414556da70af373e929692041ebaf15faa4a7d57ba2f475f0037b13fdf86237c1304a55d7",
          "sha256": "5d7ee9bbebb40c5df003d9f7c0cc9c7e7e7f7d4672d0eb6165206c30ae3358b7",
          "sha1": "61b1a784c10b8d10eec08e27c20e6c6661d76ee8",
          "md5": "eb7ea4d468ae8ff416c0dd5ecb8ab3c0"
        }
      ]
    }
  ]
}
