{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-analytics",
    "version": "1.5.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.5.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-1.5.7.aar",
          "url": "nautilus-analytics-1.5.7.aar",
          "size": 144767,
          "sha512": "1e0557da0685d7e1886779fe554b56dbb7d4ddfcda0997f78674674679d40aadb98b781123858ac0495a12caff863f7eb41a173b7f85e925dd1fb40bc6673adb",
          "sha256": "8f540531416d78e8b28ee81909be73b055a37a9ed03bec0144c05fdc63b70dbf",
          "sha1": "6e295dbd880cf6208dbc0f926bd1fcbd3c9cf429",
          "md5": "8793112e598e4b59e68a8c366962f73b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.5.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-1.5.7.aar",
          "url": "nautilus-analytics-1.5.7.aar",
          "size": 144767,
          "sha512": "1e0557da0685d7e1886779fe554b56dbb7d4ddfcda0997f78674674679d40aadb98b781123858ac0495a12caff863f7eb41a173b7f85e925dd1fb40bc6673adb",
          "sha256": "8f540531416d78e8b28ee81909be73b055a37a9ed03bec0144c05fdc63b70dbf",
          "sha1": "6e295dbd880cf6208dbc0f926bd1fcbd3c9cf429",
          "md5": "8793112e598e4b59e68a8c366962f73b"
        }
      ]
    }
  ]
}
