{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-format",
    "version": "1.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.9.0.aar",
          "url": "nautilus-util-format-1.9.0.aar",
          "size": 8947,
          "sha512": "942c86fc7062d3c75bb8046ff749adb4b6973f21ea14b6d799f3e5aa919c5c0b2ffddf8c653ea0f1ac51de78b5668027e4ff27f0da1204652657d9a2d0396a83",
          "sha256": "082014bfd786356c5796190bcc7518385a2d176252cfafc14e15ad917a0801c6",
          "sha1": "41396a64b21adfc0ac29d99b6950f02beee78f7a",
          "md5": "e0729cab3a61e6382fd081a6e561c400"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.9.0.aar",
          "url": "nautilus-util-format-1.9.0.aar",
          "size": 8947,
          "sha512": "942c86fc7062d3c75bb8046ff749adb4b6973f21ea14b6d799f3e5aa919c5c0b2ffddf8c653ea0f1ac51de78b5668027e4ff27f0da1204652657d9a2d0396a83",
          "sha256": "082014bfd786356c5796190bcc7518385a2d176252cfafc14e15ad917a0801c6",
          "sha1": "41396a64b21adfc0ac29d99b6950f02beee78f7a",
          "md5": "e0729cab3a61e6382fd081a6e561c400"
        }
      ]
    }
  ]
}
