{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-network",
    "version": "1.25.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.25.14"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.25.14.aar",
          "url": "nautilus-util-network-1.25.14.aar",
          "size": 19344,
          "sha512": "107d67d6fb1f936e7ac37314de5e6e2b0056885e484848497750a78e7e7748e287559fa15a2075ed039e12e343a3fd263921a4dfe0776f9d8515dc38be5e3d22",
          "sha256": "08ffee8fc2470b3f48f9c2c97c3aebd63053f256e1aca5144baa38d50406796e",
          "sha1": "d24423629cfc727e95581bdc6d7fed90705d5dae",
          "md5": "0d502a697f2e2cde468e6bdfc07daa2f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.3.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.3.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.15.2"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.15.2"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.25.14"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.25.14.aar",
          "url": "nautilus-util-network-1.25.14.aar",
          "size": 19344,
          "sha512": "107d67d6fb1f936e7ac37314de5e6e2b0056885e484848497750a78e7e7748e287559fa15a2075ed039e12e343a3fd263921a4dfe0776f9d8515dc38be5e3d22",
          "sha256": "08ffee8fc2470b3f48f9c2c97c3aebd63053f256e1aca5144baa38d50406796e",
          "sha1": "d24423629cfc727e95581bdc6d7fed90705d5dae",
          "md5": "0d502a697f2e2cde468e6bdfc07daa2f"
        }
      ]
    }
  ]
}
