{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-core",
    "version": "1.16.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.16.3"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-cryptography",
          "version": {
            "requires": "1.16.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-core-1.16.3.aar",
          "url": "nautilus-core-1.16.3.aar",
          "size": 107539,
          "sha512": "6bb3eb7272d9660c2d365bdc5fa4811a32a8ce5115ddd2f5eddcfaf5814c4cebe09e831df3f5c8730bafa62ebf9934c7281609b464ec14e2ff3523046e2d7dc6",
          "sha256": "c4fd02a1c283b158b8e9e0abd1c49b5995bd6361015257143029f640595186d2",
          "sha1": "a2413f52241f0147a78bb6700413214959e55c83",
          "md5": "09e4f3a10db51044a6b2cf09989d4d5e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.16.3"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-cryptography",
          "version": {
            "requires": "1.16.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-core-1.16.3.aar",
          "url": "nautilus-core-1.16.3.aar",
          "size": 107539,
          "sha512": "6bb3eb7272d9660c2d365bdc5fa4811a32a8ce5115ddd2f5eddcfaf5814c4cebe09e831df3f5c8730bafa62ebf9934c7281609b464ec14e2ff3523046e2d7dc6",
          "sha256": "c4fd02a1c283b158b8e9e0abd1c49b5995bd6361015257143029f640595186d2",
          "sha1": "a2413f52241f0147a78bb6700413214959e55c83",
          "md5": "09e4f3a10db51044a6b2cf09989d4d5e"
        }
      ]
    }
  ]
}
