{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-analytics",
    "version": "1.7.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.7.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-1.7.5.aar",
          "url": "nautilus-analytics-1.7.5.aar",
          "size": 157562,
          "sha512": "4a36b45392baa6c3a8f2979c4edfecbf64fc39bac84bd701b0657a1d49c7ab5b0a55a3793cb0df333fbe8579979b5ad3ea431808692bb8d483de0d366da5760c",
          "sha256": "85a01e8d753d94204109b309ed7556f824cf611f09bb5692ac2d2a5876f0663e",
          "sha1": "4a45a044bf053d79f826dbcb5d0da784006e793b",
          "md5": "15dba6dcac064a239257cae81bfdde1b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.7.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-1.7.5.aar",
          "url": "nautilus-analytics-1.7.5.aar",
          "size": 157562,
          "sha512": "4a36b45392baa6c3a8f2979c4edfecbf64fc39bac84bd701b0657a1d49c7ab5b0a55a3793cb0df333fbe8579979b5ad3ea431808692bb8d483de0d366da5760c",
          "sha256": "85a01e8d753d94204109b309ed7556f824cf611f09bb5692ac2d2a5876f0663e",
          "sha1": "4a45a044bf053d79f826dbcb5d0da784006e793b",
          "md5": "15dba6dcac064a239257cae81bfdde1b"
        }
      ]
    }
  ]
}
