{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-analytics",
    "version": "1.7.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.7.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-1.7.5.aar",
          "url": "nautilus-analytics-1.7.5.aar",
          "size": 157562,
          "sha512": "b01a495a7a8676bd3188955895cc500c50de389fed48e45076a5856601094ef88ed7711385d920f2cf4f4954b6e71331be1a3f19c56fd15fa1ac1dabca1c157a",
          "sha256": "486eefbd09ad15c553ab8438f845f90a2743866e3af4f877e130aa05247e8f43",
          "sha1": "d6c6b6389667f2d59cbf490b11d9374b7897a3cd",
          "md5": "49dc1704dab1ba0f35c79500728f412f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.7.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-1.7.5.aar",
          "url": "nautilus-analytics-1.7.5.aar",
          "size": 157562,
          "sha512": "b01a495a7a8676bd3188955895cc500c50de389fed48e45076a5856601094ef88ed7711385d920f2cf4f4954b6e71331be1a3f19c56fd15fa1ac1dabca1c157a",
          "sha256": "486eefbd09ad15c553ab8438f845f90a2743866e3af4f877e130aa05247e8f43",
          "sha1": "d6c6b6389667f2d59cbf490b11d9374b7897a3cd",
          "md5": "49dc1704dab1ba0f35c79500728f412f"
        }
      ]
    }
  ]
}
