{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-datetime",
    "version": "1.7.0-hotfix",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.7.0-hotfix"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-datetime-1.7.0-hotfix.aar",
          "url": "nautilus-util-datetime-1.7.0-hotfix.aar",
          "size": 15051,
          "sha512": "4bf51b2807aa21bafc33ea68277952a9171f207e552cd2331c04b86c6926330729f40a0383d66e7a7ee90ebf97a99d7d1666998f2b7b82b6c010b790a6f32bea",
          "sha256": "fdf03ce483e4bcf4cb46967ebc273c00547213575f29f7d1ff73249c1beb501d",
          "sha1": "c4c9de8d96991ef142a5a269445b97548aa43d5b",
          "md5": "6e3b1c1b29d823f1dffc71e8df7e37ec"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.7.0-hotfix"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.jakewharton.threetenabp",
          "module": "threetenabp",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-datetime-1.7.0-hotfix.aar",
          "url": "nautilus-util-datetime-1.7.0-hotfix.aar",
          "size": 15051,
          "sha512": "4bf51b2807aa21bafc33ea68277952a9171f207e552cd2331c04b86c6926330729f40a0383d66e7a7ee90ebf97a99d7d1666998f2b7b82b6c010b790a6f32bea",
          "sha256": "fdf03ce483e4bcf4cb46967ebc273c00547213575f29f7d1ff73249c1beb501d",
          "sha1": "c4c9de8d96991ef142a5a269445b97548aa43d5b",
          "md5": "6e3b1c1b29d823f1dffc71e8df7e37ec"
        }
      ]
    }
  ]
}
