{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-tools-livedata",
    "version": "1.19.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-livedata-1.19.21.aar",
          "url": "nautilus-tools-livedata-1.19.21.aar",
          "size": 10512,
          "sha512": "1c34393dc1d6e6f57535a20be68857dfaf6acdf00ef4063b10015b2788fc9a6f2a870d7e54f62d01d466567f28adf5b684670e2f07f50f7b759b05d08af13032",
          "sha256": "b5dcdb3bd01491ea2062d14cc56739fee44421e734f21227dd97c34683aa2a07",
          "sha1": "96bb149d4241ca5347f4074dc67db4c06d8e411b",
          "md5": "2fd5cc45fde909f72364fe5234aea9a0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-livedata-1.19.21.aar",
          "url": "nautilus-tools-livedata-1.19.21.aar",
          "size": 10512,
          "sha512": "1c34393dc1d6e6f57535a20be68857dfaf6acdf00ef4063b10015b2788fc9a6f2a870d7e54f62d01d466567f28adf5b684670e2f07f50f7b759b05d08af13032",
          "sha256": "b5dcdb3bd01491ea2062d14cc56739fee44421e734f21227dd97c34683aa2a07",
          "sha1": "96bb149d4241ca5347f4074dc67db4c06d8e411b",
          "md5": "2fd5cc45fde909f72364fe5234aea9a0"
        }
      ]
    }
  ]
}
