{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-network",
    "version": "1.9.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.9.3.aar",
          "url": "nautilus-util-network-1.9.3.aar",
          "size": 23248,
          "sha512": "71900f171a936c720ef21063bb4a982b82ca3356081d10d7a20f43dd5d6b6b8e9f3bb96fde554f98b3409d4ffe8e9f7a9b1be05b1110ac27703a48652479067b",
          "sha256": "a7c83d02be51d11cc191d50331f54dbacc5494b48c9069be1d2fb2e8da87a77f",
          "sha1": "c5b044ce015ab29a77863453aaf8044c370833da",
          "md5": "7051a91f05a2b51ffaf572535e9ef3ea"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.9.3.aar",
          "url": "nautilus-util-network-1.9.3.aar",
          "size": 23248,
          "sha512": "71900f171a936c720ef21063bb4a982b82ca3356081d10d7a20f43dd5d6b6b8e9f3bb96fde554f98b3409d4ffe8e9f7a9b1be05b1110ac27703a48652479067b",
          "sha256": "a7c83d02be51d11cc191d50331f54dbacc5494b48c9069be1d2fb2e8da87a77f",
          "sha1": "c5b044ce015ab29a77863453aaf8044c370833da",
          "md5": "7051a91f05a2b51ffaf572535e9ef3ea"
        }
      ]
    }
  ]
}
