{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-format",
    "version": "1.6.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.6.4.aar",
          "url": "nautilus-util-format-1.6.4.aar",
          "size": 8806,
          "sha512": "1035960c2a81987a1d94c35f96d045e3a72ec078396605141cae25b802274336c686883def6c41722cb71efb092d60c8070eb649534ee4b6def1090f55039eed",
          "sha256": "40eef992830adf8892b7b5a96fecb93d7e378bcbce8a994be32e42db663782fa",
          "sha1": "83a2cd88e511c59b2d169ce32a4480042fee7d93",
          "md5": "680a966541598b5c3ebb2336da74b67c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-format-1.6.4.aar",
          "url": "nautilus-util-format-1.6.4.aar",
          "size": 8806,
          "sha512": "1035960c2a81987a1d94c35f96d045e3a72ec078396605141cae25b802274336c686883def6c41722cb71efb092d60c8070eb649534ee4b6def1090f55039eed",
          "sha256": "40eef992830adf8892b7b5a96fecb93d7e378bcbce8a994be32e42db663782fa",
          "sha1": "83a2cd88e511c59b2d169ce32a4480042fee7d93",
          "md5": "680a966541598b5c3ebb2336da74b67c"
        }
      ]
    }
  ]
}
