{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-lottery",
    "version": "1.7.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.7.5"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-config",
          "version": {
            "requires": "1.7.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-lottery-1.7.5.aar",
          "url": "nautilus-lottery-1.7.5.aar",
          "size": 95789,
          "sha512": "3eb30bf9083cdbc0ffb37bda777a6b99ec78638fc560e7f599b61054c6eecfcf95b88ea1a5eed213bdd540c5f6ce7e77f3566396a038571f6a23a7d9024aae8e",
          "sha256": "a83cdc6cdd2f692a39eb6fdfef9f0193f0b6bcefb85a53603d4d7ba32ff58e5a",
          "sha1": "4e325fc8ffa61b51627df4f5b734a0bd19ab0549",
          "md5": "77ed35e2c0d173c2ae4d686bf1b06faa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-identify",
          "version": {
            "requires": "1.7.5"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-config",
          "version": {
            "requires": "1.7.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-lottery-1.7.5.aar",
          "url": "nautilus-lottery-1.7.5.aar",
          "size": 95789,
          "sha512": "3eb30bf9083cdbc0ffb37bda777a6b99ec78638fc560e7f599b61054c6eecfcf95b88ea1a5eed213bdd540c5f6ce7e77f3566396a038571f6a23a7d9024aae8e",
          "sha256": "a83cdc6cdd2f692a39eb6fdfef9f0193f0b6bcefb85a53603d4d7ba32ff58e5a",
          "sha1": "4e325fc8ffa61b51627df4f5b734a0bd19ab0549",
          "md5": "77ed35e2c0d173c2ae4d686bf1b06faa"
        }
      ]
    }
  ]
}
