{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-tools-cryptography",
    "version": "1.16.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-cryptography-1.16.5.aar",
          "url": "nautilus-tools-cryptography-1.16.5.aar",
          "size": 26329,
          "sha512": "2c9ef7eee33226920ee7e2567bb52c3b81d64b9c27ef464032753849170c523623c015fba5f72333a962ad626e0642e5f04bac5dbe34dc1b8179a61cb713baf0",
          "sha256": "feeabf8d71148c1e8d0a9233c37d7e7a1d6ac25559ef2bb725a6e50163d7977d",
          "sha1": "1b912f8bc8161c0a5182d0f39e7d0d0b4c1bec51",
          "md5": "c1816762558e7e82a635fcf6ddd12bac"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-tools-cryptography-1.16.5.aar",
          "url": "nautilus-tools-cryptography-1.16.5.aar",
          "size": 26329,
          "sha512": "2c9ef7eee33226920ee7e2567bb52c3b81d64b9c27ef464032753849170c523623c015fba5f72333a962ad626e0642e5f04bac5dbe34dc1b8179a61cb713baf0",
          "sha256": "feeabf8d71148c1e8d0a9233c37d7e7a1d6ac25559ef2bb725a6e50163d7977d",
          "sha1": "1b912f8bc8161c0a5182d0f39e7d0d0b4c1bec51",
          "md5": "c1816762558e7e82a635fcf6ddd12bac"
        }
      ]
    }
  ]
}
