{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-util-network",
    "version": "1.19.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.19.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.19.7.aar",
          "url": "nautilus-util-network-1.19.7.aar",
          "size": 23280,
          "sha512": "bada5babc2f9d37a6ccf28e7726240760e1ba5e1d0392895e4bb2c242e7507de035cedf805ff5bcc620b170f2c6e27469b959b9d35bf4c0b25694fefc2a47345",
          "sha256": "1d8a4ea8f39be1fedfbd316e151d8c7881ca9697e8139a6c6a1f12b993a7cc7b",
          "sha1": "1e84d2d6ef7e27d5c3339206d55e41d9ee5a8645",
          "md5": "1bb386d97d93a754310267415f1cf2c4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-tools-logging",
          "version": {
            "requires": "1.19.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-util-network-1.19.7.aar",
          "url": "nautilus-util-network-1.19.7.aar",
          "size": 23280,
          "sha512": "bada5babc2f9d37a6ccf28e7726240760e1ba5e1d0392895e4bb2c242e7507de035cedf805ff5bcc620b170f2c6e27469b959b9d35bf4c0b25694fefc2a47345",
          "sha256": "1d8a4ea8f39be1fedfbd316e151d8c7881ca9697e8139a6c6a1f12b993a7cc7b",
          "sha1": "1e84d2d6ef7e27d5c3339206d55e41d9ee5a8645",
          "md5": "1bb386d97d93a754310267415f1cf2c4"
        }
      ]
    }
  ]
}
