{
  "formatVersion": "1.1",
  "component": {
    "group": "com.locationvalue.ma2.nautilus",
    "module": "nautilus-analytics",
    "version": "1.19.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.19.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-1.19.9.aar",
          "url": "nautilus-analytics-1.19.9.aar",
          "size": 166581,
          "sha512": "36214f8f0ac011600513d0c7fe0143d85ab614dd047edcf67b65b57cdddc55d956c988fad6c8c82bba5c0370a39f4098aa38aa77bccd06653cd3b60e7daa224a",
          "sha256": "212ca1e406b5e45c30f6bacd5a66d595718a48dd7884981870133bd9cc4ae60e",
          "sha1": "5b301600df09aded486f64e5fa060753db1b222d",
          "md5": "dc4a3fd38d9345ff33d0d61805d42232"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.locationvalue.ma2.nautilus",
          "module": "nautilus-core",
          "version": {
            "requires": "1.19.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "nautilus-analytics-1.19.9.aar",
          "url": "nautilus-analytics-1.19.9.aar",
          "size": 166581,
          "sha512": "36214f8f0ac011600513d0c7fe0143d85ab614dd047edcf67b65b57cdddc55d956c988fad6c8c82bba5c0370a39f4098aa38aa77bccd06653cd3b60e7daa224a",
          "sha256": "212ca1e406b5e45c30f6bacd5a66d595718a48dd7884981870133bd9cc4ae60e",
          "sha1": "5b301600df09aded486f64e5fa060753db1b222d",
          "md5": "dc4a3fd38d9345ff33d0d61805d42232"
        }
      ]
    }
  ]
}
